import type { QuotationRecord } from "./types.js";

const hours = (h: number) =>
  new Date(Date.now() - h * 3_600_000).toISOString();
const days = (d: number) =>
  new Date(Date.now() - d * 86_400_000).toISOString();
const futureDays = (d: number) =>
  new Date(Date.now() + d * 86_400_000).toISOString();

export const quotationRecordsFixture: QuotationRecord[] = [
  {
    id: "qt-889-v2",
    publicCode: "QT-889",
    status: "issued",
    versionNumber: 2,
    familyId: "fam-889",
    procurementRequestId: "pr-1042",
    procurementRequestCode: "PR-1042",
    supplierId: "sup-valve-co",
    supplierName: "Ningbo Precision Valves Co., Ltd",
    currencyCode: "USD",
    subtotalAmount: 44_000,
    discountAmount: 1_500,
    taxAmount: 0,
    shippingAmount: 2_000,
    dutyAmount: 0,
    otherAmount: 0,
    totalAmount: 44_500,
    expiresAt: futureDays(5),
    deliveryLeadTimeDays: 24,
    minimumOrderQuantity: 20,
    paymentTerms: "30% deposit, balance against BL copy",
    commercialTerms: "Ex-works Ningbo. Inspection available on request.",
    rowVersion: 5,
    createdAt: hours(30),
    updatedAt: hours(20),
    items: [
      {
        id: "qi1",
        description: "Gate valve DN50 PN16",
        quantity: 120,
        unitAmount: 90,
        lineAmount: 10_800,
      },
      {
        id: "qi2",
        description: "Ball valve DN80",
        quantity: 40,
        unitAmount: 155,
        lineAmount: 6_200,
      },
    ],
    attachments: [
      {
        id: "qd1",
        name: "QT-889-v2.pdf",
        href: "#",
        kind: "pdf",
        uploadedAt: hours(20),
      },
      {
        id: "qd2",
        name: "datasheet-pack.zip",
        href: "#",
        kind: "bundle",
        uploadedAt: hours(22),
      },
    ],
    versions: [
      {
        id: "qt-889-v1",
        versionNumber: 1,
        publicCode: "QT-889",
        status: "superseded",
        totalAmount: 46_200,
        createdAt: days(4),
      },
      {
        id: "qt-889-v2",
        versionNumber: 2,
        publicCode: "QT-889",
        status: "issued",
        totalAmount: 44_500,
        createdAt: hours(30),
        current: true,
      },
    ],
    history: [
      {
        id: "qh1",
        fromStatus: null,
        toStatus: "draft",
        command: "create",
        actorName: "James Nwosu",
        createdAt: days(4),
      },
      {
        id: "qh2",
        fromStatus: "draft",
        toStatus: "internally_reviewed",
        command: "review",
        actorName: "James Nwosu",
        createdAt: days(3),
      },
      {
        id: "qh3",
        fromStatus: "internally_reviewed",
        toStatus: "issued",
        command: "issue",
        actorName: "James Nwosu",
        createdAt: days(3),
      },
      {
        id: "qh4",
        fromStatus: "issued",
        toStatus: "superseded",
        command: "revise",
        reason: "Buyer requested discount and faster lead time",
        actorName: "James Nwosu",
        createdAt: hours(30),
      },
      {
        id: "qh5",
        fromStatus: "draft",
        toStatus: "issued",
        command: "issue",
        actorName: "James Nwosu",
        createdAt: hours(20),
      },
    ],
    negotiation: [
      {
        id: "n1",
        authorName: "Ada Okonkwo",
        body: "Please improve discount to at least 3% and confirm 24-day lead.",
        createdAt: days(3.5),
        kind: "buyer",
      },
      {
        id: "n2",
        authorName: "James Nwosu",
        body: "Revised v2 with USD 1,500 discount and 24-day typical lead.",
        createdAt: hours(28),
        kind: "ops",
      },
    ],
  },
  {
    id: "qt-910",
    publicCode: "QT-910",
    status: "draft",
    versionNumber: 1,
    familyId: "fam-910",
    procurementRequestId: "pr-881",
    procurementRequestCode: "PR-881",
    supplierId: "sup-chem",
    supplierName: "Gulf Specialty Chemicals FZE",
    currencyCode: "USD",
    subtotalAmount: 11_200,
    discountAmount: 0,
    taxAmount: 560,
    shippingAmount: 400,
    dutyAmount: 0,
    otherAmount: 0,
    totalAmount: 12_160,
    expiresAt: futureDays(10),
    deliveryLeadTimeDays: 28,
    paymentTerms: "Net 15",
    commercialTerms: "Draft - pending SDS pack.",
    rowVersion: 1,
    createdAt: hours(8),
    updatedAt: hours(2),
    items: [
      {
        id: "qi3",
        description: "Industrial solvent blend",
        quantity: 4,
        unitAmount: 2_800,
        lineAmount: 11_200,
      },
    ],
    attachments: [],
    versions: [
      {
        id: "qt-910",
        versionNumber: 1,
        publicCode: "QT-910",
        status: "draft",
        totalAmount: 12_160,
        createdAt: hours(8),
        current: true,
      },
    ],
    history: [
      {
        id: "qh6",
        toStatus: "draft",
        command: "create",
        actorName: "James Nwosu",
        createdAt: hours(8),
      },
    ],
    negotiation: [],
  },
  {
    id: "qt-700",
    publicCode: "QT-700",
    status: "accepted",
    versionNumber: 1,
    familyId: "fam-700",
    procurementRequestId: "pr-700",
    procurementRequestCode: "PR-700",
    supplierName: "Lagos Pack Systems Ltd",
    currencyCode: "USD",
    subtotalAmount: 2_200,
    discountAmount: 100,
    taxAmount: 0,
    shippingAmount: 50,
    dutyAmount: 0,
    otherAmount: 0,
    totalAmount: 2_150,
    expiresAt: days(20),
    rowVersion: 4,
    createdAt: days(50),
    updatedAt: days(45),
    items: [
      {
        id: "qi4",
        description: "Stretch wrap rolls",
        quantity: 200,
        unitAmount: 11,
        lineAmount: 2_200,
      },
    ],
    attachments: [
      {
        id: "qd3",
        name: "QT-700-accepted.pdf",
        href: "#",
        uploadedAt: days(45),
      },
    ],
    versions: [
      {
        id: "qt-700",
        versionNumber: 1,
        publicCode: "QT-700",
        status: "accepted",
        totalAmount: 2_150,
        createdAt: days(50),
        current: true,
      },
    ],
    history: [
      {
        id: "qh7",
        fromStatus: "issued",
        toStatus: "accepted",
        command: "accept",
        actorName: "Ada Okonkwo",
        createdAt: days(45),
      },
    ],
    negotiation: [],
  },
  {
    id: "qt-512",
    publicCode: "QT-512",
    status: "declined",
    versionNumber: 1,
    familyId: "fam-512",
    procurementRequestId: "pr-512",
    procurementRequestCode: "PR-512",
    supplierName: "Ankara Steel Traders AS",
    currencyCode: "USD",
    subtotalAmount: 8_000,
    discountAmount: 0,
    taxAmount: 0,
    shippingAmount: 900,
    dutyAmount: 200,
    otherAmount: 0,
    totalAmount: 9_100,
    expiresAt: days(10),
    rowVersion: 3,
    createdAt: days(58),
    updatedAt: days(56),
    items: [
      {
        id: "qi5",
        description: "HR coil sample",
        quantity: 2,
        unitAmount: 4_000,
        lineAmount: 8_000,
      },
    ],
    attachments: [],
    versions: [
      {
        id: "qt-512",
        versionNumber: 1,
        publicCode: "QT-512",
        status: "declined",
        totalAmount: 9_100,
        createdAt: days(58),
        current: true,
      },
    ],
    history: [
      {
        id: "qh8",
        fromStatus: "issued",
        toStatus: "declined",
        command: "decline",
        reason: "Lead time unacceptable",
        actorName: "Leo Mensah",
        createdAt: days(56),
      },
    ],
    negotiation: [
      {
        id: "n3",
        authorName: "Leo Mensah",
        body: "Cannot accept 45-day lead for trial lot.",
        createdAt: days(56),
        kind: "buyer",
      },
    ],
  },
];
