import type { AnalyticsSnapshot } from "./types.js";

const hours = (h: number) =>
  new Date(Date.now() - h * 3_600_000).toISOString();

const trend = (base: number, step = 1.08) =>
  ["W1", "W2", "W3", "W4", "W5", "W6"].map((label, i) => ({
    label,
    value: Math.round(base * step ** i),
  }));

/** Mission coverage fixture - all track metrics populated. */
export const analyticsSnapshotFixture: AnalyticsSnapshot = {
  generatedAt: hours(0.2),
  timezone: "Africa/Lagos",
  currency: "USD",
  metrics: [
    {
      key: "visitors",
      label: "Visitors",
      value: "48.2k",
      delta: "+6.4% vs prior",
      tone: "positive",
      definition: "Unique consented website sessions excluding bots/test.",
      freshnessAt: hours(0.5),
      series: trend(6200),
    },
    {
      key: "registered_users",
      label: "Registered users",
      value: "1,284",
      delta: "+112 new",
      tone: "positive",
      definition: "Verified organization accounts activated in range.",
      freshnessAt: hours(1),
      series: trend(180, 1.05),
    },
    {
      key: "conversion_rate",
      label: "Conversion rate",
      value: "3.8%",
      unit: "%",
      delta: "+0.3 pts",
      tone: "positive",
      definition: "Visitor → qualified procurement request completion.",
      freshnessAt: hours(1),
      series: [
        { label: "W1", value: 3.1 },
        { label: "W2", value: 3.3 },
        { label: "W3", value: 3.5 },
        { label: "W4", value: 3.4 },
        { label: "W5", value: 3.7 },
        { label: "W6", value: 3.8 },
      ],
    },
    {
      key: "procurement_requests",
      label: "Procurement requests",
      value: "642",
      delta: "+8.1%",
      tone: "positive",
      definition: "Submitted requests (not drafts) in selected period.",
      freshnessAt: hours(0.4),
      series: trend(85, 1.07),
    },
    {
      key: "supplier_activity",
      label: "Supplier activity",
      value: "2,110",
      delta: "Responses + quotes",
      tone: "neutral",
      definition: "Supplier quote submissions and RFQ responses.",
      freshnessAt: hours(0.6),
      series: trend(280, 1.04),
    },
    {
      key: "quotation_acceptance",
      label: "Quotation acceptance",
      value: "41%",
      unit: "%",
      delta: "-2 pts",
      tone: "warning",
      definition: "Accepted quotations / issued quotations.",
      freshnessAt: hours(0.8),
      series: [
        { label: "W1", value: 44 },
        { label: "W2", value: 43 },
        { label: "W3", value: 42 },
        { label: "W4", value: 40 },
        { label: "W5", value: 41 },
        { label: "W6", value: 41 },
      ],
    },
    {
      key: "revenue",
      label: "Revenue",
      value: "$1.84M",
      delta: "+12% recognized",
      tone: "positive",
      definition: "Recognized commercial revenue (not pipeline).",
      freshnessAt: hours(2),
      series: trend(240000, 1.06),
    },
    {
      key: "response_time",
      label: "Response time",
      value: "4.6h",
      delta: "-0.8h median",
      tone: "positive",
      definition: "Median first operational response on open requests.",
      freshnessAt: hours(0.3),
      series: [
        { label: "W1", value: 6.2 },
        { label: "W2", value: 5.8 },
        { label: "W3", value: 5.4 },
        { label: "W4", value: 5.1 },
        { label: "W5", value: 4.9 },
        { label: "W6", value: 4.6 },
      ],
    },
    {
      key: "order_completion",
      label: "Order completion",
      value: "92%",
      unit: "%",
      delta: "+1.4 pts OTIF proxy",
      tone: "positive",
      definition: "Closed POs delivered against committed window.",
      freshnessAt: hours(1.5),
      series: [
        { label: "W1", value: 88 },
        { label: "W2", value: 89 },
        { label: "W3", value: 90 },
        { label: "W4", value: 91 },
        { label: "W5", value: 91 },
        { label: "W6", value: 92 },
      ],
    },
    {
      key: "customer_satisfaction",
      label: "Customer satisfaction",
      value: "4.6 / 5",
      delta: "CSAT rolling",
      tone: "positive",
      definition: "Post-delivery CSAT average (consented responses).",
      freshnessAt: hours(3),
      series: [
        { label: "W1", value: 4.4 },
        { label: "W2", value: 4.5 },
        { label: "W3", value: 4.5 },
        { label: "W4", value: 4.6 },
        { label: "W5", value: 4.5 },
        { label: "W6", value: 4.6 },
      ],
    },
  ],
};
