// Curated presentation taxonomy, not a snapshot of stock or publication status.
// Generated by scripts/optimize-canonical-presentation.py from the approved artwork.
export const CANONICAL_PRESENTATION = [
  {
    "slug": "iphones-gadgets",
    "name": "Electronics, Mobile & Digital Technology",
    "src": "/media/presentation/v2/international/iphones-gadgets.webp",
    "alt": "Commercial arrangement of smartphones, laptops, networking devices and digital accessories for procurement",
    "business": "International"
  },
  {
    "slug": "medical-equipments",
    "name": "Medical, Healthcare & Laboratory Equipment",
    "src": "/media/presentation/v2/international/medical-equipments.webp",
    "alt": "Healthcare and laboratory equipment arranged in a clean professional procurement setting",
    "business": "International"
  },
  {
    "slug": "home-garden-wares",
    "name": "Home, Garden & Facility Supplies",
    "src": "/media/presentation/v2/international/home-garden-wares.webp",
    "alt": "Home, garden and facility equipment arranged in a modern commercial environment",
    "business": "International"
  },
  {
    "slug": "machineries",
    "name": "Industrial Machinery, Tools & Processing Equipment",
    "src": "/media/presentation/v2/international/machineries.webp",
    "alt": "Industrial machines, workshop tools and processing equipment in a professional procurement display",
    "business": "International"
  },
  {
    "slug": "general-procurement",
    "name": "General Procurement & Custom Sourcing",
    "src": "/media/presentation/v2/international/general-procurement.webp",
    "alt": "Assorted professional procurement supplies, packaging, safety items and business materials",
    "business": "International"
  },
  {
    "slug": "home-appliances",
    "name": "Home Appliances & Living Equipment",
    "src": "/media/presentation/v2/international/home-appliances.webp",
    "alt": "Modern refrigeration, laundry, kitchen and household appliances arranged for procurement",
    "business": "International"
  },
  {
    "slug": "office-business",
    "name": "Office, Business & Commercial Technology",
    "src": "/media/presentation/v2/international/office-business.webp",
    "alt": "Professional office furniture, point-of-sale equipment and commercial technology",
    "business": "International"
  },
  {
    "slug": "fashion-textiles",
    "name": "Fashion, Textiles, Uniforms & Accessories",
    "src": "/media/presentation/v2/international/fashion-textiles.webp",
    "alt": "Professional display of fabrics, uniforms, footwear and fashion accessories for procurement",
    "business": "International"
  },
  {
    "slug": "beauty-spa-salon",
    "name": "Beauty, Salon & Spa Equipment",
    "src": "/media/presentation/v2/international/beauty-spa-salon.webp",
    "alt": "Professional salon and spa chairs, mirrors, hair tools and beauty equipment",
    "business": "International"
  },
  {
    "slug": "retail-store-setup",
    "name": "Retail, Store Setup & Merchandising Equipment",
    "src": "/media/presentation/v2/international/retail-store-setup.webp",
    "alt": "Retail shelving, checkout counters, display racks and merchandising equipment in a modern store",
    "business": "International"
  },
  {
    "slug": "sesame-seeds",
    "name": "Sesame Seeds",
    "src": "/media/presentation/v2/ie/sesame-seeds.webp",
    "alt": "Sesame Seeds",
    "business": "IE"
  },
  {
    "slug": "cashew",
    "name": "Cashew",
    "src": "/media/presentation/v2/ie/cashew.webp",
    "alt": "Cashew",
    "business": "IE"
  },
  {
    "slug": "ginger",
    "name": "Ginger",
    "src": "/media/presentation/v2/ie/ginger.webp",
    "alt": "Ginger",
    "business": "IE"
  },
  {
    "slug": "hibiscus",
    "name": "Hibiscus",
    "src": "/media/presentation/v2/ie/hibiscus.webp",
    "alt": "Hibiscus",
    "business": "IE"
  },
  {
    "slug": "shea",
    "name": "Shea",
    "src": "/media/presentation/v2/ie/shea.webp",
    "alt": "Shea",
    "business": "IE"
  },
  {
    "slug": "soybean",
    "name": "Soybean",
    "src": "/media/presentation/v2/ie/soybean.webp",
    "alt": "Soybean",
    "business": "IE"
  },
  {
    "slug": "cocoa",
    "name": "Cocoa",
    "src": "/media/presentation/v2/ie/cocoa.webp",
    "alt": "Cocoa",
    "business": "IE"
  }
] as const;
