/**
 * IE-IMAGE-02 International category extras (acquired WebP).
 * Generated from docs/ie-image-02-provenance.json - do not hand-edit filenames.
 * Does not replace INTERNATIONAL_CATEGORY_MEDIA primary JPGs.
 */
import type { MediaAsset } from "./media-assets.js";

export const INTERNATIONAL_CATEGORY_STAGED_MEDIA = {
  "iphones-gadgets": [
    {
      id: "INTL-IPHONES_GADGETS-HERO-01",
      src: "/media/international/categories/iphones-gadgets/hero/intl-iphones-gadgets-hero-01.webp",
      alt: "Representative imagery for iPhones & Gadgets (hero)",
      kind: "representative" as const,
      authenticity: "representative" as const,
      subject: "smartphone hero",
      source: "Unsplash - Neil Son, photo-1511707171634-5f897ff02aa9",
      license: "Unsplash License",
      licenseUrl: "https://unsplash.com/license",
      downloadDate: "2026-08-17",
      usedOn: ["/", "/products"] as const,
    },
    {
      id: "INTL-IPHONES_GADGETS-HERO-02",
      src: "/media/international/categories/iphones-gadgets/hero/intl-iphones-gadgets-hero-02.webp",
      alt: "Representative imagery for iPhones & Gadgets (hero)",
      kind: "representative" as const,
      authenticity: "representative" as const,
      subject: "phone hero (remapped verified Unsplash id)",
      source: "Unsplash - Unsplash contributor, photo-1557800636-894a64c1696f",
      license: "Unsplash License",
      licenseUrl: "https://unsplash.com/license",
      downloadDate: "2026-08-17",
      usedOn: ["/", "/products"] as const,
    },
    {
      id: "INTL-IPHONES_GADGETS-HERO-03",
      src: "/media/international/categories/iphones-gadgets/hero/intl-iphones-gadgets-hero-03.webp",
      alt: "Representative imagery for iPhones & Gadgets (hero)",
      kind: "representative" as const,
      authenticity: "representative" as const,
      subject: "phone desk (remapped verified Unsplash id)",
      source: "Unsplash - Unsplash contributor, photo-1504674900247-0877df9cc836",
      license: "Unsplash License",
      licenseUrl: "https://unsplash.com/license",
      downloadDate: "2026-08-17",
      usedOn: ["/", "/products"] as const,
    },
    {
      id: "INTL-IPHONES_GADGETS-PRODUCT-01",
      src: "/media/international/categories/iphones-gadgets/gallery/intl-iphones-gadgets-product-01.webp",
      alt: "Representative imagery for iPhones & Gadgets (product)",
      kind: "representative" as const,
      authenticity: "representative" as const,
      subject: "phones product",
      source: "Unsplash - Tamas Pap, photo-1556656793-08538906a9f8",
      license: "Unsplash License",
      licenseUrl: "https://unsplash.com/license",
      downloadDate: "2026-08-17",
      usedOn: ["/", "/products"] as const,
    },
    {
      id: "INTL-IPHONES_GADGETS-PRODUCT-02",
      src: "/media/international/categories/iphones-gadgets/gallery/intl-iphones-gadgets-product-02.webp",
      alt: "Representative imagery for iPhones & Gadgets (product)",
      kind: "representative" as const,
      authenticity: "representative" as const,
      subject: "gadgets",
      source: "Unsplash - Daniel Korpai, photo-1601784551446-20c9e07cdbdb",
      license: "Unsplash License",
      licenseUrl: "https://unsplash.com/license",
      downloadDate: "2026-08-17",
      usedOn: ["/", "/products"] as const,
    },
    {
      id: "INTL-IPHONES_GADGETS-PRODUCT-03",
      src: "/media/international/categories/iphones-gadgets/gallery/intl-iphones-gadgets-product-03.webp",
      alt: "Representative imagery for iPhones & Gadgets (product)",
      kind: "representative" as const,
      authenticity: "representative" as const,
      subject: "audio gadgets (remapped verified Unsplash id)",
      source: "Unsplash - Unsplash contributor, photo-1441986300917-64674bd600d8",
      license: "Unsplash License",
      licenseUrl: "https://unsplash.com/license",
      downloadDate: "2026-08-17",
      usedOn: ["/", "/products"] as const,
    },
    {
      id: "INTL-IPHONES_GADGETS-PRODUCT-04",
      src: "/media/international/categories/iphones-gadgets/gallery/intl-iphones-gadgets-product-04.webp",
      alt: "Representative imagery for iPhones & Gadgets (product)",
      kind: "representative" as const,
      authenticity: "representative" as const,
      subject: "device",
      source: "Unsplash - Kiran CK, photo-1523275335684-37898b6baf30",
      license: "Unsplash License",
      licenseUrl: "https://unsplash.com/license",
      downloadDate: "2026-08-17",
      usedOn: ["/", "/products"] as const,
    },
    {
      id: "INTL-IPHONES_GADGETS-CLOSEUP-01",
      src: "/media/international/categories/iphones-gadgets/gallery/intl-iphones-gadgets-closeup-01.webp",
      alt: "Representative imagery for iPhones & Gadgets (closeup)",
      kind: "representative" as const,
      authenticity: "representative" as const,
      subject: "camera closeup",
      source: "Unsplash - Vojtech Bruzek, photo-1516035069371-29a1b244cc32",
      license: "Unsplash License",
      licenseUrl: "https://unsplash.com/license",
      downloadDate: "2026-08-17",
      usedOn: ["/", "/products"] as const,
    },
    {
      id: "INTL-IPHONES_GADGETS-CLOSEUP-02",
      src: "/media/international/categories/iphones-gadgets/gallery/intl-iphones-gadgets-closeup-02.webp",
      alt: "Representative imagery for iPhones & Gadgets (closeup)",
      kind: "representative" as const,
      authenticity: "representative" as const,
      subject: "phone edge (remapped verified Unsplash id)",
      source: "Unsplash - Unsplash contributor, photo-1556740738-b6a63e27c4df",
      license: "Unsplash License",
      licenseUrl: "https://unsplash.com/license",
      downloadDate: "2026-08-17",
      usedOn: ["/", "/products"] as const,
    },
    {
      id: "INTL-IPHONES_GADGETS-CLOSEUP-03",
      src: "/media/international/categories/iphones-gadgets/gallery/intl-iphones-gadgets-closeup-03.webp",
      alt: "Representative imagery for iPhones & Gadgets (closeup)",
      kind: "representative" as const,
      authenticity: "representative" as const,
      subject: "phone back",
      source: "Unsplash - Do Nguyen, photo-1580910051074-3eb694886505",
      license: "Unsplash License",
      licenseUrl: "https://unsplash.com/license",
      downloadDate: "2026-08-17",
      usedOn: ["/", "/products"] as const,
    },
    {
      id: "INTL-IPHONES_GADGETS-ALT-01",
      src: "/media/international/categories/iphones-gadgets/gallery/intl-iphones-gadgets-alt-01.webp",
      alt: "Representative imagery for iPhones & Gadgets (alt)",
      kind: "representative" as const,
      authenticity: "representative" as const,
      subject: "desk tech",
      source: "Unsplash - Luca Bravo, photo-1498049794561-7780e7231661",
      license: "Unsplash License",
      licenseUrl: "https://unsplash.com/license",
      downloadDate: "2026-08-17",
      usedOn: ["/", "/products"] as const,
    },
    {
      id: "INTL-IPHONES_GADGETS-ALT-02",
      src: "/media/international/categories/iphones-gadgets/gallery/intl-iphones-gadgets-alt-02.webp",
      alt: "Representative imagery for iPhones & Gadgets (alt)",
      kind: "representative" as const,
      authenticity: "representative" as const,
      subject: "tech alt (remapped verified Unsplash id)",
      source: "Unsplash - Unsplash contributor, photo-1497366216548-37526070297c",
      license: "Unsplash License",
      licenseUrl: "https://unsplash.com/license",
      downloadDate: "2026-08-17",
      usedOn: ["/", "/products"] as const,
    },
    {
      id: "INTL-IPHONES_GADGETS-ALT-03",
      src: "/media/international/categories/iphones-gadgets/gallery/intl-iphones-gadgets-alt-03.webp",
      alt: "Representative imagery for iPhones & Gadgets (alt)",
      kind: "representative" as const,
      authenticity: "representative" as const,
      subject: "laptop",
      source: "Unsplash - Ales Nesetril, photo-1531297484001-80022131f5a1",
      license: "Unsplash License",
      licenseUrl: "https://unsplash.com/license",
      downloadDate: "2026-08-17",
      usedOn: ["/", "/products"] as const,
    },
    {
      id: "INTL-IPHONES_GADGETS-CONTEXT-01",
      src: "/media/international/categories/iphones-gadgets/context/intl-iphones-gadgets-context-01.webp",
      alt: "Representative imagery for iPhones & Gadgets (context)",
      kind: "representative" as const,
      authenticity: "representative" as const,
      subject: "retail context",
      source: "Unsplash - Nathan Dumlao, photo-1550009158-9ebf69173e03",
      license: "Unsplash License",
      licenseUrl: "https://unsplash.com/license",
      downloadDate: "2026-08-17",
      usedOn: ["/", "/products"] as const,
    },
    {
      id: "INTL-IPHONES_GADGETS-CONTEXT-02",
      src: "/media/international/categories/iphones-gadgets/context/intl-iphones-gadgets-context-02.webp",
      alt: "Representative imagery for iPhones & Gadgets (context)",
      kind: "representative" as const,
      authenticity: "representative" as const,
      subject: "workplace",
      source: "Unsplash - Marvin Meyer, photo-1519389950473-47ba0277781c",
      license: "Unsplash License",
      licenseUrl: "https://unsplash.com/license",
      downloadDate: "2026-08-17",
      usedOn: ["/", "/products"] as const,
    },
  ],
  "medical-equipments": [
    {
      id: "INTL-MEDICAL_EQUIPMENTS-HERO-01",
      src: "/media/international/categories/medical-equipments/hero/intl-medical-equipments-hero-01.webp",
      alt: "Representative imagery for Medical Equipments (hero)",
      kind: "representative" as const,
      authenticity: "representative" as const,
      subject: "clinic",
      source: "Unsplash - National Cancer Institute, photo-1576091160399-112ba8d25d1d",
      license: "Unsplash License",
      licenseUrl: "https://unsplash.com/license",
      downloadDate: "2026-08-17",
      usedOn: ["/", "/products"] as const,
    },
    {
      id: "INTL-MEDICAL_EQUIPMENTS-HERO-02",
      src: "/media/international/categories/medical-equipments/hero/intl-medical-equipments-hero-02.webp",
      alt: "Representative imagery for Medical Equipments (hero)",
      kind: "representative" as const,
      authenticity: "representative" as const,
      subject: "medical (remapped verified Unsplash id)",
      source: "Unsplash - Unsplash contributor, photo-1497366754035-f200968a6e72",
      license: "Unsplash License",
      licenseUrl: "https://unsplash.com/license",
      downloadDate: "2026-08-17",
      usedOn: ["/", "/products"] as const,
    },
    {
      id: "INTL-MEDICAL_EQUIPMENTS-HERO-03",
      src: "/media/international/categories/medical-equipments/hero/intl-medical-equipments-hero-03.webp",
      alt: "Representative imagery for Medical Equipments (hero)",
      kind: "representative" as const,
      authenticity: "representative" as const,
      subject: "devices",
      source: "Unsplash - Online Marketing, photo-1631815588090-d4bfec5b1ccb",
      license: "Unsplash License",
      licenseUrl: "https://unsplash.com/license",
      downloadDate: "2026-08-17",
      usedOn: ["/", "/products"] as const,
    },
    {
      id: "INTL-MEDICAL_EQUIPMENTS-PRODUCT-01",
      src: "/media/international/categories/medical-equipments/gallery/intl-medical-equipments-product-01.webp",
      alt: "Representative imagery for Medical Equipments (product)",
      kind: "representative" as const,
      authenticity: "representative" as const,
      subject: "equipment",
      source: "Unsplash - Owen Beard, photo-1584982751601-97dcc096659c",
      license: "Unsplash License",
      licenseUrl: "https://unsplash.com/license",
      downloadDate: "2026-08-17",
      usedOn: ["/", "/products"] as const,
    },
    {
      id: "INTL-MEDICAL_EQUIPMENTS-PRODUCT-02",
      src: "/media/international/categories/medical-equipments/gallery/intl-medical-equipments-product-02.webp",
      alt: "Representative imagery for Medical Equipments (product)",
      kind: "representative" as const,
      authenticity: "representative" as const,
      subject: "lab",
      source: "Unsplash - CDC, photo-1579684385127-1ef15d508118",
      license: "Unsplash License",
      licenseUrl: "https://unsplash.com/license",
      downloadDate: "2026-08-17",
      usedOn: ["/", "/products"] as const,
    },
    {
      id: "INTL-MEDICAL_EQUIPMENTS-PRODUCT-03",
      src: "/media/international/categories/medical-equipments/gallery/intl-medical-equipments-product-03.webp",
      alt: "Representative imagery for Medical Equipments (product)",
      kind: "representative" as const,
      authenticity: "representative" as const,
      subject: "monitor",
      source: "Unsplash - National Cancer Institute, photo-1666214280557-f1b5022eb634",
      license: "Unsplash License",
      licenseUrl: "https://unsplash.com/license",
      downloadDate: "2026-08-17",
      usedOn: ["/", "/products"] as const,
    },
    {
      id: "INTL-MEDICAL_EQUIPMENTS-PRODUCT-04",
      src: "/media/international/categories/medical-equipments/gallery/intl-medical-equipments-product-04.webp",
      alt: "Representative imagery for Medical Equipments (product)",
      kind: "representative" as const,
      authenticity: "representative" as const,
      subject: "supplies",
      source: "Unsplash - Owen Beard, photo-1579154204601-01588f351e67",
      license: "Unsplash License",
      licenseUrl: "https://unsplash.com/license",
      downloadDate: "2026-08-17",
      usedOn: ["/", "/products"] as const,
    },
    {
      id: "INTL-MEDICAL_EQUIPMENTS-CLOSEUP-01",
      src: "/media/international/categories/medical-equipments/gallery/intl-medical-equipments-closeup-01.webp",
      alt: "Representative imagery for Medical Equipments (closeup)",
      kind: "representative" as const,
      authenticity: "representative" as const,
      subject: "detail",
      source: "Unsplash - Christina Victoria Craft, photo-1584308666744-24d5c474f2ae",
      license: "Unsplash License",
      licenseUrl: "https://unsplash.com/license",
      downloadDate: "2026-08-17",
      usedOn: ["/", "/products"] as const,
    },
    {
      id: "INTL-MEDICAL_EQUIPMENTS-CLOSEUP-02",
      src: "/media/international/categories/medical-equipments/gallery/intl-medical-equipments-closeup-02.webp",
      alt: "Representative imagery for Medical Equipments (closeup)",
      kind: "representative" as const,
      authenticity: "representative" as const,
      subject: "instruments (remapped verified Unsplash id)",
      source: "Unsplash - Unsplash contributor, photo-1556761175-5973dc0f32e7",
      license: "Unsplash License",
      licenseUrl: "https://unsplash.com/license",
      downloadDate: "2026-08-17",
      usedOn: ["/", "/products"] as const,
    },
    {
      id: "INTL-MEDICAL_EQUIPMENTS-CLOSEUP-03",
      src: "/media/international/categories/medical-equipments/gallery/intl-medical-equipments-closeup-03.webp",
      alt: "Representative imagery for Medical Equipments (closeup)",
      kind: "representative" as const,
      authenticity: "representative" as const,
      subject: "tools (remapped verified Unsplash id)",
      source: "Unsplash - Unsplash contributor, photo-1600880292203-757bb62b4baf",
      license: "Unsplash License",
      licenseUrl: "https://unsplash.com/license",
      downloadDate: "2026-08-17",
      usedOn: ["/", "/products"] as const,
    },
    {
      id: "INTL-MEDICAL_EQUIPMENTS-ALT-01",
      src: "/media/international/categories/medical-equipments/gallery/intl-medical-equipments-alt-01.webp",
      alt: "Representative imagery for Medical Equipments (alt)",
      kind: "representative" as const,
      authenticity: "representative" as const,
      subject: "care",
      source: "Unsplash - National Cancer Institute, photo-1530026405186-ed1f139313f8",
      license: "Unsplash License",
      licenseUrl: "https://unsplash.com/license",
      downloadDate: "2026-08-17",
      usedOn: ["/", "/products"] as const,
    },
    {
      id: "INTL-MEDICAL_EQUIPMENTS-ALT-02",
      src: "/media/international/categories/medical-equipments/gallery/intl-medical-equipments-alt-02.webp",
      alt: "Representative imagery for Medical Equipments (alt)",
      kind: "representative" as const,
      authenticity: "representative" as const,
      subject: "tools-alt-shared (remapped verified Unsplash id)",
      source: "Unsplash - Unsplash contributor, photo-1573164713714-d95e436ab8d6",
      license: "Unsplash License",
      licenseUrl: "https://unsplash.com/license",
      downloadDate: "2026-08-17",
      usedOn: ["/", "/products"] as const,
    },
    {
      id: "INTL-MEDICAL_EQUIPMENTS-ALT-03",
      src: "/media/international/categories/medical-equipments/gallery/intl-medical-equipments-alt-03.webp",
      alt: "Representative imagery for Medical Equipments (alt)",
      kind: "representative" as const,
      authenticity: "representative" as const,
      subject: "stethoscope",
      source: "Unsplash - National Cancer Institute, photo-1585435557343-3b092031a831",
      license: "Unsplash License",
      licenseUrl: "https://unsplash.com/license",
      downloadDate: "2026-08-17",
      usedOn: ["/", "/products"] as const,
    },
    {
      id: "INTL-MEDICAL_EQUIPMENTS-CONTEXT-01",
      src: "/media/international/categories/medical-equipments/context/intl-medical-equipments-context-01.webp",
      alt: "Representative imagery for Medical Equipments (context)",
      kind: "representative" as const,
      authenticity: "representative" as const,
      subject: "hospital",
      source: "Unsplash - Hush Naidoo, photo-1519494026892-80bbd2d6fd0d",
      license: "Unsplash License",
      licenseUrl: "https://unsplash.com/license",
      downloadDate: "2026-08-17",
      usedOn: ["/", "/products"] as const,
    },
    {
      id: "INTL-MEDICAL_EQUIPMENTS-CONTEXT-02",
      src: "/media/international/categories/medical-equipments/context/intl-medical-equipments-context-02.webp",
      alt: "Representative imagery for Medical Equipments (context)",
      kind: "representative" as const,
      authenticity: "representative" as const,
      subject: "healthcare",
      source: "Unsplash - Martha Dom, photo-1586773860418-d37222d8fce3",
      license: "Unsplash License",
      licenseUrl: "https://unsplash.com/license",
      downloadDate: "2026-08-17",
      usedOn: ["/", "/products"] as const,
    },
  ],
  "home-garden-wares": [
    {
      id: "INTL-HOME_GARDEN_WARES-HERO-01",
      src: "/media/international/categories/home-garden-wares/hero/intl-home-garden-wares-hero-01.webp",
      alt: "Representative imagery for Home & Garden Wares (hero)",
      kind: "representative" as const,
      authenticity: "representative" as const,
      subject: "plants (remapped verified Unsplash id)",
      source: "Unsplash - Unsplash contributor, photo-1581092795360-fd1ca04f0952",
      license: "Unsplash License",
      licenseUrl: "https://unsplash.com/license",
      downloadDate: "2026-08-17",
      usedOn: ["/", "/products"] as const,
    },
    {
      id: "INTL-HOME_GARDEN_WARES-HERO-02",
      src: "/media/international/categories/home-garden-wares/hero/intl-home-garden-wares-hero-02.webp",
      alt: "Representative imagery for Home & Garden Wares (hero)",
      kind: "representative" as const,
      authenticity: "representative" as const,
      subject: "tomato (remapped verified Unsplash id)",
      source: "Unsplash - Unsplash contributor, photo-1486406146926-c627a92ad1ab",
      license: "Unsplash License",
      licenseUrl: "https://unsplash.com/license",
      downloadDate: "2026-08-17",
      usedOn: ["/", "/products"] as const,
    },
    {
      id: "INTL-HOME_GARDEN_WARES-HERO-03",
      src: "/media/international/categories/home-garden-wares/hero/intl-home-garden-wares-hero-03.webp",
      alt: "Representative imagery for Home & Garden Wares (hero)",
      kind: "representative" as const,
      authenticity: "representative" as const,
      subject: "garden",
      source: "Unsplash - Markus Spiske, photo-1416879595882-3373a0480b5b",
      license: "Unsplash License",
      licenseUrl: "https://unsplash.com/license",
      downloadDate: "2026-08-17",
      usedOn: ["/", "/products"] as const,
    },
    {
      id: "INTL-HOME_GARDEN_WARES-PRODUCT-01",
      src: "/media/international/categories/home-garden-wares/gallery/intl-home-garden-wares-product-01.webp",
      alt: "Representative imagery for Home & Garden Wares (product)",
      kind: "representative" as const,
      authenticity: "representative" as const,
      subject: "tools (remapped verified Unsplash id)",
      source: "Unsplash - Unsplash contributor, photo-1497366811353-6870744d04b2",
      license: "Unsplash License",
      licenseUrl: "https://unsplash.com/license",
      downloadDate: "2026-08-17",
      usedOn: ["/", "/products"] as const,
    },
    {
      id: "INTL-HOME_GARDEN_WARES-PRODUCT-02",
      src: "/media/international/categories/home-garden-wares/gallery/intl-home-garden-wares-product-02.webp",
      alt: "Representative imagery for Home & Garden Wares (product)",
      kind: "representative" as const,
      authenticity: "representative" as const,
      subject: "pots (remapped verified Unsplash id)",
      source: "Unsplash - Unsplash contributor, photo-1556910103-1c02745aae4d",
      license: "Unsplash License",
      licenseUrl: "https://unsplash.com/license",
      downloadDate: "2026-08-17",
      usedOn: ["/", "/products"] as const,
    },
    {
      id: "INTL-HOME_GARDEN_WARES-PRODUCT-03",
      src: "/media/international/categories/home-garden-wares/gallery/intl-home-garden-wares-product-03.webp",
      alt: "Representative imagery for Home & Garden Wares (product)",
      kind: "representative" as const,
      authenticity: "representative" as const,
      subject: "indoor",
      source: "Unsplash - Scott Webb, photo-1501004318641-b39e6451bec6",
      license: "Unsplash License",
      licenseUrl: "https://unsplash.com/license",
      downloadDate: "2026-08-17",
      usedOn: ["/", "/products"] as const,
    },
    {
      id: "INTL-HOME_GARDEN_WARES-PRODUCT-04",
      src: "/media/international/categories/home-garden-wares/gallery/intl-home-garden-wares-product-04.webp",
      alt: "Representative imagery for Home & Garden Wares (product)",
      kind: "representative" as const,
      authenticity: "representative" as const,
      subject: "homewares",
      source: "Unsplash - Annie Spratt, photo-1487700160041-babef9c3cb55",
      license: "Unsplash License",
      licenseUrl: "https://unsplash.com/license",
      downloadDate: "2026-08-17",
      usedOn: ["/", "/products"] as const,
    },
    {
      id: "INTL-HOME_GARDEN_WARES-CLOSEUP-01",
      src: "/media/international/categories/home-garden-wares/gallery/intl-home-garden-wares-closeup-01.webp",
      alt: "Representative imagery for Home & Garden Wares (closeup)",
      kind: "representative" as const,
      authenticity: "representative" as const,
      subject: "home detail (remapped verified Unsplash id)",
      source: "Unsplash - Unsplash contributor, photo-1567620905732-2d1ec7ab7445",
      license: "Unsplash License",
      licenseUrl: "https://unsplash.com/license",
      downloadDate: "2026-08-17",
      usedOn: ["/", "/products"] as const,
    },
    {
      id: "INTL-HOME_GARDEN_WARES-CLOSEUP-02",
      src: "/media/international/categories/home-garden-wares/gallery/intl-home-garden-wares-closeup-02.webp",
      alt: "Representative imagery for Home & Garden Wares (closeup)",
      kind: "representative" as const,
      authenticity: "representative" as const,
      subject: "greenery (remapped verified Unsplash id)",
      source: "Unsplash - Unsplash contributor, photo-1512621776951-a57141f2eefd",
      license: "Unsplash License",
      licenseUrl: "https://unsplash.com/license",
      downloadDate: "2026-08-17",
      usedOn: ["/", "/products"] as const,
    },
    {
      id: "INTL-HOME_GARDEN_WARES-CLOSEUP-03",
      src: "/media/international/categories/home-garden-wares/gallery/intl-home-garden-wares-closeup-03.webp",
      alt: "Representative imagery for Home & Garden Wares (closeup)",
      kind: "representative" as const,
      authenticity: "representative" as const,
      subject: "leaf (remapped verified Unsplash id)",
      source: "Unsplash - Unsplash contributor, photo-1540420773420-3366772f4999",
      license: "Unsplash License",
      licenseUrl: "https://unsplash.com/license",
      downloadDate: "2026-08-17",
      usedOn: ["/", "/products"] as const,
    },
  ],
  "machineries": [
    {
      id: "INTL-MACHINERIES-HERO-01",
      src: "/media/international/categories/machineries/hero/intl-machineries-hero-01.webp",
      alt: "Representative imagery for Machineries (hero)",
      kind: "representative" as const,
      authenticity: "representative" as const,
      subject: "machinery",
      source: "Unsplash - American Public Power Association, photo-1565043666747-69f6646db940",
      license: "Unsplash License",
      licenseUrl: "https://unsplash.com/license",
      downloadDate: "2026-08-17",
      usedOn: ["/", "/products"] as const,
    },
    {
      id: "INTL-MACHINERIES-HERO-03",
      src: "/media/international/categories/machineries/hero/intl-machineries-hero-03.webp",
      alt: "Representative imagery for Machineries (hero)",
      kind: "representative" as const,
      authenticity: "representative" as const,
      subject: "engineering",
      source: "Unsplash - ThisisEngineering, photo-1581091226825-a6a2a5aee158",
      license: "Unsplash License",
      licenseUrl: "https://unsplash.com/license",
      downloadDate: "2026-08-17",
      usedOn: ["/", "/products"] as const,
    },
    {
      id: "INTL-MACHINERIES-PRODUCT-01",
      src: "/media/international/categories/machineries/gallery/intl-machineries-product-01.webp",
      alt: "Representative imagery for Machineries (product)",
      kind: "representative" as const,
      authenticity: "representative" as const,
      subject: "equipment",
      source: "Unsplash - ThisisEngineering, photo-1581092160562-40aa08e78837",
      license: "Unsplash License",
      licenseUrl: "https://unsplash.com/license",
      downloadDate: "2026-08-17",
      usedOn: ["/", "/products"] as const,
    },
    {
      id: "INTL-MACHINERIES-PRODUCT-02",
      src: "/media/international/categories/machineries/gallery/intl-machineries-product-02.webp",
      alt: "Representative imagery for Machineries (product)",
      kind: "representative" as const,
      authenticity: "representative" as const,
      subject: "factory",
      source: "Unsplash - ThisisEngineering, photo-1581092918056-0c4c3acd3789",
      license: "Unsplash License",
      licenseUrl: "https://unsplash.com/license",
      downloadDate: "2026-08-17",
      usedOn: ["/", "/products"] as const,
    },
  ],
  "general-procurement": [
    {
      id: "INTL-GENERAL_PROCUREMENT-HERO-01",
      src: "/media/international/categories/general-procurement/hero/intl-general-procurement-hero-01.webp",
      alt: "Representative imagery for General Procurement (hero)",
      kind: "representative" as const,
      authenticity: "representative" as const,
      subject: "warehouse",
      source: "Unsplash - CHUTTERSNAP, photo-1586528116311-ad8dd3c8310d",
      license: "Unsplash License",
      licenseUrl: "https://unsplash.com/license",
      downloadDate: "2026-08-17",
      usedOn: ["/", "/products"] as const,
    },
    {
      id: "INTL-GENERAL_PROCUREMENT-HERO-02",
      src: "/media/international/categories/general-procurement/hero/intl-general-procurement-hero-02.webp",
      alt: "Representative imagery for General Procurement (hero)",
      kind: "representative" as const,
      authenticity: "representative" as const,
      subject: "boxes",
      source: "Unsplash - CHUTTERSNAP, photo-1553413077-190dd305871c",
      license: "Unsplash License",
      licenseUrl: "https://unsplash.com/license",
      downloadDate: "2026-08-17",
      usedOn: ["/", "/products"] as const,
    },
    {
      id: "INTL-GENERAL_PROCUREMENT-HERO-03",
      src: "/media/international/categories/general-procurement/hero/intl-general-procurement-hero-03.webp",
      alt: "Representative imagery for General Procurement (hero)",
      kind: "representative" as const,
      authenticity: "representative" as const,
      subject: "pallets",
      source: "Unsplash - CHUTTERSNAP, photo-1566576912321-d58ddd7a6088",
      license: "Unsplash License",
      licenseUrl: "https://unsplash.com/license",
      downloadDate: "2026-08-17",
      usedOn: ["/", "/products"] as const,
    },
    {
      id: "INTL-GENERAL_PROCUREMENT-CLOSEUP-01",
      src: "/media/international/categories/general-procurement/gallery/intl-general-procurement-closeup-01.webp",
      alt: "Representative imagery for General Procurement (closeup)",
      kind: "representative" as const,
      authenticity: "representative" as const,
      subject: "carton",
      source: "Unsplash - CHUTTERSNAP, photo-1566576721346-d4a3b4eaeb55",
      license: "Unsplash License",
      licenseUrl: "https://unsplash.com/license",
      downloadDate: "2026-08-17",
      usedOn: ["/", "/products"] as const,
    },
  ],
} as const satisfies Record<string, readonly MediaAsset[]>;

export function listInternationalStagedMedia(
  slug: string,
): readonly MediaAsset[] {
  return (
    INTERNATIONAL_CATEGORY_STAGED_MEDIA[
      slug as keyof typeof INTERNATIONAL_CATEGORY_STAGED_MEDIA
    ] ?? []
  );
}
