export const API_V1_PATH = "/api/v1";
export const DEFAULT_PAGE_SIZE = 25;
export const MAX_PAGE_SIZE = 100;
export const HAMD_API_SERVICE_NAME = "hamd-api";

export {
  DEFAULT_WEDDING_CAMPAIGN,
  ROWDOTUL_HAMD_IDENTITY,
  WEDDING_CAMPAIGN_ID,
  WEDDING_CAMPAIGN_SLUG,
  WEDDING_COMMENT_MAX_CHARS,
  WEDDING_GALLERY_ACCEPT,
  WEDDING_GALLERY_MAX_BYTES,
  WEDDING_LIVEKIT_ROOM,
  WEDDING_LIVEKIT_TEST_ROOM,
  WEDDING_MODAL_PUBLIC_DELAY_MS,
  DEFAULT_WEDDING_REMINDER_PREFERENCE,
  deriveWeddingModalEndsAt,
  formatWeddingDate,
  formatWeddingFileSize,
  formatWeddingWhen,
  isUsableTermiiSenderId,
  isWeddingModalEligible,
  isWeddingProductionLive,
  isWeddingTestLive,
  normalizeWeddingSmsPhone,
  shouldRequestWeddingLiveToken,
  validateWeddingGalleryFile,
  weddingCommentChannel,
  weddingGalleryKindFromMime,
  weddingLiveKitRoom,
  weddingModalActions,
  weddingModalDismissKey,
  sanitizeWeddingFeedLabel,
  weddingHostIdentity,
  weddingCaptureAttempts,
  formatWeddingCaptureLabel,
  validateWeddingWaitingAudioFile,
  weddingWaitingAudioKind,
  enabledWeddingWaitingTracks,
  shouldPlayWeddingWaitingMusic,
  nextWeddingWaitingTrackIndex,
  recoverWeddingWaitingTrackIndex,
  formatWeddingAudioDuration,
  WEDDING_FEED_LABELS,
  WEDDING_WAITING_AUDIO_ACCEPT,
  WEDDING_WAITING_AUDIO_MAX_BYTES,
  WEDDING_WAITING_AUDIO_MAX_MB,
  WEDDING_WAITING_AUDIO_SESSION_MUTE_KEY,
  WEDDING_WAITING_AUDIO_SESSION_VOLUME_KEY,
  WEDDING_WAITING_DEFAULT_VOLUME,
  type WeddingBroadcastFeed,
  type WeddingCampaignRecord,
  type WeddingCaptureChoice,
  type WeddingFeedLabel,
  type WeddingLiveMode,
  type WeddingModalCta,
  type WeddingNotificationKind,
  type WeddingReminderPreference,
  type WeddingStreamStatus,
  type WeddingWaitingTrack,
} from "./wedding-campaign.js";
