import type { ShipmentRecord } from "./types.js";

const hours = (h: number) =>
  new Date(Date.now() - h * 3_600_000).toISOString();
const days = (d: number) =>
  new Date(Date.now() - d * 86_400_000).toISOString();
const futureDays = (d: number) =>
  new Date(Date.now() + d * 86_400_000).toISOString();

export const shipmentRecordsFixture: ShipmentRecord[] = [
  {
    id: "sh-901",
    publicCode: "SH-901",
    status: "planned",
    rowVersion: 2,
    purchaseOrderId: "po-551",
    purchaseOrderCode: "PO-551",
    carrierName: "Maersk",
    trackingNumber: null,
    transportMode: "ocean",
    estimatedArrivalAt: futureDays(18),
    actualDeliveryAt: null,
    originLabel: "Ningbo, CN",
    destinationLabel: "Lagos Apapa, NG",
    createdAt: hours(40),
    updatedAt: hours(17),
    milestones: [
      {
        id: "m1",
        type: "po_confirmed",
        label: "PO confirmed",
        confidence: "confirmed",
        occurredAt: hours(17),
        location: "Ningbo",
      },
      {
        id: "m2",
        type: "supplier_ready",
        label: "Supplier ready",
        confidence: "estimated",
        estimatedAt: futureDays(5),
        location: "Ningbo",
      },
      {
        id: "m3",
        type: "departed",
        label: "Departed origin",
        confidence: "estimated",
        estimatedAt: futureDays(8),
      },
    ],
    timeline: [
      {
        id: "t1",
        label: "Shipment planned",
        detail: "Linked to PO-551",
        at: hours(40),
        kind: "status",
      },
      {
        id: "t2",
        label: "PO confirmed",
        detail: "Milestone recorded",
        at: hours(17),
        kind: "milestone",
      },
    ],
    documents: [
      {
        id: "sd1",
        documentId: "11111111-1111-1111-1111-111111111111",
        name: "booking-confirmation.pdf",
        href: "#",
        role: "booking",
        uploadedAt: hours(16),
      },
    ],
    history: [
      {
        id: "sh1",
        toStatus: "planned",
        command: "create",
        actorName: "System",
        createdAt: hours(40),
      },
    ],
    proofOfDelivery: {
      confirmed: false,
    },
    map: {
      label: "Origin · Ningbo Port",
      latitude: 29.8683,
      longitude: 121.544,
      region: "East China Sea corridor",
    },
  },
  {
    id: "sh-770",
    publicCode: "SH-770",
    status: "out_for_delivery",
    rowVersion: 8,
    purchaseOrderId: "po-300",
    purchaseOrderCode: "PO-300",
    carrierName: "GIG Logistics",
    trackingNumber: "GIG-77821",
    transportMode: "road",
    estimatedArrivalAt: futureDays(1),
    actualDeliveryAt: null,
    originLabel: "Ikeja Hub",
    destinationLabel: "Victoria Island warehouse",
    createdAt: days(14),
    updatedAt: hours(10),
    milestones: [
      {
        id: "m4",
        type: "picked_up",
        label: "Picked up",
        confidence: "confirmed",
        occurredAt: days(7),
        location: "Ikeja Hub",
      },
      {
        id: "m5",
        type: "out_for_delivery",
        label: "Out for delivery",
        confidence: "confirmed",
        occurredAt: hours(10),
        location: "Lagos",
      },
      {
        id: "m6",
        type: "delivered",
        label: "Delivered",
        confidence: "estimated",
        estimatedAt: futureDays(1),
        location: "Victoria Island",
      },
    ],
    timeline: [
      {
        id: "t3",
        label: "Picked up",
        at: days(7),
        kind: "milestone",
      },
      {
        id: "t4",
        label: "Out for delivery",
        detail: "GIG-77821",
        at: hours(10),
        kind: "status",
      },
    ],
    documents: [
      {
        id: "sd2",
        documentId: "22222222-2222-2222-2222-222222222222",
        name: "waybill-GIG-77821.pdf",
        href: "#",
        role: "waybill",
        uploadedAt: days(7),
      },
      {
        id: "sd3",
        documentId: "33333333-3333-3333-3333-333333333333",
        name: "packing-list.pdf",
        href: "#",
        role: "packing_list",
        uploadedAt: days(8),
      },
    ],
    history: [
      {
        id: "sh2",
        fromStatus: "dispatched",
        toStatus: "out_for_delivery",
        command: "out_for_delivery",
        actorName: "GIG API",
        createdAt: hours(10),
      },
      {
        id: "sh3",
        fromStatus: "warehouse_received",
        toStatus: "dispatched",
        command: "dispatch",
        actorName: "James Nwosu",
        createdAt: days(2),
      },
    ],
    proofOfDelivery: {
      confirmed: false,
      notes: "Signature capture pending on delivery",
    },
    map: {
      label: "En route · Lagos metro",
      latitude: 6.4541,
      longitude: 3.3947,
      region: "Last-mile corridor",
    },
  },
  {
    id: "sh-612",
    publicCode: "SH-612",
    status: "delivered",
    rowVersion: 11,
    purchaseOrderId: "po-280",
    purchaseOrderCode: "PO-280",
    carrierName: "DHL Freight",
    trackingNumber: "DHL-441902",
    transportMode: "air",
    estimatedArrivalAt: days(3),
    actualDeliveryAt: days(2),
    originLabel: "Frankfurt FRA",
    destinationLabel: "Abuja warehouse",
    createdAt: days(20),
    updatedAt: days(2),
    milestones: [
      {
        id: "m7",
        type: "departed",
        label: "Departed origin",
        confidence: "confirmed",
        occurredAt: days(5),
        location: "Frankfurt",
      },
      {
        id: "m8",
        type: "arrived",
        label: "Arrived destination",
        confidence: "confirmed",
        occurredAt: days(3),
        location: "Abuja",
      },
      {
        id: "m9",
        type: "delivered",
        label: "Delivered",
        confidence: "confirmed",
        occurredAt: days(2),
        location: "Abuja warehouse",
      },
    ],
    timeline: [
      {
        id: "t5",
        label: "Departed Frankfurt",
        at: days(5),
        kind: "milestone",
      },
      {
        id: "t6",
        label: "Delivered",
        detail: "Recipient: Facilities desk",
        at: days(2),
        kind: "evidence",
      },
    ],
    documents: [
      {
        id: "sd4",
        documentId: "44444444-4444-4444-4444-444444444444",
        name: "air-waybill.pdf",
        href: "#",
        role: "awb",
        uploadedAt: days(5),
      },
      {
        id: "sd5",
        documentId: "55555555-5555-5555-5555-555555555555",
        name: "pod-photo.jpg",
        href: "#",
        role: "pod",
        uploadedAt: days(2),
      },
    ],
    history: [
      {
        id: "sh4",
        fromStatus: "out_for_delivery",
        toStatus: "delivered",
        command: "deliver",
        actorName: "DHL Freight",
        createdAt: days(2),
      },
    ],
    proofOfDelivery: {
      confirmed: true,
      recipientName: "Facilities desk",
      confirmedAt: days(2),
      confirmedByName: "Ada Okonkwo",
      evidenceHref: "#",
      evidenceLabel: "pod-photo.jpg",
      notes: "Received intact",
    },
    map: {
      label: "Delivered · Abuja warehouse",
      latitude: 9.0765,
      longitude: 7.3986,
      region: "Destination yard",
    },
  },
  {
    id: "sh-440",
    publicCode: "SH-440",
    status: "held",
    rowVersion: 4,
    purchaseOrderId: "po-199",
    purchaseOrderCode: "PO-199",
    carrierName: "MSC",
    trackingNumber: "MSCU-99812",
    transportMode: "ocean",
    estimatedArrivalAt: futureDays(30),
    originLabel: "Mersin, TR",
    destinationLabel: "Tema, GH",
    createdAt: days(12),
    updatedAt: days(1),
    milestones: [
      {
        id: "m10",
        type: "exception_opened",
        label: "Exception opened",
        confidence: "confirmed",
        occurredAt: days(1),
        location: "Mersin",
      },
    ],
    timeline: [
      {
        id: "t7",
        label: "Held",
        detail: "Customs document mismatch",
        at: days(1),
        kind: "status",
      },
    ],
    documents: [],
    history: [
      {
        id: "sh5",
        fromStatus: "export_cleared",
        toStatus: "held",
        command: "hold",
        reason: "Customs document mismatch",
        actorName: "Leo Mensah",
        createdAt: days(1),
      },
    ],
    proofOfDelivery: {
      confirmed: false,
    },
    map: {
      label: "Held · Mersin terminal",
      latitude: 36.8121,
      longitude: 34.6415,
      region: "Export hold yard",
    },
  },
];
