import type { ChatMessage, ChatParticipant, ChatRoom } from "./types.js";

const hours = (h: number) =>
  new Date(Date.now() - h * 3_600_000).toISOString();

export const chatParticipantsFixture: ChatParticipant[] = [
  {
    id: "user-ada",
    displayName: "Ada Okonkwo",
    role: "Buyer",
    presence: "online",
  },
  {
    id: "ops-james",
    displayName: "James Nwosu",
    role: "Procurement",
    presence: "online",
  },
  {
    id: "support-maya",
    displayName: "Maya Support",
    role: "Support",
    presence: "away",
  },
];

export const chatRoomsFixture: ChatRoom[] = [
  {
    id: "room-pr-1042",
    type: "request",
    title: "PR-1042 · Industrial valves",
    subtitle: "Clarification with Ops",
    recordLabel: "PR-1042",
    recordHref: "/requests/pr-1042",
    status: "sourcing",
    unreadCount: 2,
    updatedAt: hours(0.5),
    preview: "Please confirm Lagos warehouse address.",
    participants: [
      chatParticipantsFixture[0]!,
      chatParticipantsFixture[1]!,
    ],
    pinnedMessageIds: ["m3"],
  },
  {
    id: "room-support",
    type: "support",
    title: "Support",
    subtitle: "Almahbub desk",
    status: "open",
    unreadCount: 0,
    updatedAt: hours(3),
    preview: "Happy to help with the invoice upload.",
    participants: [
      chatParticipantsFixture[0]!,
      chatParticipantsFixture[2]!,
    ],
  },
  {
    id: "room-ship-901",
    type: "shipment",
    title: "SH-901 · Maersk lane",
    recordLabel: "SH-901",
    recordHref: "/shipments/sh-901",
    status: "in_transit",
    unreadCount: 1,
    updatedAt: hours(8),
    preview: "ETA updated to 12 Aug.",
    participants: [chatParticipantsFixture[0]!, chatParticipantsFixture[1]!],
  },
];

export const chatMessagesFixture: ChatMessage[] = [
  {
    id: "m1",
    roomId: "room-pr-1042",
    senderId: "ops-james",
    kind: "text",
    body: "We need the final destination warehouse for PR-1042 before we continue sourcing.",
    createdAt: hours(6),
    delivery: "read",
  },
  {
    id: "m2",
    roomId: "room-pr-1042",
    senderId: "user-ada",
    kind: "text",
    body: "Lagos Free Zone, Building C. Gate code on the packing list.",
    createdAt: hours(5),
    delivery: "read",
  },
  {
    id: "m3",
    roomId: "room-pr-1042",
    senderId: "ops-james",
    kind: "text",
    body: "Pinned: destination confirmed - Lagos Free Zone, Building C.",
    createdAt: hours(4),
    delivery: "read",
    pinned: true,
    pinnedAt: hours(3.5),
    pinnedById: "ops-james",
  },
  {
    id: "m4",
    roomId: "room-pr-1042",
    senderId: "ops-james",
    kind: "image",
    body: "Valve datasheet preview",
    createdAt: hours(2),
    delivery: "delivered",
    attachments: [
      {
        id: "a1",
        name: "valve-preview.jpg",
        mimeType: "image/jpeg",
        sizeBytes: 240_000,
        url: "https://placehold.co/640x400/png?text=Valve+Preview",
        kind: "image",
      },
    ],
  },
  {
    id: "m5",
    roomId: "room-pr-1042",
    senderId: "user-ada",
    kind: "file",
    body: "",
    createdAt: hours(1.5),
    delivery: "delivered",
    attachments: [
      {
        id: "a2",
        name: "packing-list.pdf",
        mimeType: "application/pdf",
        sizeBytes: 180_000,
        url: "#",
        kind: "file",
      },
    ],
  },
  {
    id: "m6",
    roomId: "room-pr-1042",
    senderId: "ops-james",
    kind: "audio",
    body: "Voice note (placeholder)",
    createdAt: hours(1.2),
    delivery: "delivered",
    attachments: [
      {
        id: "a3",
        name: "note.m4a",
        mimeType: "audio/mp4",
        sizeBytes: 90_000,
        kind: "audio",
      },
    ],
  },
  {
    id: "m7",
    roomId: "room-pr-1042",
    senderId: "ops-james",
    kind: "video",
    body: "Walkthrough clip (placeholder)",
    createdAt: hours(1),
    delivery: "delivered",
    attachments: [
      {
        id: "a4",
        name: "walkthrough.mp4",
        mimeType: "video/mp4",
        sizeBytes: 2_400_000,
        kind: "video",
      },
    ],
  },
  {
    id: "m8",
    roomId: "room-pr-1042",
    senderId: "ops-james",
    kind: "text",
    body: "Please confirm Lagos warehouse address.",
    createdAt: hours(0.5),
    delivery: "delivered",
  },
  {
    id: "s1",
    roomId: "room-support",
    senderId: "support-maya",
    kind: "text",
    body: "Happy to help with the invoice upload.",
    createdAt: hours(3),
    delivery: "read",
  },
  {
    id: "sh1",
    roomId: "room-ship-901",
    senderId: "ops-james",
    kind: "text",
    body: "ETA updated to 12 Aug.",
    createdAt: hours(8),
    delivery: "delivered",
  },
];
