import type { SupplierRecord } from "./types.js";

const days = (d: number) =>
  new Date(Date.now() - d * 86_400_000).toISOString();

export const supplierRecordsFixture: SupplierRecord[] = [
  {
    id: "sup-valve-co",
    legalName: "Ningbo Precision Valves Co., Ltd",
    tradeName: "NPV Industrial",
    status: "active",
    countryCode: "CN",
    countriesServed: ["CN", "NG", "AE", "GH"],
    verification: "verified",
    riskTier: "low",
    riskScore: 22,
    website: "https://example.com/npv",
    createdAt: days(400),
    updatedAt: days(2),
    categories: ["Industrial valves", "Piping"],
    contacts: [
      {
        id: "c1",
        name: "Li Wei",
        email: "li.wei@npv.example",
        phone: "+86 574 0000",
        role: "Export manager",
        isPrimary: true,
      },
      {
        id: "c2",
        name: "Anna Park",
        email: "anna@npv.example",
        role: "QA",
        isPrimary: false,
      },
    ],
    locations: [
      {
        id: "l1",
        label: "HQ / Plant",
        addressLine: "88 Harbor Rd",
        city: "Ningbo",
        countryCode: "CN",
        isHeadquarters: true,
      },
      {
        id: "l2",
        label: "Dubai office",
        addressLine: "Sheikh Zayed Rd",
        city: "Dubai",
        countryCode: "AE",
      },
    ],
    certifications: [
      {
        id: "cert1",
        type: "ISO 9001",
        issuer: "SGS",
        number: "CN-9001-441",
        issuedAt: days(600),
        expiresAt: days(-200),
        status: "valid",
        documentHref: "#",
      },
      {
        id: "cert2",
        type: "CE",
        issuer: "TÜV",
        number: "CE-77821",
        issuedAt: days(300),
        expiresAt: days(-30),
        status: "expiring",
        documentHref: "#",
      },
    ],
    documents: [
      {
        id: "d1",
        name: "Company profile.pdf",
        kind: "profile",
        uploadedAt: days(90),
        href: "#",
        sizeLabel: "2.1 MB",
      },
      {
        id: "d2",
        name: "Factory audit 2025.pdf",
        kind: "audit",
        uploadedAt: days(40),
        href: "#",
        sizeLabel: "4.8 MB",
      },
    ],
    ratings: {
      overall: 4.6,
      quality: 4.7,
      delivery: 4.4,
      communication: 4.5,
      reviewCount: 18,
    },
    leadTime: {
      minDays: 18,
      maxDays: 35,
      typicalDays: 24,
      notes: "Ex-works Ningbo; ocean add 18–28 days to Lagos.",
    },
    performance: [
      { key: "otif", label: "OTIF", value: "94%", trend: "up", period: "90d" },
      {
        key: "defect",
        label: "Defect rate",
        value: "0.8%",
        trend: "down",
        period: "90d",
      },
      {
        key: "response",
        label: "Quote response",
        value: "1.2d",
        trend: "flat",
        period: "90d",
      },
      {
        key: "disputes",
        label: "Open disputes",
        value: "0",
        trend: "flat",
        period: "90d",
      },
    ],
    products: [
      {
        id: "p1",
        name: "Gate valve DN50",
        sku: "GV-50",
        category: "Valves",
        moq: "50 pcs",
        href: "/catalog/gv-50",
      },
      {
        id: "p2",
        name: "Ball valve DN80",
        sku: "BV-80",
        category: "Valves",
        moq: "20 pcs",
      },
    ],
    communications: [
      {
        id: "msg1",
        subject: "PR-1042 clarification",
        preview: "Datasheet revision attached.",
        updatedAt: days(1),
        href: "/messages/room-pr-1042",
        unread: true,
      },
    ],
  },
  {
    id: "sup-textile",
    legalName: "Accra Weave Exports Ltd",
    tradeName: "Accra Weave",
    status: "draft",
    countryCode: "GH",
    countriesServed: ["GH", "NG"],
    verification: "pending",
    riskTier: "medium",
    riskScore: 48,
    createdAt: days(20),
    updatedAt: days(1),
    categories: ["Textiles"],
    contacts: [
      {
        id: "c3",
        name: "Kwame Boateng",
        email: "kwame@accraweave.example",
        isPrimary: true,
        role: "Director",
      },
    ],
    locations: [
      {
        id: "l3",
        label: "Factory",
        addressLine: "Spintex Rd",
        city: "Accra",
        countryCode: "GH",
        isHeadquarters: true,
      },
    ],
    certifications: [],
    documents: [
      {
        id: "d3",
        name: "Business registration.pdf",
        kind: "kyb",
        uploadedAt: days(18),
        href: "#",
      },
    ],
    ratings: {
      overall: 0,
      quality: 0,
      delivery: 0,
      communication: 0,
      reviewCount: 0,
    },
    leadTime: { minDays: 21, maxDays: 45, typicalDays: 30 },
    performance: [],
    products: [],
    communications: [],
  },
  {
    id: "sup-chem",
    legalName: "Gulf Specialty Chemicals FZE",
    status: "suspended",
    countryCode: "AE",
    countriesServed: ["AE", "SA", "NG"],
    verification: "verified",
    riskTier: "high",
    riskScore: 71,
    createdAt: days(500),
    updatedAt: days(10),
    categories: ["Chemicals"],
    notes: "Suspended pending SDS refresh.",
    contacts: [
      {
        id: "c4",
        name: "Fatima Al Mansoori",
        email: "fatima@gulfchem.example",
        isPrimary: true,
        role: "Commercial",
      },
    ],
    locations: [
      {
        id: "l4",
        label: "JAFZA",
        addressLine: "Plot 12",
        city: "Dubai",
        countryCode: "AE",
        isHeadquarters: true,
      },
    ],
    certifications: [
      {
        id: "cert3",
        type: "ISO 14001",
        issuer: "BSI",
        number: "AE-14001-12",
        issuedAt: days(800),
        expiresAt: days(40),
        status: "expired",
      },
    ],
    documents: [],
    ratings: {
      overall: 3.2,
      quality: 3.5,
      delivery: 2.8,
      communication: 3.4,
      reviewCount: 9,
    },
    leadTime: { minDays: 14, maxDays: 40, typicalDays: 28 },
    performance: [
      { key: "otif", label: "OTIF", value: "71%", trend: "down", period: "90d" },
      {
        key: "defect",
        label: "Defect rate",
        value: "3.1%",
        trend: "up",
        period: "90d",
      },
    ],
    products: [
      {
        id: "p3",
        name: "Industrial solvent blend",
        category: "Chemicals",
        moq: "4 drums",
      },
    ],
    communications: [
      {
        id: "msg2",
        subject: "SDS update request",
        preview: "Please upload revised SDS pack.",
        updatedAt: days(8),
        href: "/messages/room-chem",
      },
    ],
  },
  {
    id: "sup-pack",
    legalName: "Lagos Pack Systems Ltd",
    tradeName: "LPS",
    status: "active",
    countryCode: "NG",
    countriesServed: ["NG"],
    verification: "verified",
    riskTier: "low",
    riskScore: 18,
    createdAt: days(200),
    updatedAt: days(5),
    categories: ["Packaging"],
    contacts: [
      {
        id: "c5",
        name: "Tunde Adebayo",
        email: "tunde@lps.example",
        phone: "+234 800 000",
        isPrimary: true,
      },
    ],
    locations: [
      {
        id: "l5",
        label: "Ikeja plant",
        addressLine: "Industrial Estate",
        city: "Lagos",
        countryCode: "NG",
        isHeadquarters: true,
      },
    ],
    certifications: [
      {
        id: "cert4",
        type: "SONCAP",
        issuer: "SON",
        number: "SON-991",
        issuedAt: days(100),
        expiresAt: days(-250),
        status: "valid",
      },
    ],
    documents: [
      {
        id: "d4",
        name: "Insurance certificate.pdf",
        kind: "insurance",
        uploadedAt: days(60),
        href: "#",
      },
    ],
    ratings: {
      overall: 4.8,
      quality: 4.9,
      delivery: 4.7,
      communication: 4.8,
      reviewCount: 31,
    },
    leadTime: { minDays: 5, maxDays: 12, typicalDays: 7 },
    performance: [
      { key: "otif", label: "OTIF", value: "98%", trend: "up", period: "90d" },
      {
        key: "response",
        label: "Quote response",
        value: "0.4d",
        trend: "up",
        period: "90d",
      },
    ],
    products: [
      {
        id: "p4",
        name: "Corrugated carton 40×40",
        category: "Packaging",
        moq: "500 pcs",
      },
    ],
    communications: [],
  },
  {
    id: "sup-steel",
    legalName: "Ankara Steel Traders AS",
    status: "archived",
    countryCode: "TR",
    countriesServed: ["TR", "NG"],
    verification: "expired",
    riskTier: "critical",
    riskScore: 88,
    createdAt: days(900),
    updatedAt: days(100),
    categories: ["Metals"],
    contacts: [
      {
        id: "c6",
        name: "Emre Yilmaz",
        email: "emre@anksteel.example",
        isPrimary: true,
      },
    ],
    locations: [
      {
        id: "l6",
        label: "Warehouse",
        addressLine: "OSB Zone",
        city: "Ankara",
        countryCode: "TR",
        isHeadquarters: true,
      },
    ],
    certifications: [],
    documents: [],
    ratings: {
      overall: 2.1,
      quality: 2.0,
      delivery: 1.8,
      communication: 2.5,
      reviewCount: 4,
    },
    leadTime: { minDays: 30, maxDays: 60, typicalDays: 45 },
    performance: [
      { key: "otif", label: "OTIF", value: "52%", trend: "down", period: "180d" },
    ],
    products: [],
    communications: [],
  },
];
