import type { InboxNotification, NotificationPreference } from "./types.js";

const now = Date.now();
const hours = (h: number) => new Date(now - h * 3_600_000).toISOString();
const days = (d: number) => new Date(now - d * 86_400_000).toISOString();

/** Storybook / test fixture covering mission notification categories + channels. */
export const notificationCenterFixture: InboxNotification[] = [
  {
    id: "n1",
    type: "procurement",
    priority: "high",
    status: "unread",
    title: "Clarification requested on PR-1042",
    body: "Ops needs destination details before sourcing continues.",
    deepLink: "/requests/pr-1042",
    createdAt: hours(1),
    kind: "procurement_update",
    channels: ["in_app", "email"],
    primaryChannel: "in_app",
  },
  {
    id: "n2",
    type: "quotation",
    priority: "high",
    status: "unread",
    title: "Quotation QT-889 received",
    body: "USD 42,500 · expires in 48 hours.",
    deepLink: "/quotations/qt-889",
    createdAt: hours(3),
    kind: "quotation_received",
    pinned: true,
    channels: ["in_app", "email"],
  },
  {
    id: "n3",
    type: "procurement",
    priority: "normal",
    status: "read",
    title: "Purchase order PO-551 approved",
    body: "Your organization approved the purchase order.",
    deepLink: "/orders/po-551",
    createdAt: hours(20),
    kind: "order_approved",
    channels: ["in_app"],
  },
  {
    id: "n4",
    type: "shipment",
    priority: "normal",
    status: "unread",
    title: "Shipment SH-901 departed origin",
    body: "Carrier Maersk · ETA 12 Aug.",
    deepLink: "/shipments/sh-901",
    createdAt: days(1.2),
    kind: "shipment_update",
    channels: ["in_app", "email"],
  },
  {
    id: "n5",
    type: "invoice",
    priority: "high",
    status: "read",
    title: "Invoice INV-4401 generated",
    body: "USD 12,200 due 15 Aug.",
    deepLink: "/invoices/inv-4401",
    createdAt: days(2),
    kind: "invoice_generated",
    channels: ["email"],
    primaryChannel: "email",
  },
  {
    id: "n6",
    type: "payment",
    priority: "normal",
    status: "read",
    title: "Payment received for INV-4390",
    body: "TT-77880 confirmed.",
    deepLink: "/payments/p-prev",
    createdAt: days(3),
    kind: "payment_received",
    channels: ["in_app", "email"],
  },
  {
    id: "n7",
    type: "announcement",
    priority: "low",
    status: "unread",
    title: "Scheduled maintenance window",
    body: "Workspace may be briefly unavailable Sunday 02:00–04:00 UTC.",
    createdAt: days(4),
    kind: "system_announcement",
    channels: ["in_app", "email"],
  },
  {
    id: "n8",
    type: "support",
    priority: "normal",
    status: "unread",
    title: "New message on PR-1042",
    body: "Ops: Please confirm the Lagos warehouse address.",
    deepLink: "/messages/m1",
    createdAt: hours(5),
    kind: "message",
    channels: ["in_app"],
  },
  {
    id: "n9",
    type: "support",
    priority: "high",
    status: "unread",
    title: "You were mentioned in PO-551",
    body: "@Ada please review the payment evidence.",
    deepLink: "/messages/m2",
    createdAt: hours(8),
    kind: "mention",
    channels: ["in_app"],
  },
  {
    id: "n10",
    type: "system",
    priority: "low",
    status: "read",
    title: "AI recommendation: complete company profile",
    body: "Faster quote turnaround when destination defaults are set.",
    deepLink: "/profile",
    createdAt: days(5),
    kind: "ai_recommendation",
    metadata: { kind: "ai_recommendation" },
    channels: ["in_app"],
  },
  {
    id: "n11",
    type: "system",
    priority: "critical",
    status: "archived",
    title: "Session security notice",
    body: "A sign-in from a new device was confirmed.",
    createdAt: days(10),
    kind: "system_announcement",
    archivedAt: days(9),
    channels: ["in_app", "email"],
  },
  {
    id: "n11b",
    type: "security",
    priority: "critical",
    status: "unread",
    title: "New device sign-in",
    body: "Confirm this sign-in or revoke the session from Security settings.",
    deepLink: "/app/settings#security",
    createdAt: hours(1),
    kind: "system_announcement",
    channels: ["in_app", "email"],
  },
  {
    id: "n12",
    type: "announcement",
    priority: "normal",
    status: "scheduled",
    title: "Weekend maintenance reminder",
    body: "Scheduled announcement for Sunday corridor window.",
    createdAt: hours(2),
    scheduledFor: new Date(now + 48 * 3_600_000).toISOString(),
    kind: "system_announcement",
    channels: ["in_app", "email"],
  },
  {
    id: "n13",
    type: "shipment",
    priority: "high",
    status: "unread",
    title: "SMS placeholder: customs hold alert",
    body: "Would deliver over SMS when the gateway is configured.",
    createdAt: hours(4),
    kind: "shipment_update",
    channels: ["sms"],
    primaryChannel: "sms",
  },
  {
    id: "n14",
    type: "procurement",
    priority: "low",
    status: "read",
    title: "Push placeholder: request update",
    body: "Push channel reserved until a provider is attached.",
    createdAt: hours(9),
    kind: "procurement_update",
    channels: ["push"],
    primaryChannel: "push",
  },
];

/** Sample channel preferences for Channels view demos. */
export const notificationPreferencesFixture: NotificationPreference[] = [
  { type: "shipment", channel: "in_app", enabled: true },
  { type: "shipment", channel: "email", enabled: true },
  { type: "shipment", channel: "sms", enabled: false },
  { type: "shipment", channel: "push", enabled: false },
  { type: "announcement", channel: "in_app", enabled: true },
  { type: "announcement", channel: "email", enabled: true },
];
