import type {
  GuidanceAnalyticsSummary,
  GuidanceTip,
  GuidanceTour,
  GuidanceUserPreference,
  GuidanceUserProgress,
} from "./types.js";

function withTourFallback(selector?: string): string | undefined {
  if (!selector) return undefined;
  if (selector.includes("data-tour=")) return selector;
  const match = selector.match(/\[data-guide=['"]([^'"]+)['"]\]/);
  if (!match?.[1]) return selector;
  return `[data-tour='${match[1]}'], ${selector}`;
}

function step(
  tourPrefix: string,
  order: number,
  stepKey: string,
  title: string,
  body: string,
  extras: Partial<GuidanceTour["steps"][number]> = {},
): GuidanceTour["steps"][number] {
  const targetSelector = withTourFallback(extras.targetSelector);
  return {
    id: `${tourPrefix}-step-${stepKey}`,
    stepKey,
    title,
    body,
    sortOrder: order,
    placement: extras.placement ?? (targetSelector ? "auto" : undefined),
    ...extras,
    ...(targetSelector ? { targetSelector } : {}),
  };
}

/** CMS-shaped published tours covering every authenticated functional surface. */
const guidanceToursFixtureBase: GuidanceTour[] = [
  {
    id: "tour-dashboard",
    key: "dashboard",
    title: "Dashboard Tour",
    description: "Learn how to read your procurement corridor at a glance.",
    audience: "client_workspace",
    pageKey: "dashboard",
    status: "published",
    estimatedMinutes: 4,
    locale: "en",
    sortOrder: 10,
    publishedAt: "2026-08-01T00:00:00Z",
    steps: [
      step("dashboard", 1, "welcome", "Welcome to your workspace", "This overview is your starting point after you sign in. Skip anytime, or restart later from Profile, Settings, or Help."),
      step("dashboard", 2, "nav-overview", "Dashboard", "Use the sidebar to return here. On a phone, open the menu first.", {
        targetSelector: "[data-guide='dashboard-nav']",
        placement: "right",
      }),
      step("dashboard", 3, "nav-requests", "Procurement requests", "Create and track sourcing requests from this area.", {
        targetSelector: "[data-guide='requests-nav']",
        placement: "right",
      }),
      step("dashboard", 4, "nav-quotes", "Quotations", "Review supplier quotations and related order work here.", {
        targetSelector: "[data-guide='quotations-nav']",
        placement: "right",
      }),
      step("dashboard", 5, "nav-support", "Messages and support", "Open Support when you need help from the operations team.", {
        targetSelector: "[data-guide='chat-nav']",
        placement: "right",
      }),
      step("dashboard", 6, "nav-alerts", "Notifications", "Alerts for your account appear here.", {
        targetSelector: "[data-guide='notifications-nav']",
        placement: "bottom",
      }),
      step("dashboard", 7, "nav-profile", "Profile and account", "Update your name and manage password reset from Profile and Settings.", {
        targetSelector: "[data-guide='profile-nav']",
        placement: "right",
      }),
    ],
  },
  {
    id: "tour-catalog",
    key: "catalog",
    title: "Catalog Tour",
    description: "Search, filter, bookmark, and compare products.",
    audience: "client_workspace",
    pageKey: "catalog",
    status: "published",
    estimatedMinutes: 5,
    locale: "en",
    sortOrder: 20,
    publishedAt: "2026-08-01T00:00:00Z",
    steps: [
      step("catalog", 1, "search", "Find products fast", "Use search and filters to narrow by category, specs, or supplier region.", {
        targetSelector: "[data-guide='catalog-search']",
        requireAction: true,
        actionEvent: "focus",
        actionLabel: "Focus the search field",
      }),
      step("catalog", 2, "filters", "Apply a filter", "Filters refine results without leaving the page. Clear them anytime.", {
        targetSelector: "[data-guide='catalog-filters']",
        requireAction: true,
        actionEvent: "click",
        actionLabel: "Apply a search filter",
      }),
      step("catalog", 3, "open", "Open product details", "Select a product card to review specifications before requesting.", {
        targetSelector: "[data-guide='catalog-product']",
        requireAction: true,
        actionEvent: "click",
        actionLabel: "Open Product Details",
      }),
    ],
  },
  {
    id: "tour-product-detail",
    key: "product_detail",
    title: "Product Details Tour",
    description: "Evaluate a product and start procurement from the detail page.",
    audience: "client_workspace",
    pageKey: "product_detail",
    status: "published",
    estimatedMinutes: 3,
    locale: "en",
    sortOrder: 21,
    publishedAt: "2026-08-01T00:00:00Z",
    steps: [
      step("product_detail", 1, "specs", "Review specifications", "Confirm units, compliance, and lead-time signals before you commit.", {
        targetSelector: "[data-guide='product-specs']",
      }),
      step("product_detail", 2, "request", "Request from product", "Start a procurement request pre-filled with this product context.", {
        targetSelector: "[data-guide='product-request']",
        requireAction: true,
        actionEvent: "click",
        actionLabel: "Start a request",
      }),
    ],
  },
  {
    id: "tour-categories",
    key: "categories",
    title: "Categories Tour",
    description: "Browse the enterprise category tree.",
    audience: "client_workspace",
    pageKey: "categories",
    status: "published",
    estimatedMinutes: 2,
    locale: "en",
    sortOrder: 22,
    publishedAt: "2026-08-01T00:00:00Z",
    steps: [
      step("categories", 1, "tree", "Navigate categories", "Drill into categories to discover approved product families.", {
        targetSelector: "[data-guide='category-tree']",
      }),
    ],
  },
  {
    id: "tour-bookmarks",
    key: "bookmarks",
    title: "Bookmarks Tour",
    description: "Save products for later procurement cycles.",
    audience: "client_workspace",
    pageKey: "bookmarks",
    status: "published",
    estimatedMinutes: 2,
    locale: "en",
    sortOrder: 23,
    publishedAt: "2026-08-01T00:00:00Z",
    steps: [
      step("bookmarks", 1, "list", "Your saved products", "Bookmarks keep shortlists ready for RFQs and comparisons.", {
        targetSelector: "[data-guide='bookmarks-list']",
      }),
    ],
  },
  {
    id: "tour-compare",
    key: "compare",
    title: "Compare Tour",
    description: "Side-by-side product evaluation.",
    audience: "client_workspace",
    pageKey: "compare",
    status: "published",
    estimatedMinutes: 3,
    locale: "en",
    sortOrder: 24,
    publishedAt: "2026-08-01T00:00:00Z",
    steps: [
      step("compare", 1, "table", "Compare attributes", "Use the comparison grid to decide which SKU meets policy and budget.", {
        targetSelector: "[data-guide='compare-table']",
      }),
    ],
  },
  {
    id: "tour-procurement",
    key: "procurement",
    title: "Procurement Tour",
    description: "Create, track, and manage procurement requests.",
    audience: "client_workspace",
    pageKey: "procurement_requests",
    status: "published",
    estimatedMinutes: 6,
    locale: "en",
    sortOrder: 30,
    publishedAt: "2026-08-01T00:00:00Z",
    steps: [
      step("procurement", 1, "welcome", "Welcome to Requests", "Create and track procurement requests from draft through sourcing. Filter the inbox, open a card, or start a new request when you know what you need. Skip anytime, or use More tours for another module."),
      step("procurement", 2, "list", "Request inbox", "Filter by status to find drafts, clarifications, and sourcing work.", {
        targetSelector: "[data-guide='request-list']",
      }),
      step("procurement", 3, "create", "Start a new request", "New request opens the wizard. Save a draft any time and submit when line items are complete.", {
        targetSelector: "[data-guide='create-request']",
      }),
    ],
  },
  {
    id: "tour-request-wizard",
    key: "request_wizard",
    title: "Request Wizard Tour",
    description: "Complete a guided multi-step procurement request.",
    audience: "client_workspace",
    pageKey: "request_wizard",
    status: "published",
    estimatedMinutes: 7,
    locale: "en",
    sortOrder: 31,
    publishedAt: "2026-08-01T00:00:00Z",
    steps: [
      step("request_wizard", 1, "welcome", "Welcome to the request wizard", "Walk through commercial context step by step. Required fields must be complete before you continue. Skip this tour anytime if you already know the flow."),
      step("request_wizard", 2, "steps", "Wizard progress", "Each step captures commercial context. You can save a draft at any time.", {
        targetSelector: "[data-guide='wizard-steps']",
        placement: "bottom",
      }),
      step("request_wizard", 3, "draft", "Save as draft", "Save and continue later keeps unfinished work across sessions.", {
        targetSelector: "[data-guide='save-draft']",
        placement: "top",
      }),
      step("request_wizard", 4, "submit", "Submit when ready", "On the review step, Submit routes the request to operations for sourcing.", {
        targetSelector: "[data-guide='submit-request']",
        placement: "top",
      }),
    ],
  },
  {
    id: "tour-draft-requests",
    key: "draft_requests",
    title: "Draft Requests Tour",
    description: "Resume or submit unfinished requests.",
    audience: "client_workspace",
    pageKey: "draft_requests",
    status: "published",
    estimatedMinutes: 2,
    locale: "en",
    sortOrder: 32,
    publishedAt: "2026-08-01T00:00:00Z",
    steps: [
      step("draft_requests", 1, "resume", "Resume a draft", "Open a draft to continue the wizard where you left off.", {
        targetSelector: "[data-guide='draft-row']",
        requireAction: true,
        actionEvent: "click",
        actionLabel: "Open a draft",
      }),
    ],
  },
  {
    id: "tour-quotation",
    key: "quotation",
    title: "Quotation Tour",
    description: "Review commercial offers and respond confidently.",
    audience: "client_workspace",
    pageKey: "quotations",
    status: "published",
    estimatedMinutes: 5,
    locale: "en",
    sortOrder: 40,
    publishedAt: "2026-08-01T00:00:00Z",
    steps: [
      step("quotation", 1, "welcome", "Welcome to Quotations", "This is where supplier offers land. Review totals, validity, and terms, then accept, reject, or request a revision. Use Skip anytime, or More tours to learn another area."),
      step("quotation", 2, "list", "Issued quotations", "The directory lists every offer with status, supplier, and total. Filter or search to find one quickly.", {
        targetSelector: "[data-guide='quotation-list']",
      }),
      step("quotation", 3, "review", "Review an offer", "Open a quotation card to compare line items, Incoterms, and lead times, then take a commercial action.", {
        targetSelector: "[data-guide='quotation-open']",
      }),
    ],
  },
  {
    id: "tour-purchase-orders",
    key: "purchase_orders",
    title: "Purchase Orders Tour",
    description: "Follow approved commercial commitments.",
    audience: "client_workspace",
    pageKey: "purchase_orders",
    status: "published",
    estimatedMinutes: 3,
    locale: "en",
    sortOrder: 45,
    publishedAt: "2026-08-01T00:00:00Z",
    steps: [
      step("purchase_orders", 1, "list", "PO register", "Purchase orders lock commercial terms for fulfillment and finance.", {
        targetSelector: "[data-guide='po-list']",
      }),
    ],
  },
  {
    id: "tour-finance",
    key: "finance",
    title: "Finance Tour",
    description: "Invoices and payments from issue to confirmation.",
    audience: "client_workspace",
    pageKey: "invoices",
    status: "published",
    estimatedMinutes: 5,
    locale: "en",
    sortOrder: 50,
    publishedAt: "2026-08-01T00:00:00Z",
    steps: [
      step("finance", 1, "invoices", "Invoice workspace", "Open invoices to review amounts, due dates, and linked POs.", {
        targetSelector: "[data-guide='invoice-list']",
      }),
      step("finance", 2, "payments", "Payment actions", "Submit or confirm payments according to your organization policy.", {
        targetSelector: "[data-guide='payment-actions']",
        requireAction: true,
        actionEvent: "click",
        actionLabel: "Open payment actions",
      }),
    ],
  },
  {
    id: "tour-shipment",
    key: "shipment",
    title: "Shipment Tour",
    description: "Track logistics from dispatch to delivery confirmation.",
    audience: "client_workspace",
    pageKey: "shipments",
    status: "published",
    estimatedMinutes: 4,
    locale: "en",
    sortOrder: 60,
    publishedAt: "2026-08-01T00:00:00Z",
    steps: [
      step("shipment", 1, "welcome", "Welcome to Shipments", "Track consignments from dispatch to delivery. Open a shipment for carrier, ETA, milestones, and documents. Skip anytime, or use More tours for another module."),
      step("shipment", 2, "list", "Active shipments", "See carrier, ETA, and status for every consignment.", {
        targetSelector: "[data-guide='shipment-list']",
      }),
      step("shipment", 3, "track", "Tracking timeline", "The Tracking tab shows milestones and exceptions for the selected shipment.", {
        targetSelector: "[data-guide='shipment-track']",
      }),
    ],
  },
  {
    id: "tour-notifications",
    key: "notifications",
    title: "Notifications Tour",
    description: "Stay current without leaving your workflow.",
    audience: "all_authenticated",
    pageKey: "notifications",
    status: "published",
    estimatedMinutes: 3,
    locale: "en",
    sortOrder: 70,
    publishedAt: "2026-08-01T00:00:00Z",
    steps: [
      step("notifications", 1, "welcome", "Welcome to Notifications", "Stay current without leaving your workflow. Unread items, archives, and channel preferences live here. Skip anytime, or open More tours."),
      step("notifications", 2, "center", "Inbox and settings", "Switch between Inbox and Settings to mark items read or choose which channels you receive.", {
        targetSelector: "[data-guide='notification-center']",
      }),
      step("notifications", 3, "open", "Top-bar bell", "The bell in the workspace top bar also opens this center from any page.", {
        targetSelector: "[data-guide='notification-trigger']",
      }),
    ],
  },
  {
    id: "tour-messages",
    key: "messages",
    title: "Messages Tour",
    description: "Structured message threads for procurement collaboration.",
    audience: "client_workspace",
    pageKey: "messages",
    status: "published",
    estimatedMinutes: 3,
    locale: "en",
    sortOrder: 71,
    publishedAt: "2026-08-01T00:00:00Z",
    steps: [
      step("messages", 1, "inbox", "Message inbox", "Threads stay linked to requests, quotes, and shipments.", {
        targetSelector: "[data-guide='messages-inbox']",
      }),
    ],
  },
  {
    id: "tour-chat",
    key: "chat",
    title: "Chat Tour",
    description: "Real-time chat for urgent coordination.",
    audience: "client_workspace",
    pageKey: "chat",
    status: "published",
    estimatedMinutes: 2,
    locale: "en",
    sortOrder: 72,
    publishedAt: "2026-08-01T00:00:00Z",
    steps: [
      step("chat", 1, "welcome", "Welcome to Chat", "Use chat for fast clarification with operations. Keep formal decisions on the request or quotation record. Skip anytime, or use More tours."),
      step("chat", 2, "rooms", "Conversations", "Pick a room on the left, then send messages, files, or pins in the thread.", {
        targetSelector: "[data-guide='chat-rooms']",
      }),
    ],
  },
  {
    id: "tour-settings",
    key: "settings",
    title: "Settings Tour",
    description: "Profile, security, and organization preferences.",
    audience: "all_authenticated",
    pageKey: "settings",
    status: "published",
    estimatedMinutes: 4,
    locale: "en",
    sortOrder: 80,
    publishedAt: "2026-08-01T00:00:00Z",
    steps: [
      step("settings", 1, "welcome", "Welcome to Account", "Update your profile and reset your password by email here. Skip anytime, or use More tours to learn another module."),
      step("settings", 2, "profile", "Complete your profile", "Accurate name and organization details improve routing and notifications.", {
        targetSelector: "[data-guide='profile-form']",
      }),
      step("settings", 3, "security", "Reset password by email", "Password changes require a verification link sent to your account email.", {
        targetSelector: "[data-guide='security-panel']",
      }),
    ],
  },
  {
    id: "tour-supplier",
    key: "supplier",
    title: "Supplier Tour",
    description: "Qualify and manage supplier relationships (operations).",
    audience: "operations_console",
    pageKey: "suppliers",
    status: "published",
    estimatedMinutes: 5,
    locale: "en",
    sortOrder: 90,
    publishedAt: "2026-08-01T00:00:00Z",
    steps: [
      step("supplier", 1, "directory", "Supplier directory", "Search, qualify, and open supplier profiles.", {
        targetSelector: "[data-guide='supplier-list']",
      }),
      step("supplier", 2, "open", "Open a supplier", "Review capability, regions, and compliance status.", {
        targetSelector: "[data-guide='supplier-row']",
        requireAction: true,
        actionEvent: "click",
        actionLabel: "Open a supplier",
      }),
    ],
  },
  {
    id: "tour-analytics",
    key: "analytics",
    title: "Analytics Tour",
    description: "Operational insight and exportable reports.",
    audience: "operations_console",
    pageKey: "analytics",
    status: "published",
    estimatedMinutes: 4,
    locale: "en",
    sortOrder: 100,
    publishedAt: "2026-08-01T00:00:00Z",
    steps: [
      step("analytics", 1, "range", "Change the range", "Adjust time windows to compare cycles and SLAs.", {
        targetSelector: "[data-guide='analytics-range']",
        requireAction: true,
        actionEvent: "click",
        actionLabel: "Change analytics range",
      }),
      step("analytics", 2, "export", "Export insights", "Export for offline review or board reporting.", {
        targetSelector: "[data-guide='analytics-export']",
      }),
    ],
  },
  {
    id: "tour-administration",
    key: "administration",
    title: "Administration Tour",
    description: "CMS, audit, platform config, and org management.",
    audience: "operations_console",
    pageKey: "administration",
    status: "published",
    estimatedMinutes: 6,
    locale: "en",
    sortOrder: 110,
    publishedAt: "2026-08-01T00:00:00Z",
    steps: [
      step("administration", 1, "modules", "Admin modules", "CMS, audit logs, email center, and platform config live under Administration.", {
        targetSelector: "[data-guide='admin-nav']",
      }),
      step("administration", 2, "audit", "Audit logs", "Every sensitive action is attributable and exportable.", {
        targetSelector: "[data-guide='audit-table']",
      }),
      step("administration", 3, "guidance", "Update tours without rewrites", "Publish and schedule product tours from Guidance Admin - hosts consume the catalog API.", {
        targetSelector: "[data-guide='admin-guidance']",
        placement: "center",
      }),
    ],
  },
  {
    id: "tour-assistant",
    key: "assistant",
    title: "AI Assistant Tour",
    description: "Use the AI procurement assistant responsibly.",
    audience: "client_workspace",
    pageKey: "assistant",
    status: "published",
    estimatedMinutes: 3,
    locale: "en",
    sortOrder: 120,
    publishedAt: "2026-08-01T00:00:00Z",
    steps: [
      step("assistant", 1, "ask", "Ask with context", "Describe the need; the assistant suggests catalog matches and next steps.", {
        targetSelector: "[data-guide='assistant-input']",
        requireAction: true,
        actionEvent: "focus",
        actionLabel: "Focus the assistant input",
      }),
    ],
  },
  {
    id: "tour-learning-center",
    key: "learning_center",
    title: "Learning Center Tour",
    description: "Launch any tour and track completion.",
    audience: "all_authenticated",
    pageKey: "learning_center",
    status: "published",
    estimatedMinutes: 2,
    locale: "en",
    sortOrder: 5,
    publishedAt: "2026-08-01T00:00:00Z",
    steps: [
      step("learning_center", 1, "search", "Find a tour", "Search by keyword to jump to the workflow you need.", {
        targetSelector: "[data-guide='learning-search']",
      }),
      step("learning_center", 2, "launch", "Launch a tour", "Start any published walkthrough from here.", {
        targetSelector: "[data-guide='learning-launch']",
        requireAction: true,
        actionEvent: "click",
        actionLabel: "Launch a tour",
      }),
    ],
  },
  {
    id: "tour-public-home",
    key: "public_home",
    title: "Welcome to Almahbub International",
    description: "A quick orientation for first-time visitors.",
    audience: "public_visitor",
    pageKey: "public_home",
    status: "published",
    estimatedMinutes: 2,
    locale: "en",
    sortOrder: 1,
    publishedAt: "2026-08-06T00:00:00Z",
    steps: [
      step("public_home", 1, "brand", "Meet the brand", "Almahbub International is Almahbub International’s enterprise procurement platform.", {
        targetSelector: "[data-guide='public-brand']",
        placement: "bottom",
      }),
      step("public_home", 2, "nav", "Explore the site", "Use primary navigation to browse services, products, and industries.", {
        targetSelector: "[data-guide='public-actions']",
        placement: "bottom",
      }),
      step("public_home", 3, "cta", "Start a conversation", "Request procurement support or sign in when you are ready to work.", {
        targetSelector: "[data-guide='public-brand']",
        placement: "bottom",
      }),
    ],
  },
  {
    id: "tour-supplier-portal",
    key: "supplier_portal",
    title: "Supplier Portal Tour",
    description: "Future-ready orientation for supplier collaborators.",
    audience: "supplier_portal",
    pageKey: "suppliers",
    status: "published",
    estimatedMinutes: 3,
    locale: "en",
    sortOrder: 210,
    publishedAt: "2026-08-06T00:00:00Z",
    steps: [
      step("supplier_portal", 1, "inbox", "Supplier inbox", "Review RFQs and respond with commercial clarity.", {
        targetSelector: "[data-guide='supplier-inbox']",
        placement: "center",
      }),
      step("supplier_portal", 2, "profile", "Keep profile current", "Capabilities and certifications improve match quality.", {
        targetSelector: "[data-guide='supplier-profile']",
        placement: "center",
      }),
    ],
  },
];

/** Versioned catalog - bump `version` when CMS ships new onboarding content. */
export const guidanceToursFixture: GuidanceTour[] = guidanceToursFixtureBase.map(
  (tour) => ({
    ...tour,
    version: tour.version ?? 1,
  }),
);

export const guidanceTipsFixture: GuidanceTip[] = [
  {
    id: "tip-bookmarks",
    key: "bookmarks_first",
    featureKey: "bookmarks",
    pageKey: "catalog",
    title: "Bookmarks",
    body: "Save products you revisit often. Bookmarks sync across devices.",
    targetSelector: "[data-guide-tip='bookmarks']",
    locale: "en",
    enabled: true,
  },
  {
    id: "tip-compare",
    key: "compare_first",
    featureKey: "compare",
    pageKey: "catalog",
    title: "Compare",
    body: "Add up to several products and compare specs side by side before requesting.",
    targetSelector: "[data-guide-tip='compare']",
    locale: "en",
    enabled: true,
  },
  {
    id: "tip-assistant",
    key: "assistant_first",
    featureKey: "assistant",
    pageKey: "dashboard",
    title: "AI Assistant",
    body: "Ask natural-language questions about sourcing. Suggestions stay advisory until you act.",
    targetSelector: "[data-guide-tip='assistant']",
    locale: "en",
    enabled: true,
  },
  {
    id: "tip-export",
    key: "export_first",
    featureKey: "export",
    pageKey: "analytics",
    title: "Export",
    body: "Export tables and charts for offline review. Exports respect your role scope.",
    targetSelector: "[data-guide-tip='export']",
    locale: "en",
    enabled: true,
  },
  {
    id: "tip-analytics",
    key: "analytics_first",
    featureKey: "analytics",
    pageKey: "analytics",
    title: "Analytics",
    body: "Track cycle time, win rates, and exception volume for your organization.",
    targetSelector: "[data-guide-tip='analytics']",
    locale: "en",
    enabled: true,
  },
  {
    id: "tip-filters",
    key: "filters_first",
    featureKey: "filters",
    pageKey: "procurement_requests",
    title: "Filters",
    body: "Combine status, priority, and assignee filters to focus your inbox.",
    targetSelector: "[data-guide-tip='filters']",
    locale: "en",
    enabled: true,
  },
  {
    id: "tip-saved-searches",
    key: "saved_searches_first",
    featureKey: "saved_searches",
    pageKey: "catalog",
    title: "Saved searches",
    body: "Persist frequent queries so your team returns to the same result set.",
    targetSelector: "[data-guide-tip='saved-searches']",
    locale: "en",
    enabled: true,
  },
  {
    id: "tip-quick-actions",
    key: "quick_actions_first",
    featureKey: "quick_actions",
    pageKey: "dashboard",
    title: "Quick actions",
    body: "Jump into create, messages, and documents without leaving the dashboard.",
    targetSelector: "[data-guide-tip='quick-actions']",
    locale: "en",
    enabled: true,
  },
  {
    id: "tip-timeline",
    key: "timeline_first",
    featureKey: "timeline",
    pageKey: "procurement_requests",
    title: "Timeline",
    body: "Every status change is recorded with actor and timestamp for auditability.",
    targetSelector: "[data-guide-tip='timeline']",
    locale: "en",
    enabled: true,
  },
  {
    id: "tip-tracking",
    key: "tracking_first",
    featureKey: "tracking",
    pageKey: "shipments",
    title: "Tracking",
    body: "Carrier milestones update automatically; exceptions surface in attention lists.",
    targetSelector: "[data-guide-tip='tracking']",
    locale: "en",
    enabled: true,
  },
  {
    id: "tip-documents",
    key: "documents_first",
    featureKey: "documents",
    pageKey: "procurement_requests",
    title: "Documents",
    body: "Attach specs and certificates to keep commercial context with the request.",
    targetSelector: "[data-guide-tip='documents']",
    locale: "en",
    enabled: true,
  },
];

export const guidancePreferenceFixture: GuidanceUserPreference = {
  mode: "guided",
  neverAutoStart: false,
  welcomeCompletedAt: null,
  locale: "en",
};

export const guidanceProgressFixture: GuidanceUserProgress[] = [
  {
    tourId: "tour-learning-center",
    tourKey: "learning_center",
    status: "not_started",
    completedSteps: 0,
    totalSteps: 2,
    lastActiveAt: "2026-08-05T12:00:00Z",
  },
];

export const guidanceAnalyticsFixture: GuidanceAnalyticsSummary = {
  totalUsers: 128,
  welcomeCompleted: 96,
  toursCompleted: 412,
  toursSkipped: 54,
  modeBreakdown: { off: 18, guided: 84, training: 26 },
  completionRate: 62,
};

export const dismissedTipIdsFixture: string[] = [];
