import type { GuidancePageDescriptor } from "./types.js";

/**
 * Audit registry of authenticated functional pages that participate in guidance.
 * Public marketing surfaces (Home, About, Contact, Privacy, Terms, etc.) are excluded.
 */
export const GUIDANCE_PAGE_REGISTRY: readonly GuidancePageDescriptor[] = [
  {
    pageKey: "dashboard",
    label: "Dashboard",
    application: "client_workspace",
    pathPattern: "/dashboard",
    primaryActions: ["New procurement request", "Open attention items", "View stats"],
    tourKey: "dashboard",
  },
  {
    pageKey: "catalog",
    label: "Product Catalog",
    application: "client_workspace",
    pathPattern: "/catalog",
    primaryActions: ["Search", "Filter", "Bookmark", "Compare", "Open product"],
    tourKey: "catalog",
  },
  {
    pageKey: "product_detail",
    label: "Product Details",
    application: "client_workspace",
    pathPattern: "/catalog/:slug",
    primaryActions: ["Request quote", "Bookmark", "Compare", "View specs"],
    tourKey: "product_detail",
  },
  {
    pageKey: "categories",
    label: "Categories",
    application: "client_workspace",
    pathPattern: "/categories",
    primaryActions: ["Browse category", "Filter"],
    tourKey: "categories",
  },
  {
    pageKey: "bookmarks",
    label: "Bookmarks",
    application: "client_workspace",
    pathPattern: "/bookmarks",
    primaryActions: ["Open bookmarked product", "Remove bookmark"],
    tourKey: "bookmarks",
  },
  {
    pageKey: "compare",
    label: "Compare Products",
    application: "client_workspace",
    pathPattern: "/compare",
    primaryActions: ["Add product", "Remove product", "Export comparison"],
    tourKey: "compare",
  },
  {
    pageKey: "procurement_requests",
    label: "Procurement Requests",
    application: "client_workspace",
    pathPattern: "/requests",
    primaryActions: ["Create request", "Filter status", "Open request"],
    tourKey: "procurement",
  },
  {
    pageKey: "request_wizard",
    label: "Request Wizard",
    application: "client_workspace",
    pathPattern: "/requests/new",
    primaryActions: ["Next step", "Save draft", "Submit"],
    tourKey: "request_wizard",
  },
  {
    pageKey: "draft_requests",
    label: "Draft Requests",
    application: "client_workspace",
    pathPattern: "/requests?status=draft",
    primaryActions: ["Resume draft", "Delete draft", "Submit draft"],
    tourKey: "draft_requests",
  },
  {
    pageKey: "quotations",
    label: "Quotations",
    application: "client_workspace",
    pathPattern: "/quotations",
    primaryActions: ["Review quote", "Accept", "Request revision"],
    tourKey: "quotation",
  },
  {
    pageKey: "purchase_orders",
    label: "Purchase Orders",
    application: "client_workspace",
    pathPattern: "/purchase-orders",
    primaryActions: ["Open PO", "Download", "Track fulfillment"],
    tourKey: "purchase_orders",
  },
  {
    pageKey: "invoices",
    label: "Invoices",
    application: "client_workspace",
    pathPattern: "/invoices",
    primaryActions: ["Open invoice", "Pay", "Download PDF"],
    tourKey: "finance",
  },
  {
    pageKey: "payments",
    label: "Payments",
    application: "client_workspace",
    pathPattern: "/payments",
    primaryActions: ["Submit payment", "Confirm", "View history"],
    tourKey: "finance",
  },
  {
    pageKey: "shipments",
    label: "Shipments",
    application: "client_workspace",
    pathPattern: "/shipments",
    primaryActions: ["Open shipment", "Track", "Confirm receipt"],
    tourKey: "shipment",
  },
  {
    pageKey: "tracking",
    label: "Tracking",
    application: "client_workspace",
    pathPattern: "/shipments/:id/tracking",
    primaryActions: ["Refresh tracking", "View timeline", "Contact ops"],
    tourKey: "shipment",
  },
  {
    pageKey: "notifications",
    label: "Notifications",
    application: "all_authenticated",
    pathPattern: "/notifications",
    primaryActions: ["Mark read", "Archive", "Open preferences"],
    tourKey: "notifications",
  },
  {
    pageKey: "messages",
    label: "Messages",
    application: "client_workspace",
    pathPattern: "/messages",
    primaryActions: ["Open thread", "Compose", "Search"],
    tourKey: "messages",
  },
  {
    pageKey: "chat",
    label: "Chat",
    application: "client_workspace",
    pathPattern: "/chat",
    primaryActions: ["Send message", "Attach file", "Open room"],
    tourKey: "chat",
  },
  {
    pageKey: "profile",
    label: "Profile",
    application: "all_authenticated",
    pathPattern: "/profile",
    primaryActions: ["Edit profile", "Upload photo", "Save"],
    tourKey: "settings",
  },
  {
    pageKey: "settings",
    label: "Settings",
    application: "all_authenticated",
    pathPattern: "/settings",
    primaryActions: ["Update preferences", "Switch organization", "Locale"],
    tourKey: "settings",
  },
  {
    pageKey: "security",
    label: "Security",
    application: "all_authenticated",
    pathPattern: "/settings/security",
    primaryActions: ["Enable MFA", "Revoke session", "Change password"],
    tourKey: "settings",
  },
  {
    pageKey: "organization",
    label: "Organization Management",
    application: "operations_console",
    pathPattern: "/admin/organizations",
    primaryActions: ["Invite member", "Assign role", "Switch organization"],
    tourKey: "administration",
  },
  {
    pageKey: "suppliers",
    label: "Supplier Management",
    application: "operations_console",
    pathPattern: "/suppliers",
    primaryActions: ["Add supplier", "Qualify", "Open profile"],
    tourKey: "supplier",
  },
  {
    pageKey: "analytics",
    label: "Analytics",
    application: "operations_console",
    pathPattern: "/analytics",
    primaryActions: ["Change range", "Export", "Drill down"],
    tourKey: "analytics",
  },
  {
    pageKey: "reports",
    label: "Reports",
    application: "operations_console",
    pathPattern: "/reports",
    primaryActions: ["Generate report", "Schedule", "Download"],
    tourKey: "analytics",
  },
  {
    pageKey: "cms",
    label: "CMS",
    application: "operations_console",
    pathPattern: "/admin/cms",
    primaryActions: ["Create content", "Publish", "Schedule"],
    tourKey: "administration",
  },
  {
    pageKey: "audit",
    label: "Audit Logs",
    application: "operations_console",
    pathPattern: "/admin/audit",
    primaryActions: ["Filter events", "Export", "Open detail"],
    tourKey: "administration",
  },
  {
    pageKey: "administration",
    label: "Administration",
    application: "operations_console",
    pathPattern: "/admin",
    primaryActions: ["Open module", "View health", "Manage roles"],
    tourKey: "administration",
  },
  {
    pageKey: "assistant",
    label: "AI Procurement Assistant",
    application: "client_workspace",
    pathPattern: "/assistant",
    primaryActions: ["Ask question", "Apply suggestion", "Open history"],
    tourKey: "assistant",
  },
  {
    pageKey: "email_center",
    label: "Email Center",
    application: "operations_console",
    pathPattern: "/admin/email",
    primaryActions: ["Edit template", "Preview", "Publish"],
    tourKey: "administration",
  },
  {
    pageKey: "platform_config",
    label: "Platform Config",
    application: "operations_console",
    pathPattern: "/admin/platform",
    primaryActions: ["Update setting", "Save", "Reset"],
    tourKey: "administration",
  },
  {
    pageKey: "recommendations",
    label: "Recommendations",
    application: "client_workspace",
    pathPattern: "/recommendations",
    primaryActions: ["Apply recommendation", "Dismiss", "Open product"],
    tourKey: "catalog",
  },
  {
    pageKey: "learning_center",
    label: "Help & Learning Center",
    application: "all_authenticated",
    pathPattern: "/help",
    primaryActions: ["Search tours", "Launch tour", "View progress"],
    tourKey: "learning_center",
  },
] as const;

export const PUBLIC_PAGES_EXCLUDED_FROM_GUIDANCE = [
  "home",
  "about",
  "contact",
  "privacy",
  "terms",
  "services",
  "industries",
  "careers",
  "news",
  "login",
  "register",
  "forgot_password",
] as const;
