import type { AuditEvent, AuditRetentionPolicy } from "./types.js";

const hours = (h: number) =>
  new Date(Date.now() - h * 3_600_000).toISOString();

/** Mission coverage - one+ event per log category. */
export const auditEventsFixture: AuditEvent[] = [
  {
    id: "aud-auth-1",
    category: "authentication",
    action: "auth.login.success",
    summary: "Someone signed in successfully",
    outcome: "success",
    severity: "low",
    actor: { id: "u-ada", name: "Ada Okonkwo", type: "user" },
    target: { type: "session", id: "sess-991", label: "Web session" },
    occurredAt: hours(1),
    correlationId: "corr-a1",
    requestId: "req-a1",
    ipAddress: "102.89.*.*",
    retentionClass: "identity-365",
  },
  {
    id: "aud-auth-2",
    category: "authentication",
    action: "auth.login.failure",
    summary: "Sign-in attempt failed",
    outcome: "failure",
    severity: "medium",
    actor: { name: "unknown@example.com", type: "user" },
    occurredAt: hours(3),
    correlationId: "corr-a2",
    ipAddress: "41.203.*.*",
    reason: "Wrong password",
    retentionClass: "identity-365",
  },
  {
    id: "aud-role-1",
    category: "role_changes",
    action: "iam.role.assign",
    summary: "Gave Leo Mensah the procurement officer role",
    outcome: "success",
    severity: "high",
    actor: {
      id: "u-admin",
      name: "Platform Admin",
      type: "user",
      organizationName: "Almahbub Ops",
    },
    target: { type: "user", id: "u-leo", label: "Leo Mensah" },
    occurredAt: hours(6),
    reason: "Team expansion",
    metadata: { role: "procurement_officer", previous: ["viewer"] },
    retentionClass: "iam-2555",
  },
  {
    id: "aud-perm-1",
    category: "permission_changes",
    action: "iam.permission.grant",
    summary: "Allowed finance leads to confirm payments",
    outcome: "success",
    severity: "critical",
    actor: { id: "u-sec", name: "Security Reviewer", type: "user" },
    target: { type: "role", id: "role-finance-lead", label: "Finance lead" },
    occurredAt: hours(10),
    reason: "Dual-control approval completed",
    metadata: { permission: "payment:confirm" },
    retentionClass: "iam-2555",
    legalHold: true,
  },
  {
    id: "aud-proc-1",
    category: "procurement_actions",
    action: "procurement.request.submit",
    summary: "Submitted purchase request PR-1042 for a quote",
    outcome: "success",
    severity: "low",
    actor: { id: "u-ada", name: "Ada Okonkwo", type: "user" },
    target: { type: "procurement_request", id: "pr-1042", label: "PR-1042" },
    occurredAt: hours(12),
    retentionClass: "commercial-2555",
  },
  {
    id: "aud-appr-1",
    category: "approvals",
    action: "approval.po.approve",
    summary: "Approved purchase order PO-778",
    outcome: "success",
    severity: "medium",
    actor: { id: "u-cfo", name: "Fatima Bello", type: "user" },
    target: { type: "purchase_order", id: "po-778", label: "PO-778" },
    occurredAt: hours(18),
    reason: "Within delegated limit",
    retentionClass: "commercial-2555",
  },
  {
    id: "aud-pay-1",
    category: "payments",
    action: "payment.confirm",
    summary: "Confirmed payment for invoice INV-2201",
    outcome: "success",
    severity: "high",
    actor: { id: "u-fin", name: "Chidi Nwosu", type: "user" },
    target: { type: "invoice", id: "inv-2201", label: "INV-2201" },
    occurredAt: hours(22),
    correlationId: "corr-pay-9",
    retentionClass: "finance-2555",
    legalHold: false,
  },
  {
    id: "aud-sup-1",
    category: "supplier_updates",
    action: "supplier.bank.update",
    summary: "Supplier bank details submitted for review",
    outcome: "pending_review",
    severity: "high",
    actor: { id: "u-sup", name: "West Africa Valves", type: "user" },
    target: { type: "supplier", id: "sup-44", label: "West Africa Valves" },
    occurredAt: hours(28),
    reason: "Bank account change",
    retentionClass: "supplier-2555",
  },
  {
    id: "aud-cms-1",
    category: "cms_changes",
    action: "cms.content.publish",
    summary: "Published homepage banner update",
    outcome: "success",
    severity: "low",
    actor: { id: "u-cms", name: "Content Publisher", type: "user" },
    target: {
      type: "cms_content",
      id: "cms-hero-1",
      label: "Primary homepage hero",
    },
    occurredAt: hours(36),
    retentionClass: "cms-730",
  },
  {
    id: "aud-sec-1",
    category: "security_events",
    action: "security.token.reuse",
    summary: "Suspicious session reuse was blocked",
    outcome: "denied",
    severity: "critical",
    actor: { name: "session-risk-engine", type: "system" },
    target: { type: "token_family", id: "tf-881", label: "Token family 881" },
    occurredAt: hours(4),
    correlationId: "corr-sec-3",
    reason: "Reuse detected",
    retentionClass: "security-2555",
    legalHold: true,
  },
  {
    id: "aud-sec-2",
    category: "security_events",
    action: "security.export.blocked",
    summary: "An export attempt was blocked",
    outcome: "denied",
    severity: "high",
    actor: { id: "u-guest", name: "Restricted Viewer", type: "user" },
    target: { type: "audit_export", label: "Audit export" },
    occurredAt: hours(48),
    retentionClass: "security-2555",
  },
];

export const auditRetentionFixture: AuditRetentionPolicy = {
  defaultDays: 365,
  byCategory: {
    authentication: 365,
    role_changes: 2555,
    permission_changes: 2555,
    procurement_actions: 2555,
    approvals: 2555,
    payments: 2555,
    supplier_updates: 2555,
    cms_changes: 730,
    security_events: 2555,
  },
  legalHoldNote:
    "Events marked for legal hold are kept until the hold is released.",
  lastReviewedAt: new Date(Date.now() - 14 * 86_400_000).toISOString(),
};
