export type RouteAccess = "public" | "authenticated";

export interface RoutePolicy {
  readonly method: string;
  readonly path: string;
  readonly access: RouteAccess;
  readonly permission?: string;
}

/**
 * Central route metadata lets tests verify authorization expectations without
 * starting an HTTP server or inspecting Express internals.
 */
export const routePolicies = [
  { method: "GET", path: "/health/live", access: "public" },
  { method: "GET", path: "/health/ready", access: "public" },
  { method: "GET", path: "/openapi.json", access: "public" },
  { method: "GET", path: "/docs", access: "public" },
  { method: "GET", path: "/api/v1/products", access: "public" },
  { method: "GET", path: "/api/v1/products/:slug", access: "public" },
  { method: "GET", path: "/api/v1/categories", access: "public" },
  { method: "GET", path: "/api/v1/public/catalog-media/:productId/:filename", access: "public" },
  { method: "GET", path: "/api/v1/ops/dashboard", access: "authenticated", permission: "ops:access" },
  { method: "GET", path: "/api/v1/ops/audit-events", access: "authenticated", permission: "ops:access" },
  { method: "GET", path: "/api/v1/ops/identity", access: "authenticated", permission: "ops:access" },
  { method: "PATCH", path: "/api/v1/ops/identity/users/:userId/status", access: "authenticated", permission: "ops:access" },
  { method: "PATCH", path: "/api/v1/ops/identity/users/:userId/ops-access", access: "authenticated", permission: "ops:access" },
  { method: "GET", path: "/api/v1/ops/suppliers", access: "authenticated", permission: "ops:access" },
  { method: "GET", path: "/api/v1/ops/products", access: "authenticated", permission: "ops:access" },
  { method: "POST", path: "/api/v1/ops/products", access: "authenticated", permission: "ops:access" },
  { method: "GET", path: "/api/v1/ops/products/:id", access: "authenticated", permission: "ops:access" },
  { method: "PATCH", path: "/api/v1/ops/products/:id", access: "authenticated", permission: "ops:access" },
  { method: "POST", path: "/api/v1/ops/products/:id/images", access: "authenticated", permission: "ops:access" },
  { method: "POST", path: "/api/v1/ops/products/:id/images/upload", access: "authenticated", permission: "ops:access" },
  { method: "PATCH", path: "/api/v1/ops/products/:id/images/:imageId", access: "authenticated", permission: "ops:access" },
  { method: "DELETE", path: "/api/v1/ops/products/:id/images/:imageId", access: "authenticated", permission: "ops:access" },
  { method: "POST", path: "/api/v1/ops/products/:id/images/:imageId/primary", access: "authenticated", permission: "ops:access" },
  { method: "POST", path: "/api/v1/ops/products/:id/videos", access: "authenticated", permission: "ops:access" },
  { method: "POST", path: "/api/v1/ops/products/:id/videos/upload", access: "authenticated", permission: "ops:access" },
  { method: "PATCH", path: "/api/v1/ops/products/:id/videos/:videoId", access: "authenticated", permission: "ops:access" },
  { method: "DELETE", path: "/api/v1/ops/products/:id/videos/:videoId", access: "authenticated", permission: "ops:access" },
  { method: "GET", path: "/api/v1/ops/categories", access: "authenticated", permission: "ops:access" },
  { method: "POST", path: "/api/v1/ops/categories", access: "authenticated", permission: "ops:access" },
  { method: "PATCH", path: "/api/v1/ops/categories/:id", access: "authenticated", permission: "ops:access" },
  { method: "POST", path: "/api/v1/ops/categories/:id/image/upload", access: "authenticated", permission: "ops:access" },
  { method: "GET", path: "/api/v1/ops/brands", access: "authenticated", permission: "ops:access" },
  { method: "POST", path: "/api/v1/ops/brands", access: "authenticated", permission: "ops:access" },
  { method: "GET", path: "/api/v1/ops/manufacturers", access: "authenticated", permission: "ops:access" },
  { method: "POST", path: "/api/v1/ops/manufacturers", access: "authenticated", permission: "ops:access" },
  { method: "GET", path: "/api/v1/ops/purchase-orders", access: "authenticated", permission: "ops:access" },
  { method: "POST", path: "/api/v1/ops/reports", access: "authenticated", permission: "ops:access" },
  { method: "GET", path: "/api/v1/announcements", access: "public" },
  { method: "GET", path: "/api/v1/announcements/:idOrSlug", access: "public" },
  { method: "GET", path: "/api/v1/announcements/:idOrSlug/replies", access: "public" },
  { method: "POST", path: "/api/v1/announcements/:idOrSlug/replies", access: "authenticated" },
  { method: "GET", path: "/api/v1/announcements/:idOrSlug/reactions", access: "public" },
  { method: "POST", path: "/api/v1/announcements/:idOrSlug/reactions", access: "authenticated" },
  { method: "DELETE", path: "/api/v1/announcements/:idOrSlug/reactions", access: "authenticated" },
  { method: "PATCH", path: "/api/v1/announcements/replies/:replyId", access: "authenticated", permission: "ops:access" },
  { method: "GET", path: "/api/v1/announcements/:id/media/:mediaId", access: "public" },
  { method: "GET", path: "/api/v1/announcements/admin", access: "authenticated", permission: "ops:access" },
  { method: "POST", path: "/api/v1/announcements", access: "authenticated", permission: "ops:access" },
  { method: "POST", path: "/api/v1/announcements/:id/media", access: "authenticated", permission: "ops:access" },
  { method: "PATCH", path: "/api/v1/announcements/:id", access: "authenticated", permission: "ops:access" },
  { method: "DELETE", path: "/api/v1/announcements/:id", access: "authenticated", permission: "ops:access" },
  { method: "DELETE", path: "/api/v1/announcements/:id/media/:mediaId", access: "authenticated", permission: "ops:access" },
  { method: "POST", path: "/api/v1/auth/register", access: "public" },
  { method: "POST", path: "/api/v1/auth/login", access: "public" },
  { method: "POST", path: "/api/v1/auth/refresh", access: "public" },
  { method: "POST", path: "/api/v1/auth/forgot-password", access: "public" },
  { method: "POST", path: "/api/v1/auth/reset-password", access: "public" },
  { method: "POST", path: "/api/v1/auth/verify-email", access: "public" },
  { method: "POST", path: "/api/v1/auth/verify-email/:token", access: "public" },
  { method: "POST", path: "/api/v1/auth/resend-verification", access: "public" },
  { method: "POST", path: "/api/v1/auth/otp/resend", access: "public" },
  { method: "POST", path: "/api/v1/auth/otp/verify", access: "public" },
  { method: "GET", path: "/api/v1/auth/google/status", access: "public" },
  { method: "POST", path: "/api/v1/auth/google", access: "public" },
  { method: "GET", path: "/api/v1/auth/google", access: "public" },
  { method: "GET", path: "/api/v1/auth/google/callback", access: "public" },
  { method: "GET", path: "/api/v1/auth/invitations/:token", access: "public" },
  { method: "POST", path: "/api/v1/auth/invitations/:token/accept", access: "public" },
  { method: "POST", path: "/api/v1/auth/invitations", access: "authenticated" },
  { method: "POST", path: "/api/v1/auth/logout", access: "authenticated" },
  { method: "POST", path: "/api/v1/auth/logout-everywhere", access: "authenticated" },
  { method: "GET", path: "/api/v1/auth/sessions", access: "authenticated" },
  { method: "DELETE", path: "/api/v1/auth/sessions/:sessionId", access: "authenticated" },
  { method: "GET", path: "/api/v1/auth/devices", access: "authenticated" },
  { method: "DELETE", path: "/api/v1/auth/devices/:deviceId", access: "authenticated" },
  { method: "GET", path: "/api/v1/auth/login-history", access: "authenticated" },
  { method: "GET", path: "/api/v1/auth/me", access: "authenticated" },
  { method: "PATCH", path: "/api/v1/auth/profile", access: "authenticated" },
  { method: "PATCH", path: "/api/v1/auth/password", access: "authenticated" },
  { method: "GET", path: "/api/v1/auth/validate", access: "authenticated" },
  {
    method: "GET",
    path: "/api/v1/procurement-requests",
    access: "authenticated",
    permission: "request:read",
  },
  {
    method: "POST",
    path: "/api/v1/procurement-requests",
    access: "authenticated",
    permission: "request:create",
  },
  {
    method: "GET",
    path: "/api/v1/procurement-requests/:requestId",
    access: "authenticated",
    permission: "request:read",
  },
  {
    method: "PATCH",
    path: "/api/v1/procurement-requests/:requestId",
    access: "authenticated",
    permission: "request:update",
  },
  {
    method: "POST",
    path: "/api/v1/procurement-requests/:requestId/transitions",
    access: "authenticated",
  },
  {
    method: "POST",
    path: "/api/v1/procurement-requests/:requestId/assignments",
    access: "authenticated",
    permission: "request:assign",
  },
  {
    method: "POST",
    path: "/api/v1/procurement-requests/:requestId/archive",
    access: "authenticated",
    permission: "request:archive",
  },
  {
    method: "POST",
    path: "/api/v1/procurement-requests/:requestId/restore",
    access: "authenticated",
    permission: "request:restore",
  },
  {
    method: "POST",
    path: "/api/v1/procurement-requests/:requestId/duplicate",
    access: "authenticated",
    permission: "request:duplicate",
  },
  {
    method: "POST",
    path: "/api/v1/documents",
    access: "authenticated",
    permission: "request:create",
  },
  {
    method: "GET",
    path: "/api/v1/documents/:documentId",
    access: "authenticated",
    permission: "request:read",
  },
  {
    method: "GET",
    path: "/api/v1/quotations",
    access: "authenticated",
    permission: "quotation:read",
  },
  {
    method: "POST",
    path: "/api/v1/quotations",
    access: "authenticated",
    permission: "quotation:create",
  },
  {
    method: "GET",
    path: "/api/v1/quotations/:quotationId",
    access: "authenticated",
    permission: "quotation:read",
  },
  {
    method: "PATCH",
    path: "/api/v1/quotations/:quotationId",
    access: "authenticated",
    permission: "quotation:update",
  },
  {
    method: "POST",
    path: "/api/v1/quotations/:quotationId/transitions",
    access: "authenticated",
  },
  {
    method: "POST",
    path: "/api/v1/quotations/:quotationId/revise",
    access: "authenticated",
    permission: "quotation:revise",
  },
  {
    method: "GET",
    path: "/api/v1/quotations/:quotationId/history",
    access: "authenticated",
    permission: "quotation:read",
  },
  {
    method: "GET",
    path: "/api/v1/invoices",
    access: "authenticated",
    permission: "invoice:read",
  },
  {
    method: "POST",
    path: "/api/v1/invoices",
    access: "authenticated",
    permission: "invoice:create",
  },
  {
    method: "GET",
    path: "/api/v1/invoices/:invoiceId",
    access: "authenticated",
    permission: "invoice:read",
  },
  {
    method: "PATCH",
    path: "/api/v1/invoices/:invoiceId",
    access: "authenticated",
    permission: "invoice:update",
  },
  {
    method: "POST",
    path: "/api/v1/invoices/:invoiceId/issue",
    access: "authenticated",
    permission: "invoice:issue",
  },
  {
    method: "POST",
    path: "/api/v1/invoices/:invoiceId/void",
    access: "authenticated",
    permission: "invoice:void",
  },
  {
    method: "GET",
    path: "/api/v1/invoices/:invoiceId/history",
    access: "authenticated",
    permission: "invoice:read",
  },
  {
    method: "GET",
    path: "/api/v1/payments",
    access: "authenticated",
    permission: "payment:read",
  },
  {
    method: "POST",
    path: "/api/v1/payments",
    access: "authenticated",
    permission: "payment:create",
  },
  {
    method: "GET",
    path: "/api/v1/payments/:paymentId",
    access: "authenticated",
    permission: "payment:read",
  },
  {
    method: "POST",
    path: "/api/v1/payments/:paymentId/submit",
    access: "authenticated",
    permission: "payment:submit",
  },
  {
    method: "POST",
    path: "/api/v1/payments/:paymentId/confirm",
    access: "authenticated",
    permission: "payment:confirm",
  },
  {
    method: "GET",
    path: "/api/v1/payments/:paymentId/history",
    access: "authenticated",
    permission: "payment:read",
  },
  { method: "GET", path: "/api/v1/shipments", access: "authenticated", permission: "shipment:read" },
  { method: "POST", path: "/api/v1/shipments", access: "authenticated", permission: "shipment:create" },
  { method: "GET", path: "/api/v1/shipments/:shipmentId", access: "authenticated", permission: "shipment:read" },
  { method: "PATCH", path: "/api/v1/shipments/:shipmentId", access: "authenticated", permission: "shipment:update" },
  { method: "POST", path: "/api/v1/shipments/:shipmentId/transitions", access: "authenticated", permission: "shipment:manage" },
  { method: "GET", path: "/api/v1/shipments/:shipmentId/timeline", access: "authenticated", permission: "shipment:read" },
  { method: "POST", path: "/api/v1/shipments/:shipmentId/milestones", access: "authenticated", permission: "shipment:update" },
  { method: "POST", path: "/api/v1/shipments/:shipmentId/containers", access: "authenticated", permission: "shipment:update" },
  { method: "POST", path: "/api/v1/shipments/:shipmentId/tracking", access: "authenticated", permission: "shipment:update" },
  { method: "POST", path: "/api/v1/shipments/:shipmentId/documents", access: "authenticated", permission: "shipment:update" },
  { method: "POST", path: "/api/v1/shipments/:shipmentId/evidence", access: "authenticated", permission: "shipment:update" },
  { method: "POST", path: "/api/v1/shipments/:shipmentId/inspections", access: "authenticated", permission: "shipment:update" },
  { method: "POST", path: "/api/v1/shipments/:shipmentId/confirm-delivery", access: "authenticated", permission: "shipment:confirm" },
  { method: "GET", path: "/api/v1/shipments/:shipmentId/history", access: "authenticated", permission: "shipment:read" },
  { method: "GET", path: "/api/v1/notifications", access: "authenticated", permission: "notification:read" },
  { method: "GET", path: "/api/v1/notifications/unread-count", access: "authenticated", permission: "notification:read" },
  { method: "GET", path: "/api/v1/notifications/:notificationId", access: "authenticated", permission: "notification:read" },
  { method: "POST", path: "/api/v1/notifications/read", access: "authenticated", permission: "notification:read" },
  { method: "POST", path: "/api/v1/notifications/read-all", access: "authenticated", permission: "notification:read" },
  { method: "POST", path: "/api/v1/notifications/:notificationId/unread", access: "authenticated", permission: "notification:read" },
  { method: "POST", path: "/api/v1/notifications/:notificationId/archive", access: "authenticated", permission: "notification:read" },
  { method: "POST", path: "/api/v1/notifications/:notificationId/unarchive", access: "authenticated", permission: "notification:read" },
  { method: "DELETE", path: "/api/v1/notifications/:notificationId", access: "authenticated", permission: "notification:read" },
  { method: "GET", path: "/api/v1/notification-preferences", access: "authenticated", permission: "notification:read" },
  { method: "PATCH", path: "/api/v1/notification-preferences", access: "authenticated", permission: "notification:read" },
  { method: "GET", path: "/api/v1/admin/communication/templates", access: "authenticated", permission: "communication:manage" },
  { method: "POST", path: "/api/v1/admin/communication/templates", access: "authenticated", permission: "communication:manage" },
  { method: "GET", path: "/api/v1/admin/communication/templates/:templateId", access: "authenticated", permission: "communication:manage" },
  { method: "POST", path: "/api/v1/admin/communication/templates/:templateId/revisions", access: "authenticated", permission: "communication:manage" },
  { method: "POST", path: "/api/v1/admin/communication/templates/:templateId/publish", access: "authenticated", permission: "communication:publish" },
  { method: "GET", path: "/api/v1/guidance/preferences", access: "authenticated", permission: "guidance:read" },
  { method: "PATCH", path: "/api/v1/guidance/preferences", access: "authenticated", permission: "guidance:read" },
  { method: "GET", path: "/api/v1/guidance/tours", access: "authenticated", permission: "guidance:read" },
  { method: "GET", path: "/api/v1/guidance/tips", access: "authenticated", permission: "guidance:read" },
  { method: "GET", path: "/api/v1/guidance/progress", access: "authenticated", permission: "guidance:read" },
  { method: "PUT", path: "/api/v1/guidance/progress", access: "authenticated", permission: "guidance:read" },
  { method: "GET", path: "/api/v1/guidance/tips/dismissed", access: "authenticated", permission: "guidance:read" },
  { method: "POST", path: "/api/v1/guidance/tips/dismiss", access: "authenticated", permission: "guidance:read" },
  { method: "POST", path: "/api/v1/guidance/progress/reset", access: "authenticated", permission: "guidance:read" },
  { method: "GET", path: "/api/v1/integrated-export/commodities", access: "public" },
  { method: "GET", path: "/api/v1/integrated-export/commodities/:slug", access: "public" },
  { method: "POST", path: "/api/v1/integrated-export/commodities", access: "authenticated", permission: "ops:access" },
  { method: "POST", path: "/api/v1/integrated-export/commodities/:id/hero", access: "authenticated", permission: "ops:access" },
  { method: "PATCH", path: "/api/v1/integrated-export/commodities/:id", access: "authenticated", permission: "ops:access" },
  { method: "DELETE", path: "/api/v1/integrated-export/commodities/:id", access: "authenticated", permission: "ops:access" },
  { method: "GET", path: "/api/v1/wedding/campaign", access: "public" },
  { method: "PATCH", path: "/api/v1/wedding/campaign", access: "authenticated", permission: "ops:access" },
  { method: "POST", path: "/api/v1/wedding/live/start", access: "authenticated", permission: "ops:access" },
  { method: "POST", path: "/api/v1/wedding/live/end", access: "authenticated", permission: "ops:access" },
  { method: "POST", path: "/api/v1/wedding/live/stop-feed", access: "authenticated", permission: "ops:access" },
  { method: "POST", path: "/api/v1/wedding/live/primary-feed", access: "authenticated", permission: "ops:access" },
  { method: "GET", path: "/api/v1/wedding/live/status", access: "authenticated" },
  { method: "POST", path: "/api/v1/wedding/live/token", access: "authenticated" },
  { method: "GET", path: "/api/v1/wedding/live/viewers", access: "authenticated", permission: "ops:access" },
  { method: "GET", path: "/api/v1/wedding/waiting-audio", access: "public" },
  { method: "POST", path: "/api/v1/wedding/waiting-audio", access: "authenticated", permission: "ops:access" },
  { method: "POST", path: "/api/v1/wedding/waiting-audio/reorder", access: "authenticated", permission: "ops:access" },
  { method: "PATCH", path: "/api/v1/wedding/waiting-audio/:id", access: "authenticated", permission: "ops:access" },
  { method: "DELETE", path: "/api/v1/wedding/waiting-audio/:id", access: "authenticated", permission: "ops:access" },
  { method: "POST", path: "/api/v1/wedding/waiting-audio/enabled", access: "authenticated", permission: "ops:access" },
  { method: "GET", path: "/api/v1/wedding/comments", access: "public" },
  { method: "POST", path: "/api/v1/wedding/comments", access: "authenticated" },
  { method: "POST", path: "/api/v1/wedding/comments/:id/hide", access: "authenticated", permission: "ops:access" },
  { method: "GET", path: "/api/v1/wedding/gallery", access: "public" },
  { method: "POST", path: "/api/v1/wedding/gallery", access: "authenticated", permission: "ops:access" },
  { method: "PATCH", path: "/api/v1/wedding/gallery/:id", access: "authenticated", permission: "ops:access" },
  { method: "DELETE", path: "/api/v1/wedding/gallery/:id", access: "authenticated", permission: "ops:access" },
  { method: "GET", path: "/api/v1/wedding/recording", access: "public" },
  { method: "GET", path: "/api/v1/wedding/recording/download", access: "authenticated" },
  { method: "POST", path: "/api/v1/wedding/test", access: "authenticated", permission: "ops:access" },
  { method: "GET", path: "/api/v1/admin/guidance/tours", access: "authenticated", permission: "guidance:manage" },
  { method: "POST", path: "/api/v1/admin/guidance/tours", access: "authenticated", permission: "guidance:manage" },
  { method: "PATCH", path: "/api/v1/admin/guidance/tours/:tourId", access: "authenticated", permission: "guidance:manage" },
  { method: "POST", path: "/api/v1/admin/guidance/tours/:tourId/publish", access: "authenticated", permission: "guidance:manage" },
  { method: "POST", path: "/api/v1/admin/guidance/tours/:tourId/unpublish", access: "authenticated", permission: "guidance:manage" },
  { method: "POST", path: "/api/v1/admin/guidance/tours/:tourId/schedule", access: "authenticated", permission: "guidance:manage" },
  { method: "GET", path: "/api/v1/admin/guidance/analytics", access: "authenticated", permission: "guidance:manage" },
  { method: "POST", path: "/api/v1/admin/guidance/users/:userId/reset-progress", access: "authenticated", permission: "guidance:manage" },
] as const satisfies readonly RoutePolicy[];

export function findRoutePolicy(
  method: string,
  path: string,
): RoutePolicy | undefined {
  return routePolicies.find(
    (policy) => policy.method === method.toUpperCase() && policy.path === path,
  );
}
