import type { ExecutiveDashboardData } from "./executive-types.js";
import type { DashboardWidgetLayoutState } from "./useDashboardLayout.js";

const hours = (h: number) =>
  new Date(Date.now() - h * 3_600_000).toISOString();

export const executiveLayoutDefaults: DashboardWidgetLayoutState[] = [
  { id: "exec-kpis", order: 0, collapsed: false, colSpan: 12, rowSpan: 1 },
  { id: "exec-approvals", order: 1, collapsed: false, colSpan: 6, rowSpan: 2 },
  { id: "exec-actions", order: 2, collapsed: false, colSpan: 6, rowSpan: 1 },
  { id: "exec-revenue", order: 3, collapsed: false, colSpan: 6, rowSpan: 2 },
  { id: "exec-pipeline", order: 4, collapsed: false, colSpan: 6, rowSpan: 2 },
  { id: "exec-requests", order: 5, collapsed: false, colSpan: 6, rowSpan: 2 },
  { id: "exec-suppliers", order: 6, collapsed: false, colSpan: 6, rowSpan: 2 },
  { id: "exec-finance", order: 7, collapsed: false, colSpan: 6, rowSpan: 2 },
  { id: "exec-shipments", order: 8, collapsed: false, colSpan: 6, rowSpan: 2 },
  { id: "exec-inventory", order: 9, collapsed: false, colSpan: 4, rowSpan: 1 },
  { id: "exec-customers", order: 10, collapsed: false, colSpan: 4, rowSpan: 2 },
  { id: "exec-notifications", order: 11, collapsed: false, colSpan: 4, rowSpan: 2 },
  { id: "exec-health", order: 12, collapsed: false, colSpan: 6, rowSpan: 1 },
  { id: "exec-ai", order: 13, collapsed: false, colSpan: 6, rowSpan: 2 },
  { id: "exec-audit", order: 14, collapsed: false, colSpan: 8, rowSpan: 2 },
  { id: "exec-heatmap", order: 15, collapsed: false, colSpan: 4, rowSpan: 2 },
];

export const executiveDashboardFixture: ExecutiveDashboardData = {
  kpis: [
    {
      id: "kpi-revenue",
      label: "Revenue (30d)",
      value: "$2.4M",
      delta: "+8.2%",
      tone: "positive",
      definition: "Recognized + booked invoice totals in scope",
      timeRange: "Last 30 days",
      freshness: "Updated 12m ago",
      trend: [
        { label: "W1", value: 480 },
        { label: "W2", value: 520 },
        { label: "W3", value: 610 },
        { label: "W4", value: 690 },
      ],
      href: "/finance/revenue",
    },
    {
      id: "kpi-pipeline",
      label: "Open pipeline",
      value: "$6.1M",
      delta: "+3.1%",
      tone: "positive",
      definition: "Active PR → RFQ → Quotation value",
      timeRange: "Current",
      freshness: "Live",
      href: "/procurement/pipeline",
    },
    {
      id: "kpi-otif",
      label: "OTIF",
      value: "94.2%",
      delta: "-1.1%",
      tone: "warning",
      definition: "On-time in-full deliveries",
      timeRange: "Last 90 days",
      freshness: "Updated 1h ago",
      href: "/logistics/otif",
    },
    {
      id: "kpi-approvals",
      label: "Pending approvals",
      value: 7,
      delta: "+2",
      tone: "warning",
      definition: "Approvals waiting on your roles",
      timeRange: "Now",
      freshness: "Live",
      href: "/approvals",
    },
  ],
  revenueSeries: [
    { label: "Jan", value: 180 },
    { label: "Feb", value: 210 },
    { label: "Mar", value: 195 },
    { label: "Apr", value: 240 },
    { label: "May", value: 260 },
    { label: "Jun", value: 290 },
  ],
  pipeline: [
    { id: "draft", label: "Draft", count: 12, amount: "$420k" },
    { id: "rfq", label: "RFQ", count: 18, amount: "$1.1M" },
    { id: "quote", label: "Quotation", count: 9, amount: "$2.4M" },
    { id: "po", label: "PO", count: 14, amount: "$1.8M" },
    { id: "ship", label: "In transit", count: 6, amount: "$980k" },
  ],
  pendingApprovals: [
    {
      id: "ap1",
      title: "Approve PO-551",
      detail: "USD 44,500 · Ningbo Precision Valves",
      urgency: "high",
      href: "/orders/po-551",
      kind: "approval",
    },
    {
      id: "ap2",
      title: "Payment release INV-4401",
      detail: "USD 12,200 due in 3 days",
      urgency: "urgent",
      href: "/payments/p-4401",
      kind: "payment",
    },
    {
      id: "ap3",
      title: "Supplier certificate renewal",
      detail: "SUP-VALVE-CO ISO expires in 14 days",
      urgency: "normal",
      href: "/suppliers/sup-valve-co",
      kind: "approval",
    },
  ],
  recentRequests: [
    {
      id: "pr-1042",
      publicCode: "PR-1042",
      title: "Gate valves DN50 set",
      status: "sourcing",
      priority: "high",
      budgetAmount: "45000",
      currencyCode: "USD",
      updatedAt: hours(2),
      href: "/requests/pr-1042",
    },
    {
      id: "pr-1038",
      publicCode: "PR-1038",
      title: "Industrial solvents",
      status: "quoted",
      priority: "normal",
      updatedAt: hours(8),
      href: "/requests/pr-1038",
    },
  ],
  supplierPerformance: [
    {
      id: "s1",
      name: "Ningbo Precision Valves",
      otif: 96,
      quality: 98,
      onTimeRate: 95,
      href: "/suppliers/sup-valve-co",
    },
    {
      id: "s2",
      name: "Gulf Specialty Chemicals",
      otif: 91,
      quality: 94,
      onTimeRate: 90,
      href: "/suppliers/sup-gulf",
    },
    {
      id: "s3",
      name: "Lagos Pack Systems",
      otif: 88,
      quality: 92,
      onTimeRate: 86,
      href: "/suppliers/sup-lagos",
    },
  ],
  financialSummary: [
    { id: "ar", label: "Accounts receivable", amount: "$820k", tone: "neutral" },
    { id: "overdue", label: "Overdue invoices", amount: "$64k", tone: "danger" },
    { id: "paid", label: "Collected (30d)", amount: "$1.1M", tone: "positive" },
    { id: "pending", label: "Pending release", amount: "$210k", tone: "warning" },
  ],
  shipmentStatus: [
    { id: "planned", label: "Planned", count: 4 },
    { id: "transit", label: "In transit", count: 11 },
    { id: "ofd", label: "Out for delivery", count: 3 },
    { id: "held", label: "Held", count: 2 },
    { id: "delivered", label: "Delivered (30d)", count: 28 },
  ],
  inventory: {
    ready: false,
    note: "Inventory snapshot is future-ready - bind warehouse stock when the module ships.",
  },
  customerActivity: [
    {
      id: "ca1",
      organizationName: "West Africa Energy Ltd",
      event: "Submitted PR-1042",
      at: hours(3),
      href: "/organizations/org-wae",
    },
    {
      id: "ca2",
      organizationName: "Harbor Foods PLC",
      event: "Accepted QT-910",
      at: hours(9),
      href: "/organizations/org-harbor",
    },
  ],
  notifications: [
    {
      id: "n1",
      type: "shipment",
      priority: "high",
      status: "unread",
      title: "SH-770 exception",
      body: "Held at customs - document mismatch",
      createdAt: hours(1),
      deepLink: "/shipments/sh-770",
    },
    {
      id: "n2",
      type: "payment",
      priority: "normal",
      status: "unread",
      title: "Payment received INV-4390",
      body: "TT confirmed",
      createdAt: hours(5),
    },
  ],
  systemHealth: [
    { id: "api", service: "API", status: "healthy", latencyMs: 48 },
    { id: "db", service: "Database", status: "healthy", latencyMs: 12 },
    { id: "redis", service: "Cache", status: "healthy", latencyMs: 3 },
    {
      id: "workers",
      service: "Notification workers",
      status: "degraded",
      latencyMs: 320,
      detail: "Queue depth elevated",
    },
  ],
  aiInsights: [
    {
      id: "ai1",
      title: "Budget risk on PR-1042",
      summary:
        "Similar valve sets closed 12% above current target. Review freight assumptions.",
      confidence: "moderate",
      href: "/assistant?focus=budget_suggestion",
    },
    {
      id: "ai2",
      title: "Supplier shortlist ready",
      summary: "Two qualified suppliers match DN50 specs with certificates on file.",
      confidence: "high",
      href: "/assistant?focus=supplier_suggestion",
    },
  ],
  quickActions: [
    {
      id: "qa1",
      label: "Review approvals",
      href: "/approvals",
      primary: true,
      badge: 7,
    },
    { id: "qa2", label: "Open pipeline", href: "/procurement/pipeline" },
    { id: "qa3", label: "System health", href: "/admin/health" },
    { id: "qa4", label: "AI assistant", href: "/assistant" },
  ],
  auditEvents: [
    {
      id: "au1",
      action: "purchase_order.approved",
      actor: "Ada Okonkwo",
      target: "PO-300",
      at: hours(4),
      href: "/orders/po-300",
    },
    {
      id: "au2",
      action: "role.permission_updated",
      actor: "Leo Mensah",
      target: "ops_manager",
      at: hours(10),
    },
    {
      id: "au3",
      action: "shipment.held",
      actor: "System",
      target: "SH-440",
      at: hours(26),
      href: "/shipments/sh-440",
    },
  ],
  procurementVolume: [
    { label: "Mon", value: 14 },
    { label: "Tue", value: 18 },
    { label: "Wed", value: 12 },
    { label: "Thu", value: 22 },
    { label: "Fri", value: 19 },
    { label: "Sat", value: 6 },
    { label: "Sun", value: 4 },
  ],
  cashCollection: [
    { label: "W1", value: 210 },
    { label: "W2", value: 180 },
    { label: "W3", value: 260 },
    { label: "W4", value: 290 },
  ],
};
