import type { ClientDashboardData } from "./ClientDashboard.js";

/** Demo / Storybook fixture - API-aligned field names. */
export const dashboardFixture: ClientDashboardData = {
  greeting: "Good afternoon, Ada",
  subtitle: "Your procurement corridor at a glance.",
  stats: [
    { id: "open", label: "Open requests", value: 12, delta: "+2 this week", tone: "neutral", href: "/requests?status=open" },
    { id: "quotes", label: "Quotes awaiting review", value: 3, tone: "warning", href: "/quotations?status=issued" },
    { id: "due", label: "Payments due", value: 1, tone: "danger", href: "/payments" },
    { id: "ships", label: "Shipments in transit", value: 4, tone: "positive", href: "/shipments" },
  ],
  quickActions: [
    { id: "new-request", label: "New procurement request", href: "/requests/new", primary: true },
    { id: "messages", label: "Messages", description: "2 unread", href: "/messages", badge: 2 },
    { id: "documents", label: "Documents", href: "/documents" },
    { id: "profile", label: "Profile & company", href: "/profile" },
  ],
  attention: [
    {
      id: "att-1",
      title: "Clarify destination for PR-1042",
      detail: "Ops needs a delivery address before sourcing can continue.",
      urgency: "high",
      href: "/requests/pr-1042",
      kind: "clarification",
    },
    {
      id: "att-2",
      title: "Review quote QT-889",
      detail: "Expires in 48 hours · USD 42,500",
      urgency: "urgent",
      href: "/quotations/qt-889",
      kind: "quote",
    },
  ],
  recentRequests: [
    {
      id: "r1",
      publicCode: "PR-1042",
      title: "Industrial valves - Lagos",
      status: "needs_clarification",
      priority: "high",
      budgetAmount: "18,000",
      currencyCode: "USD",
      updatedAt: "2026-07-30T10:00:00Z",
      href: "/requests/pr-1042",
    },
    {
      id: "r2",
      publicCode: "PR-1038",
      title: "Lab reagents kit",
      status: "sourcing",
      priority: "normal",
      budgetAmount: "6,400",
      currencyCode: "USD",
      updatedAt: "2026-07-28T10:00:00Z",
      href: "/requests/pr-1038",
    },
    {
      id: "r3",
      publicCode: "PR-1031",
      title: "HVAC compressors",
      status: "quote_issued",
      priority: "urgent",
      budgetAmount: "42,500",
      currencyCode: "USD",
      updatedAt: "2026-07-27T10:00:00Z",
      href: "/requests/pr-1031",
    },
  ],
  activeRfqs: [
    {
      id: "rfq1",
      publicCode: "RFQ-220",
      title: "Stainless fittings",
      status: "open",
      supplierCount: 5,
      closesAt: "2026-08-05T00:00:00Z",
      href: "/rfqs/rfq-220",
    },
  ],
  quotations: [
    {
      id: "q1",
      publicCode: "QT-889",
      requestCode: "PR-1031",
      status: "issued",
      totalAmount: "42,500",
      currencyCode: "USD",
      expiresAt: "2026-08-03T00:00:00Z",
      href: "/quotations/qt-889",
    },
  ],
  orders: [
    {
      id: "o1",
      publicCode: "PO-551",
      status: "confirmed",
      totalAmount: "12,200",
      currencyCode: "USD",
      updatedAt: "2026-07-20T00:00:00Z",
      href: "/orders/po-551",
    },
  ],
  shipments: [
    {
      id: "s1",
      publicCode: "SH-901",
      status: "in_transit",
      carrierName: "Maersk",
      trackingNumber: "MSKU1234567",
      estimatedArrivalAt: "2026-08-12T00:00:00Z",
      href: "/shipments/sh-901",
    },
  ],
  invoices: [
    {
      id: "i1",
      invoiceNumber: "INV-4401",
      status: "issued",
      totalAmount: "12,200",
      currencyCode: "USD",
      dueAt: "2026-08-15T00:00:00Z",
      href: "/invoices/inv-4401",
    },
  ],
  payments: [
    {
      id: "p1",
      status: "pending_confirmation",
      amount: "12,200",
      currencyCode: "USD",
      reference: "TT-77881",
      updatedAt: "2026-07-29T00:00:00Z",
      href: "/payments/p1",
    },
  ],
  notifications: [
    {
      id: "n1",
      type: "procurement",
      priority: "high",
      status: "unread",
      title: "Clarification requested",
      body: "PR-1042 needs destination details.",
      deepLink: "/requests/pr-1042",
      createdAt: "2026-07-30T09:00:00Z",
    },
    {
      id: "n2",
      type: "quotation",
      priority: "normal",
      status: "read",
      title: "Quote issued",
      body: "QT-889 is ready for review.",
      deepLink: "/quotations/qt-889",
      createdAt: "2026-07-27T12:00:00Z",
    },
  ],
  messages: [
    {
      id: "m1",
      subject: "PR-1042 · Destination",
      preview: "Please confirm the Lagos warehouse address…",
      unreadCount: 2,
      updatedAt: "2026-07-30T11:00:00Z",
      href: "/messages/m1",
    },
  ],
  documents: [
    {
      id: "d1",
      name: "QT-889.pdf",
      kind: "quotation",
      updatedAt: "2026-07-27T12:00:00Z",
      href: "/documents/d1",
    },
  ],
  bookmarks: [
    { id: "b1", label: "Industrial valves", kind: "product", href: "/products/valves" },
    { id: "b2", label: "PR-1038", kind: "request", href: "/requests/pr-1038" },
  ],
  recentlyViewed: [
    {
      id: "pv1",
      name: "Ball valve DN50",
      category: "Valves",
      href: "/products/ball-valve-dn50",
      viewedAt: "2026-07-30T08:00:00Z",
    },
  ],
  recommendations: [
    {
      id: "rec1",
      title: "Complete company profile",
      reason: "Faster quote turnaround when destination defaults are set.",
      href: "/profile",
    },
    {
      id: "rec2",
      title: "Review expiring quote",
      reason: "QT-889 expires in 48 hours.",
      href: "/quotations/qt-889",
    },
  ],
};
