import type { RecommendationItem } from "./types.js";

const hoursAgo = (hours: number) =>
  new Date(Date.now() - hours * 3_600_000).toISOString();

/** One or more explainable examples for every mission recommendation kind. */
export const recommendationFixture: RecommendationItem[] = [
  {
    id: "rec-product-1",
    kind: "products",
    entityType: "product",
    entityId: "prod-gate-dn50",
    title: "Gate valve DN50 PN16",
    summary: "Ductile iron isolation valve matching the active request.",
    href: "/products/gate-valve-dn50",
    reason: "Matches requested diameter, pressure class, and material.",
    confidence: "high",
    confidenceReason: "3 of 3 required technical attributes match.",
    badges: ["Verified specs", "Available to source"],
    categoryName: "Industrial valves",
    leadTime: "10–14 days",
    rank: 1,
    evidence: [{ id: "ev-pr", label: "PR-1042", href: "/requests/pr-1042" }],
  },
  {
    id: "rec-supplier-1",
    kind: "suppliers",
    entityType: "supplier",
    entityId: "sup-west-valves",
    title: "West Africa Valves Ltd.",
    summary: "Approved supplier with current certificates and prior OTIF history.",
    href: "/suppliers/west-africa-valves",
    reason: "Qualified for this category and delivery corridor.",
    confidence: "moderate",
    confidenceReason: "Capability verified; current production capacity pending.",
    badges: ["Approved", "Certificates current"],
    categoryName: "Industrial valves",
    rank: 1,
  },
  {
    id: "rec-category-1",
    kind: "categories",
    entityType: "category",
    entityId: "cat-flow-control",
    title: "Flow control equipment",
    summary: "Valves, actuators, fittings, and compatible accessories.",
    href: "/catalog/flow-control",
    reason: "Derived from recent specification and search intent.",
    confidence: "high",
    badges: ["128 products"],
    rank: 1,
  },
  {
    id: "rec-bundle-1",
    kind: "frequently_purchased_together",
    entityType: "bundle",
    entityId: "bundle-valve-install",
    title: "Valve installation essentials",
    summary: "Gate valve, matching flange kit, gasket set, and fasteners.",
    href: "/catalog?bundle=valve-install",
    reason:
      "Organization-safe aggregate: compatible accessories commonly sourced together.",
    confidence: "moderate",
    confidenceReason: "Based on anonymized aggregate relationships, not another buyer.",
    productIds: ["prod-gate-dn50", "prod-flange-dn50", "prod-gasket-dn50"],
    badges: ["Compatibility check required", "3 items"],
    rank: 1,
  },
  {
    id: "rec-recent-1",
    kind: "recently_viewed",
    entityType: "product",
    entityId: "prod-ball-dn50",
    title: "Ball valve DN50 PN16",
    href: "/products/ball-valve-dn50",
    reason: "Viewed in this consented workspace session.",
    confidence: "high",
    viewedAt: hoursAgo(2),
    badges: ["Recently viewed"],
    categoryName: "Industrial valves",
    rank: 1,
  },
  {
    id: "rec-trending-1",
    kind: "trending",
    entityType: "product",
    entityId: "prod-safety-gloves",
    title: "Cut-resistant safety gloves",
    href: "/products/cut-resistant-gloves",
    reason: "Public-safe request growth in industrial PPE over the last 30 days.",
    confidence: "moderate",
    badges: ["Trending", "Aggregate data"],
    categoryName: "Safety equipment",
    rank: 1,
  },
  {
    id: "rec-seasonal-1",
    kind: "seasonal",
    entityType: "category",
    entityId: "cat-rain-protection",
    title: "Rain-season site protection",
    href: "/catalog/rain-season-protection",
    reason: "Seasonal planning window for West African outdoor operations.",
    confidence: "moderate",
    confidenceReason: "Calendar signal only; validate site and delivery dates.",
    seasonalWindow: "May–October",
    badges: ["Seasonal", "Planning guidance"],
    rank: 1,
  },
];
