import type { CmsContentRecord, CmsMediaAsset } from "./types.js";

const hours = (h: number) =>
  new Date(Date.now() - h * 3_600_000).toISOString();
const futureHours = (h: number) =>
  new Date(Date.now() + h * 3_600_000).toISOString();

export const cmsMediaFixture: CmsMediaAsset[] = [
  {
    id: "media-1",
    name: "hero-lagos-port.jpg",
    mimeType: "image/jpeg",
    href: "#",
    altText: "Lagos port corridor at dusk",
    width: 1920,
    height: 1080,
    rights: "Owned",
    scanStatus: "clean",
    uploadedAt: hours(40),
    usageCount: 2,
  },
  {
    id: "media-2",
    name: "wedding-celebration-banner.webp",
    mimeType: "image/webp",
    href: "#",
    altText: "Celebration banner artwork",
    width: 1600,
    height: 600,
    rights: "Licensed",
    scanStatus: "clean",
    uploadedAt: hours(12),
    usageCount: 1,
  },
  {
    id: "media-3",
    name: "iso-certificate-sample.pdf",
    mimeType: "application/pdf",
    href: "#",
    rights: "Supplier consent",
    scanStatus: "pending",
    uploadedAt: hours(6),
    usageCount: 0,
  },
];

export const cmsContentFixture: CmsContentRecord[] = [
  {
    id: "cms-hero-1",
    type: "homepage_hero",
    slug: "homepage-hero-en",
    title: "Primary homepage hero",
    summary: "Brand-first hero for procurement marketplace.",
    body: "Source industrial goods with confidence across corridors.",
    status: "published",
    locale: "en",
    rowVersion: 5,
    versionNumber: 3,
    authorName: "Ada Okonkwo",
    updatedAt: hours(8),
    publishedAt: hours(24),
    seo: {
      title: "Almahbub International - Procurement",
      description: "Enterprise procurement marketplace",
      robots: "index,follow",
    },
    mediaIds: ["media-1"],
    versions: [
      {
        id: "v1",
        versionNumber: 1,
        status: "superseded",
        authorName: "Ada Okonkwo",
        createdAt: hours(200),
      },
      {
        id: "v2",
        versionNumber: 2,
        status: "superseded",
        authorName: "Leo Mensah",
        createdAt: hours(80),
      },
      {
        id: "v3",
        versionNumber: 3,
        status: "published",
        authorName: "Ada Okonkwo",
        createdAt: hours(24),
        publishedAt: hours(24),
        current: true,
        summary: "Updated CTA copy",
      },
    ],
    fields: { ctaLabel: "Start sourcing", layout: "full-bleed" },
  },
  {
    id: "cms-section-1",
    type: "homepage_section",
    slug: "trust-services",
    title: "Trust & services band",
    summary: "Homepage section composition order slot 2",
    status: "draft",
    locale: "en",
    rowVersion: 1,
    versionNumber: 1,
    authorName: "James Nwosu",
    updatedAt: hours(3),
    seo: {},
    versions: [
      {
        id: "vs1",
        versionNumber: 1,
        status: "draft",
        authorName: "James Nwosu",
        createdAt: hours(3),
        current: true,
      },
    ],
  },
  {
    id: "cms-service-1",
    type: "service",
    slug: "sourcing-advisory",
    title: "Sourcing advisory",
    status: "in_review",
    locale: "en",
    rowVersion: 2,
    versionNumber: 1,
    authorName: "Ada Okonkwo",
    updatedAt: hours(5),
    seo: { title: "Sourcing advisory" },
    versions: [
      {
        id: "svc1",
        versionNumber: 1,
        status: "in_review",
        createdAt: hours(5),
        current: true,
      },
    ],
  },
  {
    id: "cms-industry-1",
    type: "industry",
    slug: "oil-gas",
    title: "Oil & gas",
    status: "published",
    locale: "en",
    rowVersion: 3,
    versionNumber: 2,
    updatedAt: hours(48),
    publishedAt: hours(48),
    seo: {},
    versions: [
      {
        id: "ind1",
        versionNumber: 2,
        status: "published",
        createdAt: hours(48),
        current: true,
        publishedAt: hours(48),
      },
    ],
  },
  {
    id: "cms-cat-1",
    type: "product_category",
    slug: "industrial-valves-landing",
    title: "Industrial valves landing",
    summary: "CMS composition only - catalog owns product truth",
    status: "approved",
    locale: "en",
    rowVersion: 1,
    versionNumber: 1,
    updatedAt: hours(10),
    seo: {},
    versions: [
      {
        id: "cat1",
        versionNumber: 1,
        status: "approved",
        createdAt: hours(10),
        current: true,
      },
    ],
  },
  {
    id: "cms-faq-1",
    type: "faq",
    slug: "how-rfq-works",
    title: "How does an RFQ work?",
    body: "Submit a request, invite suppliers, compare quotations, and issue a PO.",
    status: "published",
    locale: "en",
    rowVersion: 2,
    versionNumber: 1,
    updatedAt: hours(72),
    publishedAt: hours(72),
    seo: {},
    versions: [
      {
        id: "faq1",
        versionNumber: 1,
        status: "published",
        createdAt: hours(72),
        current: true,
        publishedAt: hours(72),
      },
    ],
  },
  {
    id: "cms-testimonial-1",
    type: "testimonial",
    slug: "wae-testimonial",
    title: "West Africa Energy",
    body: "Corridor visibility cut our sourcing cycle in half.",
    status: "published",
    locale: "en",
    rowVersion: 1,
    versionNumber: 1,
    updatedAt: hours(96),
    publishedAt: hours(96),
    seo: {},
    versions: [
      {
        id: "t1",
        versionNumber: 1,
        status: "published",
        createdAt: hours(96),
        current: true,
      },
    ],
    fields: { attribution: "Head of Procurement", consent: true },
  },
  {
    id: "cms-announce-1",
    type: "announcement",
    slug: "maintenance-window",
    title: "Scheduled maintenance",
    body: "Workspace unavailable Sunday 02:00–04:00 UTC.",
    status: "scheduled",
    locale: "en",
    rowVersion: 2,
    versionNumber: 1,
    updatedAt: hours(2),
    scheduledFor: futureHours(36),
    seo: {},
    versions: [
      {
        id: "a1",
        versionNumber: 1,
        status: "scheduled",
        createdAt: hours(2),
        current: true,
      },
    ],
  },
  {
    id: "cms-news-1",
    type: "news",
    slug: "corridor-expansion-2026",
    title: "Corridor expansion update",
    status: "draft",
    locale: "en",
    rowVersion: 1,
    versionNumber: 1,
    updatedAt: hours(1),
    seo: { title: "Corridor expansion" },
    versions: [
      {
        id: "n1",
        versionNumber: 1,
        status: "draft",
        createdAt: hours(1),
        current: true,
      },
    ],
  },
  {
    id: "cms-career-1",
    type: "career_post",
    slug: "ops-analyst-lagos",
    title: "Operations analyst - Lagos",
    status: "in_review",
    locale: "en",
    rowVersion: 1,
    versionNumber: 1,
    updatedAt: hours(7),
    seo: {},
    versions: [
      {
        id: "c1",
        versionNumber: 1,
        status: "in_review",
        createdAt: hours(7),
        current: true,
      },
    ],
  },
  {
    id: "cms-wedding-1",
    type: "wedding_banner",
    slug: "celebration-banner-q3",
    title: "Q3 celebration banner",
    status: "draft",
    locale: "en",
    rowVersion: 1,
    versionNumber: 1,
    updatedAt: hours(4),
    mediaIds: ["media-2"],
    seo: {},
    versions: [
      {
        id: "w1",
        versionNumber: 1,
        status: "draft",
        createdAt: hours(4),
        current: true,
      },
    ],
  },
  {
    id: "cms-notice-1",
    type: "global_notice",
    slug: "cookie-consent-notice",
    title: "Global cookie notice",
    status: "published",
    locale: "en",
    rowVersion: 1,
    versionNumber: 1,
    updatedAt: hours(120),
    publishedAt: hours(120),
    seo: {},
    versions: [
      {
        id: "gn1",
        versionNumber: 1,
        status: "published",
        createdAt: hours(120),
        current: true,
      },
    ],
  },
  {
    id: "cms-seo-1",
    type: "seo_metadata",
    slug: "seo-homepage",
    title: "Homepage SEO defaults",
    status: "published",
    locale: "en",
    rowVersion: 2,
    versionNumber: 2,
    updatedAt: hours(30),
    publishedAt: hours(30),
    seo: {
      title: "Almahbub International",
      description: "Enterprise procurement",
      canonicalUrl: "https://example.com/",
      robots: "index,follow",
      structuredDataType: "Organization",
    },
    versions: [
      {
        id: "seo1",
        versionNumber: 2,
        status: "published",
        createdAt: hours(30),
        current: true,
      },
    ],
  },
  {
    id: "cms-footer-1",
    type: "footer",
    slug: "global-footer-en",
    title: "Global footer",
    status: "published",
    locale: "en",
    rowVersion: 4,
    versionNumber: 2,
    updatedAt: hours(50),
    publishedAt: hours(50),
    seo: {},
    versions: [
      {
        id: "f1",
        versionNumber: 2,
        status: "published",
        createdAt: hours(50),
        current: true,
        summary: "Updated careers link",
      },
    ],
    fields: {
      columns: ["Company", "Platform", "Support"],
    },
  },
  {
    id: "cms-archived-1",
    type: "announcement",
    slug: "old-promo",
    title: "Archived promo",
    status: "archived",
    locale: "en",
    rowVersion: 3,
    versionNumber: 1,
    updatedAt: hours(400),
    seo: {},
    versions: [
      {
        id: "ar1",
        versionNumber: 1,
        status: "archived",
        createdAt: hours(400),
        current: true,
      },
    ],
  },
];
