"""Create Web presentation derivatives; retain all source artwork unchanged."""
import json
from pathlib import Path
from PIL import Image, ImageDraw, ImageOps

ROOT = Path(__file__).resolve().parents[1]
PUBLIC = ROOT / 'apps/web/public'
plan = json.loads((ROOT / 'catalogue-package/category-media-plan.json').read_text())
previous_inventory = json.loads((ROOT / 'docs/presentation-media-inventory.json').read_text())['rows']
rows = []
for item in plan:
    sources = list((ROOT / 'apps/api/uploads/public/catalog' / item['categoryId']).glob('*' + Path(item['filename']).stem + '.png'))
    if len(sources) != 1:
        raise RuntimeError(f"Expected exactly one approved local source for {item['categorySlug']}")
    rows.append(dict(business='International', slug=item['categorySlug'], name=item['categoryName'], alt=item['altText'], source=sources[0], target=PUBLIC / f"media/presentation/v2/international/{item['categorySlug']}.webp"))
for slug in ['sesame-seeds', 'cashew', 'ginger', 'hibiscus', 'shea', 'soybean', 'cocoa']:
    rows.append(dict(business='IE', slug=slug, name=slug.replace('-', ' ').title(), source=PUBLIC / f'media/ie/commodities/{slug}/hero/ie-{slug}-hero-01.webp', target=PUBLIC / f'media/presentation/v2/ie/{slug}.webp'))
for row in rows:
    source, target = row.pop('source'), row.pop('target')
    with Image.open(source) as original:
        image = ImageOps.exif_transpose(original).convert('RGB')
        row['beforeDimensions'] = list(image.size)
        row['beforeFormat'] = original.format
        image.thumbnail((960, 960), Image.Resampling.LANCZOS)
        target.parent.mkdir(parents=True, exist_ok=True)
        image.save(target, 'WEBP', quality=82, method=6)
        row['dimensions'] = list(image.size)
    row.update(source=str(source.relative_to(ROOT)).replace('\\', '/'), canonical='/' + str(target.relative_to(PUBLIC)).replace('\\', '/'), beforeBytes=source.stat().st_size, afterBytes=target.stat().st_size, format='WebP')
    previous = next(item for item in previous_inventory if item['slug'] == row['slug'])
    row.update(previousStatic=previous['staticAsset'], previousStaticBytes=(PUBLIC / previous['staticAsset'].lstrip('/')).stat().st_size, preferredLocalUrlCandidates=previous.get('observedLocalUrlCandidates', []), productionSourceVerified=False)
(ROOT / 'docs/canonical-presentation-assets.json').write_text(json.dumps(rows, indent=2) + '\n')
content = [{'slug': row['slug'], 'name': row['name'], 'src': row['canonical'], 'alt': row.get('alt', row['name']), 'business': row['business']} for row in rows]
(ROOT / 'apps/web/src/content/canonical-presentation.ts').write_text('// Curated presentation taxonomy, not a snapshot of stock or publication status.\n// Generated by scripts/optimize-canonical-presentation.py from the approved artwork.\nexport const CANONICAL_PRESENTATION = ' + json.dumps(content, indent=2) + ' as const;\n')
sheet = Image.new('RGB', (1000, 250 * 6), 'white')
draw = ImageDraw.Draw(sheet)
for i, row in enumerate(rows):
    with Image.open(PUBLIC / row['canonical'].lstrip('/')) as image:
        image.thumbnail((320, 210))
        x, y = (i % 3) * 333, (i // 3) * 250
        sheet.paste(image, (x, y))
        draw.text((x + 4, y + 215), row['slug'], fill='black')
output = ROOT / 'apps/web/commerce-test-results'
output.mkdir(exist_ok=True)
sheet.save(output / 'canonical-contact-sheet.jpg')
print(json.dumps({'assets': len(rows), 'beforeBytes': sum(r['beforeBytes'] for r in rows), 'afterBytes': sum(r['afterBytes'] for r in rows)}))
