import type { PurchaseOrderRecord } from "./types.js";

const hours = (h: number) =>
  new Date(Date.now() - h * 3_600_000).toISOString();
const days = (d: number) =>
  new Date(Date.now() - d * 86_400_000).toISOString();
const futureDays = (d: number) =>
  new Date(Date.now() + d * 86_400_000).toISOString();

export const purchaseOrderRecordsFixture: PurchaseOrderRecord[] = [
  {
    id: "po-551",
    publicCode: "PO-551",
    status: "issued",
    currencyCode: "USD",
    totalAmount: 44_500,
    rowVersion: 3,
    procurementRequestId: "pr-1042",
    procurementRequestCode: "PR-1042",
    quotationId: "qt-889-v2",
    quotationCode: "QT-889",
    supplierId: "sup-valve-co",
    supplierName: "Ningbo Precision Valves Co., Ltd",
    supplierAcceptance: "pending",
    versionNumber: 1,
    createdAt: hours(40),
    updatedAt: hours(18),
    items: [
      {
        id: "poi1",
        description: "Gate valve DN50 PN16",
        quantity: 120,
        unitAmount: 90,
        lineAmount: 10_800,
      },
      {
        id: "poi2",
        description: "Ball valve DN80",
        quantity: 40,
        unitAmount: 155,
        lineAmount: 6_200,
      },
    ],
    documents: [
      {
        id: "pod1",
        name: "PO-551.pdf",
        href: "#",
        kind: "purchase_order",
        uploadedAt: hours(18),
      },
    ],
    attachments: [
      {
        id: "poa1",
        name: "packing-instructions.pdf",
        href: "#",
        kind: "instruction",
        uploadedAt: hours(16),
      },
    ],
    history: [
      {
        id: "poh1",
        toStatus: "draft",
        command: "create",
        actorName: "System",
        createdAt: hours(40),
      },
      {
        id: "poh2",
        fromStatus: "draft",
        toStatus: "issued",
        command: "issue",
        actorName: "Ada Okonkwo",
        createdAt: hours(18),
      },
    ],
    revisions: [
      {
        id: "po-551",
        versionNumber: 1,
        publicCode: "PO-551",
        status: "issued",
        totalAmount: 44_500,
        createdAt: hours(40),
        current: true,
      },
    ],
    deliveries: [
      {
        shipmentId: "sh-901",
        publicCode: "SH-901",
        status: "planned",
        carrierName: "Maersk",
        trackingNumber: null,
        estimatedArrivalAt: futureDays(18),
        href: "/shipments/sh-901",
        milestones: [
          {
            id: "m1",
            label: "PO confirmed",
            status: "confirmed",
            occurredAt: hours(17),
          },
          {
            id: "m2",
            label: "Supplier ready",
            status: "estimated",
            estimatedAt: futureDays(5),
          },
          {
            id: "m3",
            label: "Departed origin",
            status: "estimated",
            estimatedAt: futureDays(8),
          },
        ],
      },
    ],
  },
  {
    id: "po-440",
    publicCode: "PO-440",
    status: "draft",
    currencyCode: "USD",
    totalAmount: 12_160,
    rowVersion: 1,
    procurementRequestId: "pr-881",
    procurementRequestCode: "PR-881",
    quotationCode: "QT-910",
    supplierName: "Gulf Specialty Chemicals FZE",
    supplierAcceptance: "not_required",
    versionNumber: 1,
    createdAt: hours(6),
    updatedAt: hours(2),
    items: [
      {
        id: "poi3",
        description: "Industrial solvent blend",
        quantity: 4,
        unitAmount: 2_800,
        lineAmount: 11_200,
      },
    ],
    documents: [],
    attachments: [],
    history: [
      {
        id: "poh3",
        toStatus: "draft",
        command: "create",
        actorName: "James Nwosu",
        createdAt: hours(6),
      },
    ],
    revisions: [
      {
        id: "po-440",
        versionNumber: 1,
        publicCode: "PO-440",
        status: "draft",
        totalAmount: 12_160,
        createdAt: hours(6),
        current: true,
      },
    ],
    deliveries: [],
  },
  {
    id: "po-300",
    publicCode: "PO-300",
    status: "partially_fulfilled",
    currencyCode: "USD",
    totalAmount: 2_150,
    rowVersion: 5,
    procurementRequestId: "pr-700",
    procurementRequestCode: "PR-700",
    quotationCode: "QT-700",
    supplierName: "Lagos Pack Systems Ltd",
    supplierAcceptance: "accepted",
    versionNumber: 2,
    createdAt: days(40),
    updatedAt: days(5),
    items: [
      {
        id: "poi4",
        description: "Stretch wrap rolls",
        quantity: 200,
        unitAmount: 11,
        lineAmount: 2_200,
      },
    ],
    documents: [
      {
        id: "pod2",
        name: "PO-300-v2.pdf",
        href: "#",
        kind: "purchase_order",
        uploadedAt: days(20),
      },
    ],
    attachments: [
      {
        id: "poa2",
        name: "delivery-note-1.pdf",
        href: "#",
        uploadedAt: days(5),
      },
    ],
    history: [
      {
        id: "poh4",
        fromStatus: "issued",
        toStatus: "issued",
        command: "supplier_accept",
        actorName: "Tunde Adebayo",
        createdAt: days(35),
      },
      {
        id: "poh5",
        fromStatus: "issued",
        toStatus: "partially_fulfilled",
        command: "mark_partially_fulfilled",
        actorName: "James Nwosu",
        createdAt: days(5),
      },
    ],
    revisions: [
      {
        id: "po-300-v1",
        versionNumber: 1,
        publicCode: "PO-300",
        status: "superseded",
        totalAmount: 2_250,
        createdAt: days(40),
        note: "Initial issue",
      },
      {
        id: "po-300",
        versionNumber: 2,
        publicCode: "PO-300",
        status: "partially_fulfilled",
        totalAmount: 2_150,
        createdAt: days(30),
        current: true,
        note: "Discount alignment",
      },
    ],
    deliveries: [
      {
        shipmentId: "sh-770",
        publicCode: "SH-770",
        status: "out_for_delivery",
        carrierName: "GIG Logistics",
        trackingNumber: "GIG-77821",
        estimatedArrivalAt: futureDays(1),
        href: "/shipments/sh-770",
        milestones: [
          {
            id: "m4",
            label: "Picked up",
            status: "confirmed",
            occurredAt: days(7),
          },
          {
            id: "m5",
            label: "Out for delivery",
            status: "confirmed",
            occurredAt: hours(10),
          },
          {
            id: "m6",
            label: "Delivered",
            status: "estimated",
            estimatedAt: futureDays(1),
          },
        ],
      },
    ],
  },
  {
    id: "po-199",
    publicCode: "PO-199",
    status: "cancelled",
    currencyCode: "USD",
    totalAmount: 9_100,
    rowVersion: 2,
    procurementRequestId: "pr-512",
    procurementRequestCode: "PR-512",
    supplierName: "Ankara Steel Traders AS",
    supplierAcceptance: "rejected",
    versionNumber: 1,
    createdAt: days(55),
    updatedAt: days(54),
    items: [
      {
        id: "poi5",
        description: "HR coil sample",
        quantity: 2,
        unitAmount: 4_000,
        lineAmount: 8_000,
      },
    ],
    documents: [],
    attachments: [],
    history: [
      {
        id: "poh6",
        fromStatus: "issued",
        toStatus: "cancelled",
        command: "cancel",
        reason: "Supplier rejected lead time",
        actorName: "Leo Mensah",
        createdAt: days(54),
      },
    ],
    revisions: [
      {
        id: "po-199",
        versionNumber: 1,
        publicCode: "PO-199",
        status: "cancelled",
        totalAmount: 9_100,
        createdAt: days(55),
        current: true,
      },
    ],
    deliveries: [],
  },
];
