import type {
  PlatformConfigChangeLogEntry,
  PlatformConfigDocument,
  PlatformConfigValues,
  PlatformConfigVersion,
} from "./types.js";

const hours = (h: number) =>
  new Date(Date.now() - h * 3_600_000).toISOString();

export const platformConfigValuesFixture: PlatformConfigValues = {
  siteName: "Almahbub International",
  siteDescription: "Enterprise procurement marketplace",
  timezone: "Africa/Lagos",
  defaultLocale: "en",
  defaultCurrency: "USD",
  supportEmail: "support@almahbub.example",
  brandPrimaryColor: "#155aaf",
  logoUrl: "https://cdn.example.com/brand/logo.svg",
  faviconUrl: "https://cdn.example.com/brand/favicon.ico",
  brandTagline: "Source with confidence",
  smtpHost: "smtp.example.com",
  smtpPort: 587,
  smtpUsername: "noreply",
  smtpPassword: "••••••••",
  emailFromAddress: "noreply@almahbub.example",
  emailFromName: "Almahbub International",
  notifyEmailEnabled: true,
  notifyInAppEnabled: true,
  notifySmsEnabled: false,
  notifyPushEnabled: false,
  notifyDigestHourUtc: 7,
  authMfaRequired: true,
  authPasswordMinLength: 12,
  authSessionTimeoutMinutes: 60,
  authMaxLoginAttempts: 5,
  authInviteExpiryHours: 72,
  securityStepUpPayments: true,
  securityIpAllowlist: "",
  securityAuditExportRoles: "auditor,platform_admin",
  securityBreakGlassEnabled: true,
  storageProvider: "s3",
  storageBucket: "hamd-prod-assets",
  storageRegion: "eu-west-1",
  storageMaxUploadMb: 50,
  storageVirusScanEnabled: true,
  aiAssistantEnabled: true,
  aiProvider: "none",
  aiApiKey: "",
  aiDailyQuotaPerUser: 40,
  aiRequireHumanReview: true,
  integrationWebhooksEnabled: true,
  integrationCarrierTracking: "sandbox",
  integrationErpSync: "manual",
  integrationWebhookSigningSecret: "••••••••",
  paymentsProvider: "manual",
  paymentsPublicKey: "",
  paymentsSecretKey: "",
  paymentsCurrency: "USD",
  paymentsDualControl: true,
  seoDefaultTitle: "Almahbub International - Procurement",
  seoDefaultDescription: "Enterprise procurement marketplace",
  seoCanonicalBase: "https://www.almahbub.example",
  seoRobotsDefault: "index,follow",
  seoSitemapEnabled: true,
  maintenanceEnabled: false,
  maintenanceMessage: "We are performing scheduled maintenance.",
  maintenanceAllowAdmin: true,
  maintenanceEta: "",
  weddingCampaignEnabled: false,
  weddingCampaignName: "Q3 celebration",
  weddingCampaignAudience: "customers",
  weddingCampaignStartsAt: "",
  weddingCampaignEndsAt: "",
  weddingCampaignCtaHref: "https://www.almahbub.example/celebrations",
};

export const platformConfigDocumentFixture: PlatformConfigDocument = {
  id: "cfg-platform-1",
  version: 4,
  rowVersion: 4,
  updatedAt: hours(2),
  updatedBy: "Platform Admin",
  values: platformConfigValuesFixture,
};

export const platformConfigVersionsFixture: PlatformConfigVersion[] = [
  {
    id: "cfg-v2",
    version: 2,
    summary: "Enabled MFA for privileged roles",
    createdAt: hours(200),
    authorName: "Security Reviewer",
    values: {
      ...platformConfigValuesFixture,
      authMfaRequired: false,
    },
  },
  {
    id: "cfg-v3",
    version: 3,
    summary: "Storage virus scan on; SEO defaults",
    createdAt: hours(72),
    authorName: "Platform Admin",
    values: {
      ...platformConfigValuesFixture,
      storageVirusScanEnabled: false,
    },
  },
  {
    id: "cfg-v4",
    version: 4,
    summary: "Current published configuration",
    createdAt: hours(2),
    authorName: "Platform Admin",
    values: platformConfigValuesFixture,
    current: true,
  },
];

export const platformConfigChangeLogFixture: PlatformConfigChangeLogEntry[] = [
  {
    id: "cfg-log-1",
    section: "authentication",
    summary: "authMfaRequired → true",
    actorName: "Security Reviewer",
    occurredAt: hours(200),
    version: 2,
  },
  {
    id: "cfg-log-2",
    section: "storage",
    summary: "storageVirusScanEnabled → true",
    actorName: "Platform Admin",
    occurredAt: hours(72),
    version: 3,
  },
  {
    id: "cfg-log-3",
    section: "seo",
    summary: "Updated SEO defaults and canonical base",
    actorName: "Platform Admin",
    occurredAt: hours(72),
    version: 3,
  },
  {
    id: "cfg-log-4",
    section: "maintenance",
    summary: "maintenanceEnabled confirmed false",
    actorName: "Platform Admin",
    occurredAt: hours(2),
    version: 4,
  },
];
