import "../load-env.js";
import { writeFile } from "node:fs/promises";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { createDatabaseClient } from "@hamd/database";
import { parseEnvironment } from "../config/env.js";
import { isBlockedTestBedProduct } from "../modules/catalog/application/catalog-media-importer.js";
import { createCatalogImageGenerator } from "../modules/catalog/media/create-catalog-image-generator.js";
import { createHash } from "node:crypto";
import { createCatalogMediaStore } from "../modules/catalog/infrastructure/catalog-media-store.js";
import { sniffCatalogMediaMime, validateCatalogMediaUpload } from "../modules/catalog/infrastructure/catalog-media-policy.js";
const root = join(dirname(fileURLToPath(import.meta.url)), "../../../..");
const value = (n: string) => process.argv.slice(2).find((v) => v.startsWith(`${n}=`))?.slice(n.length + 1);
const flag = (n: string) => process.argv.includes(n);
const visualModifiers = (name: string): string[] => { const n = name.toLowerCase(); const out: string[] = []; const tier = n.match(/\b([2-9])-?tier\b/); if (tier) out.push(`exactly ${tier[1]} visible storage tiers/shelves`); for (const [re, text] of [[/double-sided/, "double-sided construction usable from both sides"], [/foldable/, "visibly foldable/collapsible frame shown assembled"], [/wall-mounted/, "wall-mounted"], [/freestanding/, "self-supporting floor-standing"], [/compact/, "compact small-space proportions"], [/mini/, "mini proportions"], [/small/, "small proportions"], [/medium/, "medium proportions"], [/large|extra-large/, "large-capacity proportions"], [/heavy-duty/, "heavy-duty reinforced commercial construction"], [/industrial/, "industrial-grade construction"], [/commercial-grade/, "commercial-grade construction"], [/glass[- ]door/, "clearly visible glass-front doors with interior shelves"], [/double-door/, "double doors"], [/single-door/, "single door"], [/sliding-door/, "sliding door"], [/led|backlit|illuminated|ring-light/, "integrated visible LED/illuminated lighting"], [/drawer/, "clearly visible integrated drawers"], [/open-shelf/, "open shelving"], [/mesh/, "mesh construction"], [/ceramic[- ]basin/, "clearly visible ceramic wash basin"], [/stainless[- ]steel/, "stainless-steel construction"], [/glass/, "glass construction"], [/corded/, "visible permanent power cord"], [/cordless|rechargeable/, "rechargeable cordless design with no permanent power cord"], [/digital/, "visible digital control display"], [/hydraulic/, "hydraulic base"], [/dual-light|uv\/led/, "UV/LED dual-light-source technology"], [/double-pot|two-pot/, "exactly two separate wax pots/heating wells"], [/\bsingle\b/, "single-unit design"], [/\bdouble\b|\bdual\b/, "dual/double configuration"], [/tabletop/, "tabletop form"], [/floor-standing/, "floor-standing form"], [/portable/, "portable form"], [/lockable/, "visible lock or keyed locking mechanism"], [/mobile/, "mobile rolling commercial furniture"], [/ozone/, "visible ozone treatment function"], [/reclining/, "visibly reclining backrest"], [/roll-on/, "roll-on wax cartridge form"], [/rolling/, "visible caster wheels and rolling form"], [/standing/, "floor-standing form with stable base"], [/\bstorage\b/, "clearly visible storage layout"], [/\buv\b/, "UV sanitizing feature"], [/premium/, "premium visible finish"], [/professional/, "professional commercial construction"]] as const) if (re.test(n)) out.push(text); return [...new Set(out)]; };
const exact = (n: string) => /\b(iphone|galaxy|elitebook|gucci|bottega veneta|macbook|thinkpad|dell|lenovo|hp)\b/i.test(n) && /\b(\d+|pro|ultra|g\d|model|series|x\d)\b/i.test(n);
const makePrompt = (p: { name: string; description?: string | null }, category: string | null) => {
  const n = p.name.toLowerCase();
  const visual = "";
  const modifiers = visualModifiers(p.name);
  let subject = `physical ${p.name}`; let negative = "";
  if (n.includes("trolley")) { subject = "professional beauty salon storage trolley/cart with multiple shelves or drawers, caster wheels, compact commercial salon equipment"; negative = "not railway trolley, transport cart, or luggage trolley"; }
  else if (n.includes("manicure table")) { subject = "professional nail salon manicure workstation/table with proper tabletop, storage drawers, legroom and workspace, modern salon furniture"; negative = "not dining table, geographical Table Rock, or outdoor table"; }
  else if (n.includes("styling chair")) { subject = "professional hydraulic salon styling chair with complete upholstery, hydraulic pedestal/base and footrest"; negative = "not antique, dining, or office chair"; }
  else if (n.includes("facial steamer")) { subject = "professional facial skincare steamer, beauty salon/spa equipment with water tank, steam nozzle and adjustable arm/stand"; negative = "not food steamer, cooking appliance, ship, or locomotive"; }
  else if (n.includes("hair steamer")) { subject = "professional salon hair steamer with hood or directed steam apparatus, commercial hair treatment equipment and adjustable stand"; negative = "not cooking steamer, kitchen equipment, or historical vessel"; }
  else if (n.includes("wax heater")) { subject = "professional depilatory wax warmer, salon hair-removal equipment with removable wax pot and temperature control"; negative = "not sealing wax, candle wax, craft heater, or envelope sealing equipment"; }
  else if (n.includes("nail lamp")) { subject = "UV/LED manicure nail curing lamp, professional nail salon equipment with hand opening and timer/control area"; negative = "not miner lamp, desk lamp, or industrial lamp"; }
  else if (n.includes("cabinet")) { subject = "physical salon storage furniture with drawers/cupboards for beauty tools and products, commercial salon cabinet"; negative = "not political or government cabinet, and not a meeting"; }
  if (n.includes("glass-door") && n.includes("cabinet")) { subject = "professional salon storage cabinet with clearly visible glass-front/glass doors, interior shelves visible through glass, commercial beauty/salon storage furniture"; }
  else if (n.includes("hair dryer station")) { subject = "professional salon hair dryer station/workstation with dedicated mounting/storage area for professional hair dryers, cable-management/storage features, commercial salon furniture/equipment"; negative = "not railway station, fuel station, or generic household shelf"; }
  else if (n.includes("heavy-duty") && n.includes("hair clipper")) { subject = "professional heavy-duty barber/salon clipper with robust motor housing, durable commercial-grade body, wide precision blade, designed for frequent professional use"; }
  else if (n.includes("heavy-duty") && n.includes("styling chair")) { subject = "heavy-duty professional hydraulic salon styling chair with reinforced hydraulic base, wide stable pedestal, durable commercial upholstery, sturdy footrest, high-load commercial construction"; }
  else if (n.includes("large towel warmer")) { subject = "large-capacity professional salon/spa hot-towel warmer cabinet, front-opening insulated cabinet, multiple internal towel shelves/racks, commercial countertop or cabinet appliance"; negative = "not heated towel rail, bathroom radiator, or towel rack"; }
  else if (n.includes("led") && n.includes("mirror station")) { subject = "professional salon mirror workstation with clearly visible integrated LED perimeter/edge lighting, large illuminated mirror, salon shelf/storage workstation"; }
  else if (n.includes("mirror station")) { subject = `professional salon mirror workstation with large mirror and salon storage shelf/drawer${n.includes("double") ? ", double-sided" : n.includes("wall") ? ", wall-mounted" : ", freestanding"}`; negative = "not railway, electrical, or transport station"; }
  else if (n.includes("shampoo station")) { subject = "professional salon shampoo backwash station with ceramic/composite wash basin, integrated chair or wash unit and plumbing fixtures"; negative = "not railway station, unrelated workstation, or generic sink"; }
  if (n.includes("compact towel warmer")) { subject = "professional compact salon hot-towel warmer cabinet, countertop commercial beauty/spa appliance, front-opening insulated door, internal towel shelves/racks where visible, compact current-market design"; negative = "not heated towel rail, bathroom radiator, or towel rack"; }
  else if (n.includes("detail hair clipper")) { subject = "professional precision/detail hair trimmer, compact barber/salon finishing clipper, narrow precision cutting blade, slim ergonomic body for edging and detail work"; negative = "not full-size standard hair clipper or electric shaver"; }
  else if (n.includes("compact shampoo station")) { subject = "compact professional salon shampoo/backwash station, space-saving wash basin, integrated chair or compact wash unit, visible plumbing fixture cues"; negative = "not railway station, unrelated workstation, or generic sink"; }
  else if (n.includes("ceramic-basin shampoo station")) { subject = "professional salon backwash unit with clearly visible ceramic wash basin and integrated chair/unit"; }
  else if (n.includes("corded hair clipper")) { subject = "professional electric hair clipper with visible power cord, durable metal/polymer housing, cutting blade and optional guard attachments"; }
  else if (n.includes("cordless hair clipper")) { subject = "rechargeable professional hair clipper with durable housing, cutting blade and optional charging base/cable, no permanent power cord"; }
  if (n.includes("lockable") && n.includes("beauty storage cabinet")) subject = "professional salon storage cabinet with visible lock or locking handle and drawers/cupboards for beauty tools and products";
  else if (n.includes("lockable") && n.includes("salon trolley")) subject = "professional salon trolley with caster wheels, drawers/shelves and visible locking drawer or door mechanism";
  else if (n.includes("mobile") && n.includes("beauty storage cabinet")) subject = "salon storage cabinet on visible caster wheels, mobile rolling commercial storage furniture";
  else if (n.includes("ozone") && n.includes("facial steamer")) subject = "professional facial skincare steamer with ozone treatment function, water tank, steam nozzle and adjustable arm/stand";
  else if (n.includes("ozone") && n.includes("hair steamer")) subject = "professional salon hair steamer with ozone treatment capability, hood/directed steam apparatus and floor stand";
  else if (n.includes("portable") && n.includes("shampoo station")) subject = "portable salon shampoo wash basin/unit with mobile lightweight freestanding basin and portable water/drainage arrangement";
  else if (n.includes("reclining") && n.includes("shampoo station")) subject = "professional salon shampoo/backwash unit with integrated chair with visibly reclining backrest and wash basin";
  else if (n.includes("reclining") && n.includes("styling chair")) subject = "salon styling chair with visibly reclining backrest, hydraulic pedestal/base and footrest";
  else if (n.includes("roll-on") && n.includes("wax heater")) { subject = "professional roll-on depilatory wax cartridge heater, handheld or dock-style cartridge warmer"; negative = "not wax pot, removable bowl/pot, or sealing wax"; }
  else if (n.includes("standing") && n.includes("facial steamer")) subject = "floor-standing facial steamer with tall adjustable support pole/base and caster or pedestal base";
  else if (n.includes("standing") && n.includes("hair steamer")) subject = "floor-standing salon hair steamer with hood, adjustable vertical stand and stable/caster base";
  else if (n.includes("storage") && n.includes("manicure table")) subject = "professional manicure table with clearly visible integrated storage drawers/cabinets";
  else if (n.includes("storage") && n.includes("mirror station")) subject = "salon mirror workstation with clearly visible storage drawers, shelves or cabinets";
  else if (n.includes("tabletop") && n.includes("facial steamer")) { subject = "compact tabletop/countertop facial steamer"; negative = "not floor stand or tall adjustable support pole"; }
  else if (n.includes("tabletop") && n.includes("hair steamer")) { subject = "compact tabletop salon hair steamer"; negative = "not floor stand, adjustable standing pole, or caster base"; }
  else if (n.includes("uv") && n.includes("towel warmer")) { subject = "professional salon/spa hot-towel warmer cabinet with front-opening door, internal racks and UV sanitizing feature"; negative = "not towel rail, bathroom radiator, or UV lamp by itself"; }
  else if (n.includes("shampoo basin unit")) subject = "professional salon shampoo wash-basin unit with dedicated hair-washing basin and commercial plumbing fixtures, salon backwash equipment";
  else if (n === "professional hair clipper") subject = "professional commercial barber/salon hair clipper with durable motor housing, precision cutting blade and ergonomic body";
  else if (/chest freezer/.test(n)) { subject = `modern ${n.includes("large") ? "large-capacity " : n.includes("compact") ? "compact " : ""}chest freezer, horizontal insulated freezer body, top-opening hinged lid, complete body and base visible`; negative = "not refrigerator, upright freezer, storage chest, or cooler box"; }
  else if (/upright freezer/.test(n)) { subject = "modern upright vertical freezer appliance with front-opening insulated door and tall cabinet form"; negative = "not chest freezer or ordinary storage cabinet"; }
  else if (/refrigerator|fridge/.test(n)) subject = `modern ${n.includes("side-by-side") ? "side-by-side" : n.includes("french-door") ? "French-door" : n.includes("double-door") ? "double-door" : n.includes("single-door") ? "single-door" : ""} refrigerator appliance with clearly visible door layout`;
  else if (/microwave/.test(n)) { subject = "modern countertop microwave oven with front glass door, control panel and complete compact appliance body"; negative = "not conventional baking oven or industrial furnace"; }
  else if (/air fryer/.test(n)) subject = `modern countertop air fryer with enclosed cooking body, ${n.includes("dual") ? "exactly two separate cooking drawers/baskets" : "pull-out basket/drawer"} and digital or manual controls`;
  else if (/\b(washing machine|washer)\b/.test(n)) { subject = `modern washing machine with ${n.includes("front") ? "front-load" : n.includes("top") ? "top-load" : n.includes("twin") ? "two visibly separate tubs" : "single tub"} laundry appliance body`; negative = "not dishwasher"; }
  else if (/toaster oven/.test(n)) { subject = "countertop toaster oven with front glass door and internal rack"; negative = "not pop-up toaster"; }
  else if (/toaster/.test(n)) subject = `modern ${n.includes("4-slice") ? "four-slot" : "two-slot"} pop-up toaster with complete compact body`;
  else if (/electric kettle/.test(n)) subject = "modern electric water kettle with handle, spout and power base";
  else if (/dishwasher/.test(n)) { subject = `modern ${n.includes("built-in") ? "built-in kitchen" : n.includes("commercial") ? "commercial kitchen" : n.includes("compact") ? "compact countertop" : "kitchen"} dishwasher with front-opening door and dishwashing chamber`; negative = "not washing machine, clothes washer, or laundry appliance"; }
  else if (/coffee maker|coffee machine/.test(n)) { subject = n.includes("bean-to-cup") ? "automatic bean-to-cup coffee machine with visible bean hopper, integrated grinder, dispensing spouts and drip tray" : n.includes("capsule") ? "compact capsule/pod coffee machine with brewing head and cup platform" : n.includes("drip") ? "electric drip coffee machine with water reservoir, filter basket and glass or thermal carafe" : "modern coffee brewing machine with water reservoir and dispensing area"; negative = "not kettle"; }
  else if (/water dispenser/.test(n)) subject = n.includes("bottom-load") ? "freestanding bottom-loading water dispenser with lower enclosed bottle compartment and hot/cold dispensing controls" : "modern water dispenser with bottle mounting position and dispensing taps";
  else if (/electric oven/.test(n)) subject = `modern ${n.includes("built-in") ? "built-in kitchen" : n.includes("commercial") ? "heavy-duty commercial" : "countertop"} electric baking oven with front glass door, internal cavity and control panel`;
  else if (/vacuum cleaner/.test(n)) subject = n.includes("canister") ? "canister vacuum cleaner with wheeled compact canister body, flexible hose and cleaning wand" : `modern ${n.match(/upright|stick|handheld|robot|wet\/dry/)?.[0] ?? "household"} vacuum cleaner with complete recognizable form`;
  else if (/air conditioner/.test(n)) subject = n.includes("cassette") ? "ceiling cassette air-conditioning indoor unit with square ceiling panel and multi-directional outlets" : "modern air-conditioning appliance with vents and control panel";
  else if (/air purifier/.test(n)) subject = `${n.includes("commercial") ? "large-capacity commercial" : n.includes("compact") ? "compact home" : "modern"} air purifier with visible intake and outlet grilles`;
  else if (/blender/.test(n)) subject = n.includes("commercial") ? "heavy-duty commercial countertop blender with robust motor base, large blending jar and secure lid" : n.includes("hand blender") ? "handheld immersion blender with long blending shaft and motor handle" : "countertop electric blender with motor base, blending jar and lid";
  else if (/clothes dryer/.test(n)) subject = `${n.includes("commercial") ? "commercial" : n.includes("compact") ? "compact" : "dedicated"} tumble clothes dryer with front-loading drum and laundry appliance body`;
  else if (/electric kettle/.test(n)) subject = `${n.includes("commercial") ? "professional high-capacity commercial" : "modern"} electric water kettle with handle, spout and power base`;
  else if (/microwave/.test(n)) subject = `${n.includes("commercial") ? "commercial-duty" : "modern"} microwave oven with front glass door and control panel`;
  else if (/freezer/.test(n)) subject = n.includes("upright") ? "modern upright vertical freezer with tall insulated cabinet and front-opening door" : "modern chest freezer with horizontal insulated body and top-opening lid";
  else if (/\b(washing machine|washer)\b/.test(n)) { subject = `modern ${n.includes("automatic") ? "automatic" : ""} washing machine with control panel and proper laundry-appliance form`; negative = "not dishwasher"; }
  else if (/television|4k/.test(n)) subject = "modern flat-panel television with thin bezel and complete screen with stand/base where appropriate";
  else if (/electric iron/.test(n)) subject = n.includes("cordless") ? "cordless household electric iron with soleplate, handle and charging base, no permanent attached cord" : n.includes("dry") ? "dry electric iron with solid soleplate and temperature control" : "household electric steam iron with soleplate, handle and controls";
  else if (/electric cooker/.test(n)) subject = "modern household electric cooking appliance/range with visible electric cooking surface or hotplates and control area";
  return `Photorealistic ecommerce product photography of ${subject}. Category: ${category ?? "general"}. ${visual || modifiers.length ? `Visible physical characteristics: ${[visual, ...modifiers].filter(Boolean).join(", ")}. ` : ""}Modern current-market design, realistic proportions and materials, complete product visible, centered with safe margins, front or three-quarter view, warm white/light gray studio background, soft realistic shadow, no people unless essential, no unrelated objects, no text, no watermark, no fake or invented logo, square 1:1. Negative constraints: ${negative || "none"}`.trim();
};
const invalidPrompt = (prompt: string) => /with and|and \.|on the ,|not a ed-|does not confirm|quantity|destination|warehouse stock|procurement|buyers request|can be procured|\bprovide\b|\bspecify\b/i.test(prompt);
async function main() {
  const env = parseEnvironment(process.env); if (!env.DATABASE_URL) throw new Error("DATABASE_URL is required.");
  const limit = Number(value("--limit") ?? 100); if (!Number.isInteger(limit) || limit <= 0) throw new Error("--limit must be positive");
  const execute = flag("--execute"); const db = createDatabaseClient(env.DATABASE_URL); const products = await db.product.findMany({ where: { status: "published" }, orderBy: { slug: "asc" }, select: { id: true, slug: true, name: true, description: true, category: { select: { slug: true, name: true } }, images: { select: { id: true, url: true, storageKey: true, position: true, isPrimary: true } } } });
  const generator = createCatalogImageGenerator(env); const store = createCatalogMediaStore({ uploadRoot: env.UPLOAD_ROOT, driver: env.CATALOG_MEDIA_DRIVER, nodeEnv: env.NODE_ENV, s3Bucket: env.CATALOG_MEDIA_S3_BUCKET, s3Region: env.AWS_REGION, s3AccessKeyId: env.AWS_ACCESS_KEY_ID, s3SecretAccessKey: env.AWS_SECRET_ACCESS_KEY, s3PublicBaseUrl: env.CATALOG_MEDIA_S3_PUBLIC_BASE_URL, supabaseUrl: env.CATALOG_MEDIA_SUPABASE_URL, supabaseServiceRoleKey: env.CATALOG_MEDIA_SUPABASE_SERVICE_ROLE_KEY, supabaseBucket: env.CATALOG_MEDIA_SUPABASE_BUCKET });
  const regenerate = value("--regenerate");
  if (regenerate) {
    if (value("--limit") || value("--after") || value("--category") || value("--product")) throw new Error("--regenerate accepts only one explicit product slug and --execute.");
    const product = products.find((p) => p.slug === regenerate);
    if (!product) throw new Error(`Product not found: ${regenerate}`);
    const current = product.images.find((i) => (i.isPrimary || i.position === 0) && i.url.trim());
    const category = product.category?.name ?? product.category?.slug ?? null;
    const generatedPrompt = makePrompt(product, category);
    const base = { productId: product.id, productSlug: product.slug, productName: product.name, currentPrimaryImage: current?.url ?? null, strategy: exact(product.name) ? "current_product_research" : "generated_generic", generatedPrompt };
    if (exact(product.name)) { console.log(JSON.stringify({ ...base, status: "current_product_research" }, null, 2)); return; }
    if (!current) throw new Error("Regeneration requires an existing valid primary ProductImage.");
    if (!execute || !generator) { console.log(JSON.stringify({ ...base, status: "regeneration_ready" }, null, 2)); return; }
    try {
      const generated = await generator.generate({ prompt: generatedPrompt, productSlug: product.slug });
      const mime = sniffCatalogMediaMime(generated.bytes); const dimensions = generated.width && generated.height ? { width: generated.width, height: generated.height } : null;
      const issues = !mime || !dimensions || dimensions.width < 400 || dimensions.height < 400 ? ["unsupported format or dimensions"] : validateCatalogMediaUpload({ filename: `${product.slug}.png`, mimeType: mime, sizeBytes: generated.bytes.length, kind: "image", bytes: generated.bytes });
      if (issues.length) throw new Error(`validation_failed: ${issues.join(", ")}`);
      const hash = createHash("sha256").update(generated.bytes).digest("hex"); const stored = await store.put({ productId: product.id, originalFilename: `${product.slug}-regenerated.png`, bytes: generated.bytes });
      const replacement = await db.$transaction(async (tx) => { await tx.productImage.delete({ where: { id: current.id } }); return tx.productImage.create({ data: { productId: product.id, url: stored.publicUrl, storageKey: stored.filename, mimeType: mime, fileSize: generated.bytes.length, position: 0, isPrimary: true, altText: product.name } }); });
      console.log(JSON.stringify({ ...base, provider: generated.provider, model: generated.model, size: generated.size, quality: generated.quality, newSha256: hash, oldProductImageId: current.id, oldStorageKey: current.storageKey, newProductImageId: replacement.id, newStorageKey: stored.filename, newMediaUrl: stored.publicUrl, replacementStatus: "regenerated", orphan_cleanup_required: true }, null, 2));
    } catch (error) { console.error(JSON.stringify({ ...base, replacementStatus: error instanceof Error && error.message.startsWith("validation_failed") ? "validation_failed" : "generation_failed", reason: error instanceof Error ? error.message : "Regeneration failed." }, null, 2)); process.exitCode = 1; }
    return;
  }
  const rows = products.filter((p) => (!value("--product") || p.slug === value("--product")) && !p.images.some((i) => (i.isPrimary || i.position === 0) && i.url.trim()) && !isBlockedTestBedProduct(p.slug) && (!value("--after") || p.slug > value("--after")!) && (!value("--category") || p.category?.slug === value("--category"))).slice(0, limit).map((p) => { const research = exact(p.name); const category = p.category?.name ?? p.category?.slug ?? null; const generic = p.name.trim().length >= 4; const generatedPrompt = makePrompt(p, category); const homeModifiers = p.category?.slug === "home-appliances" ? (p.name.match(/compact|mini|small|medium|large|extra-large|commercial|heavy-duty|professional|portable|tabletop|freestanding|built-in|wall-mounted|floor-standing|digital|manual|automatic|semi-automatic|single-door|double-door|single-lid|double-lid|single-basket|dual-basket|single-tub|twin-tub|top-load|front-load|top-freezer|bottom-freezer|side-by-side|french-door|single|double|dual|[2-6]-burner|[24]-slice|stainless-steel|glass|corded|cordless/gi) ?? []) : []; const modifiers = [...new Set([...visualModifiers(p.name), ...homeModifiers])]; const missing = modifiers.filter((m) => !generatedPrompt.toLowerCase().includes(m.toLowerCase())); const invalid = invalidPrompt(generatedPrompt); const contradiction = /tabletop/.test(p.name.toLowerCase()) && /floor[- ]standing|support pole|caster base/.test(generatedPrompt.toLowerCase()) || /portable/.test(p.name.toLowerCase()) && /permanently fixed/.test(generatedPrompt.toLowerCase()) || /roll-on/.test(p.name.toLowerCase()) && /wax pot|removable bowl/.test(generatedPrompt.toLowerCase()); const knownHome = p.category?.slug === "home-appliances" && /television|coffee maker|water dispenser|dishwasher|oven|vacuum cleaner|air conditioner|air purifier|blender|clothes dryer|kettle|microwave|freezer|washing machine|refrigerator|iron|cooker|water heater/.test(p.name.toLowerCase()); const insufficient = knownHome && generatedPrompt.toLowerCase().startsWith("photorealistic ecommerce product photography of physical "); return { productId: p.id, productSlug: p.slug, productName: p.name, category, strategy: research ? "current_product_research" : generic ? "generated_generic" : "manual_review", classification: research ? "exact_branded_product" : generic ? "generic_product" : "manual_review", generatedPrompt, preservedVisualModifiers: modifiers, generationProvider: generator ? "openai" : null, status: invalid || missing.length || contradiction || insufficient ? "manual_review" : research ? "current_product_research" : generic ? (generator ? "generation_ready" : "generation_provider_not_configured") : "manual_review", reason: invalid ? "invalid_generation_prompt" : contradiction ? "contradictory_generation_prompt" : insufficient ? "insufficient_product_identity" : missing.length ? "visual_modifier_not_preserved" : undefined, product: p }; });
  if (execute && generator) for (const row of rows.filter((r) => r.status === "generation_ready")) { const existing = await db.productImage.findFirst({ where: { productId: row.productId, OR: [{ isPrimary: true }, { position: 0 }] }, select: { id: true, url: true } }); if (existing?.url.trim()) { row.status = "kept_existing"; continue; } const generated = await generator.generate({ prompt: row.generatedPrompt, productSlug: row.productSlug }); const hash = createHash("sha256").update(generated.bytes).digest("hex"); const stored = await store.put({ productId: row.productId, originalFilename: `${row.productSlug}-generated.png`, bytes: generated.bytes }); await db.productImage.create({ data: { productId: row.productId, url: stored.publicUrl, storageKey: stored.filename, mimeType: generated.mimeType, fileSize: generated.bytes.length, position: 0, isPrimary: true, altText: row.productName } }); Object.assign(row, { status: "generated", provider: generated.provider, model: generated.model, size: generated.size, quality: generated.quality, sha256: hash, storageKey: stored.filename, mediaUrl: stored.publicUrl, mimeType: generated.mimeType, width: generated.width, height: generated.height }); }
  await writeFile(join(root, "docs", "generated-product-media-provenance.json"), JSON.stringify({ generatedAt: new Date().toISOString(), execute: flag("--execute"), rows }, null, 2), "utf8");
  console.log(JSON.stringify({ selected: rows.length, generationReady: rows.filter((r) => r.status === "generation_ready").length, currentProductResearch: rows.filter((r) => r.status === "current_product_research").length, manualReview: rows.filter((r) => r.status === "manual_review").length, providerNotConfigured: rows.filter((r) => r.status === "generation_provider_not_configured").length, failed: rows.filter((r) => r.status === "failed").length, lastProcessedSlug: rows.at(-1)?.productSlug ?? null }, null, 2)); rows.forEach((r) => console.log(JSON.stringify({ productName: r.productName, strategy: r.strategy, generatedPrompt: r.generatedPrompt, status: r.status })));
}
main().catch((e) => { console.error(e); process.exitCode = 1; });
