export type ProposalGroup = {
  key: string;
  categorySlugs: string[];
  context: string;
  names: string[];
};
/** Curated product families, not automatically inserted records or asserted current models. */
export const proposalGroups: ProposalGroup[] = [
  {
    key: "mobile",
    categorySlugs: ["iphones-gadgets"],
    context: "mobile communication and field computing",
    names: [
      "Apple iPhone",
      "Samsung Galaxy smartphone",
      "Apple iPad",
      "Samsung Galaxy tablet",
      "Rugged smartphone",
      "Rugged tablet",
      "Android tablet",
      "E-reader",
      "Smartwatch",
      "Wireless earbuds",
      "Over-ear headphones",
      "Portable power bank",
      "Wireless charging stand",
      "Portable Bluetooth speaker",
      "Mobile hotspot",
    ],
  },
  {
    key: "office",
    categorySlugs: ["office-business"],
    context: "business computing and document workflows",
    names: [
      "HP business laptop",
      "Lenovo business laptop",
      "Dell business laptop",
      "Business desktop computer",
      "All-in-one computer",
      "Office monitor",
      "Colour laser multifunction printer",
      "Monochrome laser printer",
      "Document scanner",
      "Photocopier",
      "Office projector",
      "Document laminator",
      "Document binding machine",
      "Document shredder",
      "Conference camera",
      "Webcam",
      "Business network router",
      "Network switch",
      "Wireless access point",
      "UPS system",
      "Laptop docking station",
      "Portable external SSD",
      "Network attached storage",
      "Conference speakerphone",
      "Interactive meeting display",
    ],
  },
  {
    key: "appliances",
    categorySlugs: ["home-appliances"],
    context: "household and commercial kitchen operations",
    names: [
      "Front-load washing machine",
      "Chest freezer",
      "Upright refrigerator",
      "Dishwasher",
      "Split air conditioner",
      "Clothes dryer",
      "Microwave oven",
      "Electric oven",
      "Gas cooker",
      "Air fryer",
      "Electric kettle",
      "Countertop blender",
      "Stand mixer",
      "Rice cooker",
      "Water dispenser",
      "Electric iron",
      "Vacuum cleaner",
      "Induction cooker",
      "Cooker hood",
      "Espresso machine",
      "Food processor",
      "Ice maker",
      "Air purifier",
      "Dehumidifier",
    ],
  },
  {
    key: "clothing",
    categorySlugs: ["ready-to-wear", "fashion-textiles"],
    context: "ready-to-wear retail and occasion dressing",
    names: [
      "Kaftan",
      "Senator outfit",
      "Agbada outfit",
      "Corporate suit",
      "Abaya",
      "Formal shirt",
      "Coordinated casual set",
      "Maxi dress",
      "Modest gown",
      "Women's two-piece set",
      "Women's tailored suit",
      "Occasion gown",
      "Knit cardigan",
      "Tailored trousers",
      "Polo shirt",
      "Gucci ready-to-wear dress",
      "Bottega Veneta ready-to-wear jacket",
      "Trench coat",
    ],
  },
  {
    key: "footwear",
    categorySlugs: ["footwear", "shoes", "fashion-textiles"],
    context: "footwear retail and professional wear",
    names: [
      "Lifestyle sneaker",
      "Running sneaker",
      "Leather sneaker",
      "Leather loafer",
      "Oxford shoe",
      "Derby shoe",
      "Chelsea boot",
      "Safety boot",
      "Heeled court shoe",
      "Ballet flat",
      "Leather sandal",
      "Slide sandal",
      "Palm slipper",
      "Nike running shoe",
      "Adidas lifestyle sneaker",
    ],
  },
  {
    key: "bags",
    categorySlugs: ["bags-accessories", "fashion-textiles"],
    context: "fashion accessories and everyday carrying",
    names: [
      "Structured handbag",
      "Leather shoulder bag",
      "Tote bag",
      "Crossbody bag",
      "Business briefcase",
      "Travel duffel bag",
      "Laptop backpack",
      "Leather belt",
      "Leather wallet",
      "Passport holder",
      "Wheeled luggage case",
      "Cosmetic bag",
      "Card holder",
      "Gucci handbag",
      "Bottega Veneta handbag",
    ],
  },
  {
    key: "machinery",
    categorySlugs: ["industrial-machinery", "machineries"],
    context: "industrial production, maintenance and material handling",
    names: [
      "Industrial centrifugal pump",
      "Submersible pump",
      "Air compressor",
      "Diesel generator",
      "Electric motor",
      "Industrial gearbox",
      "Welding machine",
      "Drill press",
      "Bench grinder",
      "Workshop lathe",
      "Milling machine",
      "Metal cutting bandsaw",
      "Packaging machine",
      "Liquid filling machine",
      "Heat sealing machine",
      "Pallet jack",
      "Electric chain hoist",
      "Hydraulic press",
      "Industrial pressure washer",
      "Belt conveyor",
    ],
  },
  {
    key: "spares",
    categorySlugs: [
      "industrial-spare-parts",
      "mechanical-spare-parts",
      "machineries",
    ],
    context:
      "industrial maintenance with dimensions and compatibility confirmed before supply",
    names: [
      "Deep-groove ball bearing",
      "Tapered roller bearing",
      "Spherical roller bearing",
      "Thrust bearing",
      "Pillow-block bearing",
      "V-belt",
      "Timing belt",
      "Roller chain",
      "Sprocket",
      "Pulley",
      "Flexible coupling",
      "Drive shaft",
      "Mechanical seal",
      "Oil seal",
      "Ball valve",
      "Gate valve",
      "Butterfly valve",
      "Check valve",
      "Globe valve",
      "Solenoid valve",
      "Pipe flange",
      "Pipe elbow",
      "Pipe tee",
      "Pipe reducer",
      "Industrial gasket",
      "Industrial hose",
      "Hydraulic hose",
      "Pipe fitting",
      "Hydraulic gear pump",
      "Hydraulic cylinder",
      "Hydraulic valve",
      "Hydraulic fitting",
      "Pneumatic cylinder",
      "Pneumatic valve",
      "Air regulator",
      "Pneumatic fitting",
      "Gear motor",
      "Air filter",
      "Oil filter",
      "Fuel filter",
      "Hydraulic filter",
      "Generator AVR",
      "Starter motor",
      "Alternator component",
      "Fuel pump",
      "Engine water pump",
      "Engine belt",
      "Engine gasket set",
      "Compressor filter",
      "Pressure switch",
      "Compressor maintenance kit",
    ],
  },
  {
    key: "medical",
    categorySlugs: ["medical-equipments"],
    context:
      "clinical and laboratory procurement with intended use reviewed before supply",
    names: [
      "Examination couch",
      "Hospital trolley",
      "Wheelchair",
      "Laboratory microscope",
      "Laboratory centrifuge",
      "Patient monitor",
      "Digital blood pressure monitor",
      "Infusion pump",
      "Medical suction machine",
      "Oxygen concentrator",
      "Laboratory refrigerator",
      "Autoclave sterilizer",
      "Examination lamp",
      "Medical weighing scale",
      "Diagnostic ultrasound system",
      "Laboratory pipette",
    ],
  },
  {
    key: "salon",
    categorySlugs: ["beauty-spa-salon"],
    context: "professional salon, barber and beauty treatment facilities",
    names: [
      "Salon trolley",
      "Manicure table",
      "Hydraulic salon styling chair",
      "Salon mirror workstation",
      "Professional salon shampoo station",
      "Facial steamer",
      "Salon hair steamer",
      "Depilatory wax heater",
      "UV/LED nail curing lamp",
      "Beauty storage cabinet",
      "Cordless hair clipper",
      "Hair dryer station",
      "Hot-towel warmer cabinet",
      "Barber chair",
      "Salon hood dryer",
      "Beauty treatment bed",
    ],
  },
];
